### ISSUE TITLE
Support backup sidecar's own NodeSelector

### ISSUE THREAD

**Issue by junghoahnsc** [coreos/etcd-operator#1009]
A backup sidecar pod seems to use the NodeSelector of cluster's pod. So, When I set anti-affinity with etcd pods, one etcd pod couldn't be scheduled due to a backup sidecar pod.

It would be good to give a flexibility to set the backup sidecar's own NodeSelector.

**Comment by xiang90** [comment]
reasonable. we will add a podpolicy into backup policy. so backup pod will only respect the pod policy there.
