### ISSUE TITLE
tls doesn't support self-hosted etcd now

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#1010]
Currently we hard-code self-hosted etcd to use url scheme as "http".

Checklist:
- [x] https://github.com/coreos/etcd-operator/issues/1102

**Comment by xiang90** [comment]
@hongchaodeng this is fixed now, right?

**Comment by hongchaodeng** [comment]
One more PR to go: https://github.com/coreos/etcd-operator/pull/1103
