### ISSUE TITLE
pod anti-affinity label means that self-hosted etcd can't bootstrap on a single master

### ISSUE THREAD

**Issue by diegs** [coreos/etcd-operator#1012]
#999 adds a restriction so only one etcd pod can run on any node. If I understand correctly, this could cause a problem if we are running on a single master: since the temporary etcd will already be running there, the self-hosted pod will not be schedulable.

cc @aaronlevy

**Comment by xiang90** [comment]
> temporary etcd

the seed etcd should not have label attached, right?

**Comment by hongchaodeng** [comment]
It only uses label "k8s-app: boot-etcd".

**Comment by xiang90** [comment]
yea. i mean it does not have the label we attach for anti-affinity

**Comment by diegs** [comment]
Ah, yes, looks like I misunderstood the PR. Should be ok then.
