### ISSUE TITLE
Return backup status when return from the /backupnow endpoint?

### ISSUE THREAD

**Issue by yifan-gu** [coreos/etcd-operator#1018]
During oob discussion with @xiang90 , we think it would be nice if the backup service can return the recent backup status to the caller when `/backupnow` is called, so the caller can know which backup is created recently and save that information in case of future restore.

So the proposed behavior here woud be:
- If a backup is skipped, then `GET /backupnow` only returns 200.
- If a backup is created, then `GET /backupnow` returns 200, plus a backup status json object in the response body.

**Comment by xiang90** [comment]
yea. i will fix this.

**Comment by yifan-gu** [comment]
@xiang90 Another optional idea I have is providing more parameters for the request, e.g. `GET /backupnow?force=true` so it can force the service to do a backup and return the backup status on success. So that the caller doesn't have to loop over the `GET` request until a change is made in etcd store.
