### ISSUE TITLE
Mention helm chart in installation guide

### ISSUE THREAD

**Issue by ahmetb** [coreos/etcd-operator#1040]
It looks like etcd-operator is packaged as a Helm chart: 

https://kubeapps.com/charts/stable/etcd-operator
https://github.com/kubernetes/charts/tree/master/stable/etcd-operator

Is there any reason to not to document it in the https://github.com/coreos/etcd-operator/blob/master/doc/user/op_guide.md ?

**Comment by hongchaodeng** [comment]
@ahmetb Would you like to update the doc?

**Comment by ahmetb** [comment]
@hongchaodeng I have to follow some internal approval process to contribute. It might be faster for you to do it.
