### ISSUE TITLE
e2e: There was no backup made but e2e/util.makeBackup() proceeded

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#1047]
```
--- FAIL: TestClusterRestoreS3 (332.17s)
    --- FAIL: TestClusterRestoreS3/restore_cluster_from_backup_on_S3 (0.00s)
        --- FAIL: TestClusterRestoreS3/restore_cluster_from_backup_on_S3/restore_from_a_different_name_cluster (332.16s)
        	util.go:38: 2017-05-03 17:43:55.060958176 +0000 UTC created etcd cluster: test-etcd-4db4l
        	util.go:38: 2017-05-03 17:44:36.79650992 +0000 UTC created etcd cluster: test-etcd-9js60
```

In operator logs, the newly restored cluster couldn't start because no backup was available:
```
"fail to do disaster recovery: check backup existence (test-etcd-9js60-backup-sidecar:19999) failed: unexpected status code (404 Not Found), response ()
```

Searched through our log infra, I couldn't find any logs for backup pod of cluster "test-etcd-4db4l".

[e2e/util.makeBackup()](https://github.com/coreos/etcd-operator/blob/235640b7245a50c7a8bfef7eefc60267e17e35f4/test/e2e/util.go#L64-L91) had proceeded without any error.

**Comment by hongchaodeng** [comment]
Another failure happened. We dig into the logs. This time the backup sidecar showed up and it had made a backup.

**Comment by hongchaodeng** [comment]
Closing it. The operator image is outdated.

**Comment by brendandburns** [comment]
@hongchaodeng I'm seeing this with the 0.5.2 operator... Was there a bug that was fixed that caused this?

Thanks!

**Comment by hongchaodeng** [comment]
@brendandburns 
I remembered this issue is due to some internal setup, not in the code. So I found the problem and fixed it, and closed this issue.

For your bug, it might be something different. Could you provide more details and logs? Maybe create an new issue?
