### ISSUE TITLE
Being able to retrieve a specific backup?

### ISSUE THREAD

**Issue by yifan-gu** [coreos/etcd-operator#1079]
Today, we can only download the latest backup from the operator, but sometimes we might want a specific backup instead.

For example, such scenario can happen during the tectonic upgrade:
- tco triggers an initial backup before upgrading anything
- tco performs upgrades accordingly after the backup succeeds
- new backups could be made afterwards automatically or triggered by other components

However, if a failure happens later, we'd like restore to the initial backup instead of the later backups so that the cluster is in a cleaner state than in the middle of upgrade.

In order to achieve this, the backup status returned by `/backupnow` or `/backup` also needs to include a snapshot index/version that can be used to retrieve the specific backup later.

@hasbro17 @hongchaodeng @xiang90

**Comment by hongchaodeng** [comment]
Is the question to restore from a specific backup or get a backup?

**Comment by yifan-gu** [comment]
@hongchaodeng Get a backup

**Comment by xiang90** [comment]
@yifan-gu 

> However, if a failure happens later, we'd like restore to the initial backup instead of the later backups so that the cluster is in a cleaner state than in the middle of upgrade.

In this case, you will need to manually get the backup from the actual storage. 

We discussed this case with @aaronlevy and @sym3tri. Yes, it is possible to get backups from the sidecar, but then we still need to assume the in-cluster network accessibility and the availability of sidecar pod. There is no clear win over simply getting the backup from the actual storage (s3, or PV). 

Do you have any other use cases in mind?

**Comment by yifan-gu** [comment]
@xiang90 It would be nice if we can ask the sidecar for a specific reversion of the backup, but downloading it from the actual storage is ok. 
In both cases, we still want `/backupnow` to return a reversion number so we can use when downloading the backup.

**Comment by hongchaodeng** [comment]
>  we still want /backupnow to return a reversion number

You mean "revision"?
That should be fine. We can add that.

**Comment by yifan-gu** [comment]
@hongchaodeng Yeah, I mean the `${CLUSTER_REVISION}` in the [example](https://github.com/coreos/etcd-operator/blob/master/doc/user/download_backup.md#get-backup-from-s3)
