### ISSUE TITLE
cluster failed to setup: unable to access s3 bucket

### ISSUE THREAD

**Issue by ssubramanian123** [coreos/etcd-operator#1088]
We are trying to create etcd cluster with backup in S3 and getting "cluster failed to setup: unable to access s3 bucket". Here is the steps followed

1.  Created operator  - up and running (followed steps https://github.com/coreos/etcd-operator/blob/master/doc/design/s3_backup.md) 
- Created secret object
- Created configmap
- Created operator
2. When creating cluster, operator throws below exception
`time="2017-05-11T21:00:32Z" level=error msg="cluster failed to setup: unable to access bucket s3://{{S3-bucket}}: MissingRegion: could not find region configuration" cluster-name=vault-etcd-cluster pkg=cluster 
time="2017-05-11T21:00:32Z" level=warning msg="fail to handle event: ignore failed cluster (vault-etcd-cluster). Please delete its TPR" pkg=controller `

Note : Tried s3 bucket name as --backup-s3-bucket=s3://{{bucket name}} and --backup-s3-bucket={{bucket name}}

Can somebody throw some lights on why we get missing region configuration / unable to access s3 bucket error? Able to access S3 bucket with AWS credentials, configmap file looks good.

**Comment by hongchaodeng** [comment]
> Created secret object
> Created configmap
> ...

Can you give detailed steps?

**Comment by hongchaodeng** [comment]
The doc you link to is a design doc. It's outdated.
Please see this one instead: https://github.com/coreos/etcd-operator/blob/master/doc/user/backup_config.md

**Comment by ssubramanian123** [comment]
Thanks @hongchaodeng let me try with new doc.

**Comment by ssubramanian123** [comment]
@hongchaodeng I verified new document and we are following the same steps and getting the error. Here is the detailed steps with file details.

Steps:

kubectl create secret generic aws --from-file=aws-crendentials --namespace=vault

aws-crendentials
`[default]
aws_access_key_id=xxxx
aws_secret_access_key=xxxx`


kubectl create configmap aws --from-file=aws-config --namespace=vault
aws-config
`[default]
region=us-east-1`



Deployed Operator 

kubectl create -f etcd/etcd-operator.yaml --namespace=vault

`etcd-operator.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd-operator
  namespace: vault
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: etcd-operator
    spec:
      containers:
      - name: etcd-operator
        image: quay.io/coreos/etcd-operator:v0.2.6
        command:
        - /usr/local/bin/etcd-operator
        - --backup-aws-secret=aws
        - --backup-aws-config=aws
        - --backup-s3-bucket=my-bucket
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name`

Deploy Cluster

kubectl create -f etcd/etcd-cluster.yaml 

etcd-cluster.yaml

`apiVersion: "etcd.coreos.com/v1beta1"
kind: "Cluster"
metadata:
  name: "vault-etcd-cluster"
  namespace: vault
spec:
  size: 3
  version: "3.1.4"
  backup:
    backupIntervalInSecond: 30
    maxBackups: 5
    storageType: "S3"`


operator log shows as below


`time="2017-05-11T23:05:48Z" level=info msg="starts running from watch version: 132958" pkg=controller 
time="2017-05-11T23:05:48Z" level=info msg="start watching at 132958" pkg=controller 
time="2017-05-11T23:09:15Z" level=error msg="cluster failed to setup: unable to access bucket my-bucket: MissingRegion: could not find region configuration" cluster-name=vault-etcd-cluster pkg=cluster 
time="2017-05-11T23:09:15Z" level=warning msg="fail to handle event: ignore failed cluster (vault-etcd-cluster). Please delete its TPR" pkg=controller`

**Comment by hongchaodeng** [comment]
File names are wrong:
aws-crendentials -> crendentials
aws-config -> config

**Comment by ssubramanian123** [comment]
thanks @hongchaodeng, really appreciate your quick reply. It fixed the issues.
