### ISSUE TITLE
cluster failed to setup : error retrieving resource lock vault

### ISSUE THREAD

**Issue by ssubramanian123** [coreos/etcd-operator#1098]
I followed below document to create etcd operator and clusters. 
https://github.com/coreos/etcd-operator/blob/master/doc/user/backup_config.md

But while running cluster getting error as below in operator log and cluster didnt create.

`E0516 03:50:55.532973       1 election.go:226] error retrieving resource lock vault/etcd-operator: the server has asked for the client to provide credentials (get endpoints etcd-operator)
E0516 03:50:59.834406       1 election.go:226] error retrieving resource lock vault/etcd-operator: the server has asked for the client to provide credentials (get endpoints etcd-operator)
E0516 03:51:04.890999       1 election.go:226] error retrieving resource lock vault/etcd-operator: the server has asked for the client to provide credentials (get endpoints etcd-operator)
`

Can anyone please help me with the reason for above issue?

Same steps follwed in https://github.com/coreos/etcd-operator/issues/1088 and it worked for different env.

**Comment by hongchaodeng** [comment]
@ssubramanian123 
This is typical RBAC issue.
Please set up RBAC correctly according to [the docs](https://github.com/coreos/etcd-operator/blob/master/doc/user/rbac.md).

**Comment by hongchaodeng** [comment]
@ssubramanian123 
What environment (GKE, AWS) are you running? There are usually default account with admin roles to let you play with.

**Comment by ssubramanian123** [comment]
Thanks @hongchaodeng for your quick response. I tried this in our AWS pre-develop env and it worked fine, now trying to deploy in AWS Develop env. I am pretty new to k8s, not sure on RBAC. Let me go through docs and try to setup as stated.

**Comment by ssubramanian123** [comment]
@hongchaodeng I was trying to create the clusters on existing vault namespace. So now I completely deleted namespaces and trying to create again.

During cluster creation getting below error. Though I am able to access S3 bucket with same credentials.  Any thought?

`time="2017-05-16T16:49:06Z" level=error msg="cluster failed to setup: unable to access bucket com-charter-aesd-dev-k8s-vault: RequestError: send request failed\ncaused by: Head https://com-charter-aesd-dev-k8s-vault.s3-us-west-2.amazonaws.com/: dial tcp: i/o timeout" cluster-name=vault-etcd-cluster pkg=cluster 
time="2017-05-16T16:49:06Z" level=warning msg="fail to handle event: ignore failed cluster (vault-etcd-cluster). Please delete its TPR" pkg=controller `

**Comment by hongchaodeng** [comment]
Can you provide your TPR? How you start operator? And how you create your AWS secret?

**Comment by ssubramanian123** [comment]
It is same steps https://github.com/coreos/etcd-operator/issues/1088, (I have fixed the filenames as suggested by you in other thread).

**Comment by hongchaodeng** [comment]
Sure. But things could change in subtle way anytime.
We need formal process to run and reproduce this error to figure out what goes exactly wrong.

**Comment by ssubramanian123** [comment]
Thanks @hongchaodeng  Here is the steps which I followed now.

--Namespace created

kubectl create -f deployments/secured-external-ca/namespace.yaml 

--AWS credentials setup

kubectl create secret generic aws --from-file=deployments/secured-external-ca/awsdev/credentials --namespace=vault
kubectl create configmap aws --from-file=deployments/secured-external-ca/awsdev/config --namespace=vault

-- create Operator 
kubectl create -f deployments/secured-external-ca/etcd/etcd-operator.yaml 

-- get TPR
kubectl get thirdpartyresource cluster.etcd.coreos.com --namespace=vault

--Create Cluster
kubectl create -f deployments/secured-external-ca/etcd/etcd-cluster.yaml

/code time="2017-05-16T16:49:06Z" level=error msg="cluster failed to setup: unable to access bucket com-charter-aesd-dev-k8s-vault: RequestError: send request failed\ncaused by: Head https://com-charter-aesd-dev-k8s-vault.s3-us-west-2.amazonaws.com/: dial tcp: i/o timeout" cluster-name=vault-etcd-cluster pkg=cluster time="2017-05-16T16:49:06Z" level=warning msg="fail to handle event: ignore failed cluster (vault-etcd-cluster). Please delete its TPR" pkg=controller

**Comment by hongchaodeng** [comment]
Can you provide:
- deployments/secured-external-ca/etcd/etcd-operator.yaml
- deployments/secured-external-ca/etcd/etcd-cluster.yaml

**Comment by hongchaodeng** [comment]
BTW, did you retry that?
```
 dial tcp: i/o timeout
```
This could be temporary network error.

**Comment by ssubramanian123** [comment]
@hongchaodeng I tried 2 / 3 times by deleting TPR / cluster and re-creating it, no luck.

Here is the file

etcd-operator.yaml

`apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd-operator
  namespace: vault
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: etcd-operator
    spec:
      containers:
      - name: etcd-operator
        image: quay.io/coreos/etcd-operator:v0.2.6
        command:
        - /usr/local/bin/etcd-operator
        - --backup-aws-secret=aws
        - --backup-aws-config=aws
        - --backup-s3-bucket=com-charter-aesd-dev-k8svault
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name`


etcd-cluster.yaml

`apiVersion: "etcd.coreos.com/v1beta1"
kind: "Cluster"
metadata:
  name: "vault-etcd-cluster"
  namespace: vault
spec:
  size: 3
  version: "3.1.4"
  backup:
    backupIntervalInSecond: 30
    maxBackups: 5
    storageType: "S3"`

**Comment by hongchaodeng** [comment]
I couldn't reproduce this.
From the error, it looks a networking issue talking to S3:
```
Head https://com-charter-aesd-dev-k8s-vault.s3-us-west-2.amazonaws.com/: dial tcp: i/o timeout
```

Could you try to create a pod directly, mount secrets/configs, and see if it could talk to S3.

**Comment by ssubramanian123** [comment]
Thanks @hongchaodeng let me try it and update here.

**Comment by ssubramanian123** [comment]
Thanks @hongchaodeng, looks some issue with cluster dns or some issue.. we completely deleted cluster and ran it again. Everything worked as expected. 

Thank you very much again for your help.
