### ISSUE TITLE
backup to GCS

### ISSUE THREAD

**Issue by rimusz** [coreos/etcd-operator#1109]
support backup to GCS bucket

**Comment by xiang90** [comment]
@rimusz It would be great if you can contribute to this.

**Comment by rimusz** [comment]
I wish I was the go developer, then I could :)

**Comment by crimsonfaith91** [comment]
@rimusz @xiang90  Has anyone worked on this? I can work on this (I work at Google).

**Comment by bradjones1** [comment]
@crimsonfaith91 I think silence gives consent... if it helps you justify this to your bosses for development time, I am leading a rather large conversion to GCP/GKE and would see this as a real value-add.

**Comment by crimsonfaith91** [comment]
@bradjones1 Yes, introducing GCS to the operator can be considered part of my work. I will start working on this then. Thanks for timely update!

**Comment by crimsonfaith91** [comment]
@cpick Wonderful! I will monitor the PR. Thanks for the work!

**Comment by hexfusion** [comment]
Fixed via b3b2f83f47961e29d47412ea84ecea308c549a52
