### ISSUE TITLE
Use Taint Based Evictions

### ISSUE THREAD

**Issue by chancez** [coreos/etcd-operator#1117]
TaintBasedEvictions is an alpha feature in 1.6 which let's you specify tolerations that effect when a pod is evicted as a result of certain node conditions. This can be used to prevent the pod from being evicted for a certain amount of time (via `tolerationSeconds`), or indefinitely when a node becomes NotReady, or unknown, etc.

Docs:

https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#per-pod-configurable-eviction-behavior-when-there-are-node-problems-alpha-feature

Notes: The etcd-operator could probably allow users to enable this today, so long as they can set tolerations, and not have to worry if the feature flag is even enabled, since it would just have no effect when the alpha feature is not enabled.

**Comment by philips** [comment]
Yes! We should do this; glad this feature exists.

Then we need some way to reconcile actual node death with cloud providers, which we should probably do anyways. Create a NodeDeletionController or something.

**Comment by chancez** [comment]
I'm pretty certain that an actual node death (ie: termination) is already reconciled correctly in Kubernetes. If you mean something else, like "down and not coming back, but not terminated", then I think that would ideally be handled by an ASG health check where the node is unhealthy and terminated by the ASG after the configured grace period.

As that relates to the TaintBasedEviction tolerations, if the node object is deleted (as a result of the instainced being terminated), then then the pod will be GCed/deleted in the API rather than evicted, and then re-created to be scheduled.

Of course, this all assumes the cloud, baremetal likely would need some kinda node deletion handling still.

**Comment by diegs** [comment]
I would assume baremetal folks would want to know that one of their nodes is non-functional and go fix it.

**Comment by hongchaodeng** [comment]
ref: https://kubernetes.io/docs/concepts/architecture/nodes/

> If the Status of the Ready condition is “Unknown” or “False” for longer than the pod-eviction-timeout, an argument passed to the kube-controller-manager, all of the Pods on the node are scheduled for deletion by the Node Controller. The default eviction timeout duration is five minutes. In some cases when the node is unreachable, the apiserver is unable to communicate with the kubelet on it. The decision to delete the pods cannot be communicated to the kubelet until it re-establishes communication with the apiserver. In the meantime, the pods which are scheduled for deletion may continue to run on the partitioned node.

We have hit this issue again (https://github.com/coreos-inc/tectonic-issues/issues/268). We need to figure out ways to prevent etcd pods from being evicted.

**Comment by hongchaodeng** [comment]
I am trying this to see if it can endure partition. Will update here.

**Comment by hongchaodeng** [comment]
I have tested it with https://github.com/coreos/etcd-operator/pull/1224 and it fixed the problem. The pod will keep "Running" state instead of being deleted and become "Terminating".

**Comment by hongchaodeng** [comment]
Closing this to converge in https://github.com/coreos/etcd-operator/issues/1856
