### ISSUE TITLE
etcd2 backup/restore support in operator

### ISSUE THREAD

**Issue by raoofm** [coreos/etcd-operator#1123]
@xiang90 @philips @heyitsanthony 
etcd-operator is awesome and we are really excited to use this in production.

Our usecase is [**_Here_**](https://github.com/coreos/etcd/blob/master/Documentation/production-users.md#vonage) and we are using etcd as vault backend on kubernetes. So now comes the real requirement of highly available with auto pilot (operator)

Not having v2 is stopping us from using it. We were early adopters of etcdv2 and have clients using it and they cant/didnt migrate to v3 yet. One of the limitations being no java client library available and moving away from rest to grpc made it not so easy for clients to start using v3. The cluster is already running 3.1

No doubt that v3 is awesome but can't force clients to move to v3. Is it a lot of work to have v2 back/restore as part of operator too.

I see that this was reported earlier #864  and I'm pretty sure that there must be many who want to use operator and not having v2 backup/restore might be a limitation. This supports only new users who are starting to use v3.

The only option I see is to have a side car container running which should reinitialize v2 data from a backup that it had taken before. (not an ideal way of doing it though)

**Comment by hongchaodeng** [comment]
I remembered the plan is to use v2 API proxy on top of etcd3. Is there any tracking issue? @xiang90 @heyitsanthony

**Comment by sergik** [comment]
Any updates on this?

**Comment by xiang90** [comment]
i do not think etcd operator will ever deal with a v2 data snapshot. 

one option is the make etcd itself to support v2 api with v3 data.

**Comment by raoofm** [comment]
> I remembered the plan is to use v2 API proxy on top of etcd3. Is there any tracking issue? @xiang90 @heyitsanthony 

> one option is the make etcd itself to support v2 api with v3 data.

@xiang90 @heyitsanthony Is there an issue that is being tracked in etcd?

**Comment by hongchaodeng** [comment]
@raoofm https://github.com/coreos/etcd/issues/6925

**Comment by raoofm** [comment]
@hongchaodeng Thanks, awesome!
