### ISSUE TITLE
Create operator kit/sdk for common operations?

### ISSUE THREAD

**Issue by jamiehannaford** [coreos/etcd-operator#1125]
I'm wondering whether there is enough overlap in different operators to warrant some kind of common library that will make the lives of those who want to write an operator easier. Have you folks thought about doing this?

Specifically I was thinking about some common areas:

- configuration and validation (flags, files, etc.)
- client setup
- leadership election
- garbage collection
- TPR registration
- TPR monitoring
- common Spec interfaces/functions 

Is this possible and/or wanted; or are folks of the opinion that operators wildly differ in their implementation?

**Comment by hongchaodeng** [comment]
@jamiehannaford 

Why do you want to such common library? What is the motivation? Are you writing more operators? Maybe we can create a framework for operator.

**Comment by jamiehannaford** [comment]
@hongchaodeng Yeah, I'm writing an [operator](https://github.com/jamiehannaford/canary-operator) to help with long-term canary deployments. I'm finding that a lot of the logic that goes into an operator is relatively common and can possibly be abstracted into a framework. ATM I'm basing heavily on the etcd-operator because config, client setup, API calls, TPR creation, synchronisation and the reconciliation loop structure are basically the same. What do you think?

I expect a lot more operators will be written in the future, so encouraging people to reuse code and common patterns is preferable than asking them to reinvent the wheel or duplicate.

**Comment by hongchaodeng** [comment]
@jamiehannaford 
We have the same thought and would like to work on that. Please take a look at https://github.com/kubernetes-incubator/apiserver-builder . That's a long term plan.

**Comment by jamiehannaford** [comment]
@hongchaodeng Isn't that for building API servers?

**Comment by hongchaodeng** [comment]
@jamiehannaford 
Yes.
See https://groups.google.com/forum/#!msg/kubernetes-sig-apps/0gbmMNvZWUo/fgYSHNoWCQAJ .

**Comment by jamiehannaford** [comment]
@hongchaodeng Hmm, an interesting read! In that doc Brendan B. says that custom APIs and TPRs are at the opposite ends of a spectrum and that one will not necessarily replace the other. @xiang90 also mentioned that the etcd-operator will keep using the TPRs even after custom APIs become more supported. So if that's the case, wouldn't an operator framework have different concerns from https://github.com/kubernetes-incubator/apiserver-builder?

**Comment by xiang90** [comment]
@jamiehannaford Operator kit is a good idea. I know a few people also want it. We would like to help and develop it.

But before start to create one, would you mind creating a google doc to gather requirements? I will ask other people to take a look too.

**Comment by jamiehannaford** [comment]
@xiang90 Yep, will do when I have some time this week.

**Comment by jamiehannaford** [comment]
@xiang90 @hongchaodeng I've created a very rough first draft [here](https://docs.google.com/document/d/1NJhFcNezJyLM952eaYVcdfIQFQYWsAx4oTaA82-Frdk). I've opened the permissions so folks can edit it too, so feel free to add/modify/delete content as necessary. Would love to hear your feedback!

**Comment by jamiehannaford** [comment]
I'm going to propose this project for incubator status. [Here](https://docs.google.com/document/d/1ChcMp6pnEK13sSwfThKb5UPBYdrJ-3z4qIsnMMoNEKs) is the proposal if folks would like to review and add comments beforehand. 

@xiang90 Every incubator needs a "champion", somebody who is in a Kubernetes OWNER file. Are you willing to be the champion for OperatorKit? I saw you're an apimachinery and apiserver owner.

**Comment by jamiehannaford** [comment]
Closing as we now have a requirements doc and community interest. Next steps will be proposing it as an incubator project.
