### ISSUE TITLE
Allow people to override etcd registry URL

### ISSUE THREAD

**Issue by jamiehannaford** [coreos/etcd-operator#1156]
When adding etcd-operator to kubeadm, some folks [mentioned](https://github.com/kubernetes/kubernetes/pull/45665#discussion_r116325896) that users might want to override the registry URL with their own. Currently it's hardcoded [here](https://github.com/coreos/etcd-operator/blob/9bfc87aa1473da7931b3d1f285829472ab2099fc/pkg/util/k8sutil/k8sutil.go#L113).

Is this possible?

**Comment by hongchaodeng** [comment]
There is an ongoing PR: https://github.com/coreos/etcd-operator/pull/1056
But the author seems inactive.
Feel free to take it over

**Comment by jamiehannaford** [comment]
@hongchaodeng Okay, I'll take a look if I have time next week :)
