### ISSUE TITLE
etcd backup size limit

### ISSUE THREAD

**Issue by sergik** [coreos/etcd-operator#1161]
We are using etcd operator with backups. And looks like backup size growth linear. From 50k to 20mb in 2 hours. Looks like it is normal behaviour https://coreos.com/etcd/docs/latest/tuning.html and by default etcd truncates log after 10к revision. But in my case looks like it was not happen. Is there way control this settings from etcd-operator side?

**Comment by xiang90** [comment]
this is not something etcd operator would enforce. this is an application related tuning knob. you can use env to configure etcd pod.
