### ISSUE TITLE
spec/backup: rename cleanupBackupsOnClusterDelete to autoDelete

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#1164]
In backup policy, the field cleanupBackupsOnClusterDelete is too long and verbose.
Now I have a better name -- `autoDelete`.

**Comment by hongchaodeng** [comment]
Here's the plan:
- We will add AutoDelete field first. If either `AutoDelete` or `CleanupBackupsOnClusterDelete` is set to `true`, we will have `AutoDelete=true`.
- We will drop `CleanupBackupsOnClusterDelete` in 0.4.0 release

**Comment by xiang90** [comment]
@hongchaodeng can we still keep the json tag? so we do not need to go through the internal depreciation path. we only need to drop the json tag when we decide to drop the external field.

**Comment by hongchaodeng** [comment]
The value of this change is about the json tag.
Currently it is too long for reading and writing.

**Comment by hongchaodeng** [comment]
another idea: rename `backupIntervalInSecond` to `intervalInSec`.
```
backup:
  intervalInSec: 1800
```

**Comment by hongchaodeng** [comment]
fixed in #1228
