### ISSUE TITLE
Typo in README regarding getting service endpoint URL

### ISSUE THREAD

**Issue by honghzzhang** [coreos/etcd-operator#1188]
In "Create and destroy an etcd cluster" section: 

The following command: 
export ETCDCTL_ENDPOINTS=$(minikube service example-etcd-cluster-client --url)

should be 
export ETCDCTL_ENDPOINTS=$(minikube service example-etcd-cluster-client-service --url)

to get the URL of the service. The current command returns null.

**Comment by xiang90** [comment]
@honghzzhang can you send a pr to get this fixed?

**Comment by honghzzhang** [comment]
Submitted pull request: https://github.com/coreos/etcd-operator/pull/1194
