### ISSUE TITLE
support TLS enabled cluster

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd-operator#12]

**Comment by hongchaodeng** [comment]
ref static TLS issue: https://github.com/coreos/etcd-operator/issues/409

**Comment by hongchaodeng** [comment]
I'm closing this in favor of https://github.com/coreos/etcd-operator/issues/409
All TLS issue update would be tracked there. We are prioritizing the work and trying to get it out in next release, soon.

For dynamic TLS (operator generates CSR), please open another issue later.
