### ISSUE TITLE
do not print out aws client error directly

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd-operator#1200]
now we might print out errors like

> failed to update backup policy: resource name may not be empty"

This error message is useless since it has no context. I do not know what is the resource name and what is empty. At least, it should have aws s3 prefix. It should be something like 

failed to update backup policy: failed to create s3 client (resource name may not be empty)

**Comment by hongchaodeng** [comment]
> ailed to update backup policy: failed to create s3 client (resource name may not be empty)

Adding stack trace to error should be the right way to go.
Maybe we should consider switching to https://github.com/pkg/errors

**Comment by hongchaodeng** [comment]
After digging through the code base, I think there are two things that we need to improve on error handling:
- First, we need to wrap all errors. What this issue basically about is that we don't really provide **context** for where the error happened, what we expect, etc.
- Second, we have a method called `isFatalError()` which detects sentinel/const error. This limits our ability to wrap the error with more context info. We need to think of something to improve that.
