### ISSUE TITLE
The 'Cluster' kind is too generic

### ISSUE THREAD

**Issue by TimJones** [coreos/etcd-operator#1209]
When a ThirdPartyResource is registered, it's `Kind` has to be unique cluster-wide. The ETCD Operator uses the kind `Cluster` to manage ETCD Clusters. I think this is too generic and clashes with many other types of cluster (Redis Clusters, Kafka Clusters, maybe even one day a Kubernetes Cluster etc). In fact, rook.io already also uses `kind: Cluster` in their operator.

Before a release to 1.0 I strongly believe that the `Kind` should be renamed something more specific like `EtcdCluster` to avoid such name clashes and confusion.

**Comment by hongchaodeng** [comment]
Duplicate to https://github.com/coreos/etcd-operator/issues/860.
Let's move the discussion there.
