### ISSUE TITLE
Cluster restore from backup fails for 3.2.1

### ISSUE THREAD

**Issue by aaronyoungkash** [coreos/etcd-operator#1222]
When operator attempts to pull the backup image from sidecar it fails with a 400 to the backup endpoint:

`time="2017-06-27T15:50:50Z" level=error msg="check backup existence (etcd-cluster-backup-sidecar:19999) failed: unexpected status code (400 Bad Request), response ()" cluster-name=etcd-cluster pkg=cluster`

After some investigation it seems to be because the the endpoint `http://etcd-cluster-backup-sidecar:19999/v1/backup?etcdVersion=3.2.1` is unaware of the existence of version 3.2:

```
< HTTP/1.1 400 Bad Request
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Tue, 27 Jun 2017 16:19:14 GMT
< Content-Length: 64
<
requested version (3.2) is not compatible with the backup (3.2)
```

Which is because this map hasn't been updated:
```
var compatibilityMap = map[string]map[string]struct{}{
	"3.0": {"2.3": struct{}{}, "3.0": struct{}{}},
	"3.1": {"3.0": struct{}{}, "3.1": struct{}{}},
}
```

**Comment by theothermike** [comment]
Should also probably include this:  https://github.com/coreos/etcd-operator/issues/1185

which would have caught this particular bug

**Comment by hongchaodeng** [comment]
We haven't supported 3.2 yet. So there are two action items for this:
- have docs for compatibility matrix against etcd
- support etcd 3.2

**Comment by hongchaodeng** [comment]
This is fixed.
