### ISSUE TITLE
Compatibility Test against k8s 1.7

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#1233]
Failing test blocker:
- [x] wait backup deployment deleted timeout (fixed in https://github.com/coreos/etcd-operator/pull/1248)
- [x] many tests failing to create 3 member clusters (fine after we reduce two clusters to one, seems GCE network problem)
- [x] restore same name test failing due to previous deployment exist (https://github.com/coreos/etcd-operator/pull/1251)

**Comment by hongchaodeng** [comment]
Latest try with k8s v1.7.0-rc.1 resulted in failure to set up operator:
```
time="2017-06-29T17:43:58Z" level=error msg="fail to setup etcd operator: unexpected pod status.phase: Failed" 
time="2017-06-29T17:43:58Z" level=error msg="fail to setup framework: unexpected pod status.phase: Failed" 
```

**Comment by hongchaodeng** [comment]
Now we have the test running as normal.

We two builds:
- https://jenkins-etcd.prod.coreos.systems/view/operator/job/etcd-operator-master-k8s-master/122
- https://jenkins-etcd.prod.coreos.systems/view/operator/job/etcd-operator-master-k8s-master/123

It seems there is some flakes in 1.7 .

**Comment by hongchaodeng** [comment]
Update for this week.

Now I have the following setup:
- 1 master node: "n1-standard-2"
- 4 worker nodes: "n1-standard-2"

I run `e2e_pass` in sequential and have the following failures:
- `TestOperWideS3AllDown`
- `TestOperWideS3RestoreSameName`

Both failed for the `wait backup deployment deleted timeout` case. Gonna dig deeper into that case right now.

**Comment by hongchaodeng** [comment]
Last time we tracked the failure of `TestOperWideS3AllDown` in real time. It looks like backup sidecar deployment still exists for a while before eventually deleted from API.

**Comment by hongchaodeng** [comment]
I tried to use `DeletionTimestamp` to detect deletion of Deployment and pod.
This will fix the flakes caused in https://github.com/coreos/etcd-operator/issues/1233#issuecomment-313215741

**Comment by hongchaodeng** [comment]
Currently we are seeing one failure pretty frequently:
```
TestOperWideS3RestoreSameName
...
restore_test.go:156: fail to wait backup deleted: failed to wait storage (S3) to be deleted: still failing after 5 retries
```

**Comment by hongchaodeng** [comment]
e2e is green now.
We have upgrade test failing due to the deployment check deletion change. This is something we are fixing right now.

**Comment by xiang90** [comment]
closing
