### ISSUE TITLE
migrate to CRD

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd-operator#1236]

**Comment by hongchaodeng** [comment]
So in order to migrate to CRD, here are the steps that we need to do:
1. create CRD
2. copy cluster TPR to cluster CR
3. shutdown operator
4. update relevant resources' ownerRefs
5. delete cluster TPR, delete TPR
6. restart operator

**Comment by hongchaodeng** [comment]
We will prioritize this item since TPR will be removed in k8s 1.8 . We need to ship this as early as we could and have it tested as much as possible.

**Comment by hongchaodeng** [comment]
Has 30 passes right now: https://jenkins-etcd-public.prod.coreos.systems/view/operator/job/etcd-operator-flake/

Testing is stable for "crd" branch.
