### ISSUE TITLE
Decoupling boot member removal

### ISSUE THREAD

**Issue by jamiehannaford** [coreos/etcd-operator#1246]
I've been speaking with @luxas about how we can incorporate the etcd-operator into kubeadm, and one thing we've run into is how the etcd-operator handles removing the boot etcd member after the new etcd cluster is created. Right now it waits for a fixed time before beginning removal (60 seconds), but this is suboptimal for a few reasons:

- If there's 5TB of data and a slow network it will take longer than 60s, but the operator will just cut things in the middle

- Tightly coupling the creation of the new resource and deletion of old introduces some unnecessary constraints. Specifically, if we take the intended workflow of kubeadm:

1. Static pods (boot etcd, apiserver, controller-manager and scheduler) starts
2. etcd-operator deployment is created
3. TPR data is sent to operator specifying the boot etcd IP
4. operator creates self-hosted etcd cluster
5. operator adds new members to existing cluster and migrates data to new members
6. self-hosted control panel is deployed (apiserver uses service IP of self-hosted etcd)
7. static pods (apiserver, controller-manager and scheduler) are deleted directly after the self-hosted version is up
8. operator removes boot etcd from etcd cluster
9. boot etcd pod is deleted

But right now steps 5 and 8 are coupled together with a 60s buffer. Would it be possible to add an option to the self-hosted TPR spec which allows a user to disable the auto deletion of the boot member? If the bool is true, they are expected to handle the removal themselves.

**Comment by hongchaodeng** [comment]
the problem is that kubelet has a bug that even if static pod is deleted, kubelet doesnt take down the pod. We have seen this several times and going to report to upstream sometime

**Comment by hongchaodeng** [comment]
Sorry, I probably didn't understand your point well. Isn't the workflow above the same as what we currently have? Can you point out what is the difference and what you want to achieve more detailedly?

**Comment by xiang90** [comment]
> But right now steps 5 and 8 are coupled together with a 60s buffer. Would it be possible to add an option to the self-hosted TPR spec which allows a user to disable the auto deletion of the boot member? If the bool is true, they are expected to handle the removal themselves.

We can do that. Can you submit a PR to make it happen?

**Comment by jamiehannaford** [comment]
Sure, I'll try to get around to it this week

**Comment by xiang90** [comment]
@jamiehannaford We add that thing simply because bootkube team does not want to handle the deletion of boot member in bootkube. And, yes, I think the bootstrapper is a better place to remove the boot member instead of the etcd operator actually. Just make sure we are talking about the same thing.
