### ISSUE TITLE
Clarify: anti-affinity behavior between etcd pods and backup sidecar

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#1253]
ref: https://github.com/coreos/etcd-operator/pull/1128

Previously we haven't defined nor thought good enough about this behavior. Let's define it:

|                                                  |  sidecar with anti-affinity | sidecar without anti-affinity |
|------------------------------|--------------------------|-----------------------------|
| etcd pod with anti-affinity      | cannot colocate               | can colocate                           |
| etcd pod without anti-affinity | can colocate                    | can colocate                           |

Then let's better put some schedule to implement it.

**Comment by luqasn** [comment]
What's the status on this? I need to colocate the backup sidecar with the etcd nodes.

**Comment by hongchaodeng** [comment]
We don't have backup sidecar anymore.
Closing this.
