### ISSUE TITLE
failed to create 3 members etcd cluster: still failing after 6 retries

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#1256]
In our e2e testing, we have seen occasional flakes caused by network connectivity problems. The end result is that operator failed to create etcd client with error msg `grpc time out when dialing` and cannot operate etcd cluster as expected.

**Comment by hongchaodeng** [comment]
I checked recent e2e flakes and they are caused by this issue. For example, e2e relies on operator to update status.members and some member's health check failed by `grpc: timed out when dialing`.

**Comment by xiang90** [comment]
i am not convinced that gce networking is THAT unreliable. we might want to spend sometime to dig into this.

**Comment by hongchaodeng** [comment]
How to dig? It failed to create an etcd client. In operator, there isn't much to dig.

**Comment by hongchaodeng** [comment]
Also this doesn't rule out other problems like kubelet starting container slow.

**Comment by hongchaodeng** [comment]
another possible cause: scheduling is slow

**Comment by hongchaodeng** [comment]
It also depends. I have stress one test that always failed at some point. Then it always succeed after that.

**Comment by hongchaodeng** [comment]
Some more evidence from a flake:

```
time="2017-07-11T19:23:51Z" level=info msg="added member (test-etcd-g9g1l-0002)" 
...
time="2017-07-11T19:23:56Z" level=warning msg="health check of etcd member
```

```
2017-07-11 19:23:57.143387 I | etcdmain: etcd Version: 3.1.8
...
E  2017-07-11 19:23:57.312249 N | embed: serving insecure client requests on [::]:2379
```

last check
```
util.go:102: 2017-07-11 19:24:04.114000071 +0000 UTC waiting size (3), healthy etcd members: names ([test-etcd-g9g1l-0000 test-etcd-g9g1l-0001])
```

```
time="2017-07-11T19:24:04Z" level=info msg="cluster is deleted by the user" cluster-name=test-etcd-g9g1l pkg=cluster
```

**Comment by hongchaodeng** [comment]
It looks like it took operator:
- `51 - 14 = 37s` to create 3 members, which is normal
- there is some delay + reconciile interval (8s) = `64-51=13s`

**Comment by hongchaodeng** [comment]
Honestly, this is problematic.. It waits only `37 + 13 = 50s`. We used divide method = `(60 * time.Second) / (10 * time.Second)`. This is rounded down unexpectedly.

**Comment by hongchaodeng** [comment]
The total test time is also less than 60s:
```
FAIL: TestDisasterRecoveryAll (55.51s)
```

**Comment by hongchaodeng** [comment]
It is not rounding down.. The root cause is that in `Retry()` code, we implement "retries" as exact tries, while we use it as "retries", i.e. additional tries.

**Comment by hongchaodeng** [comment]
ref:
https://github.com/coreos/etcd-operator/pull/1276
https://github.com/coreos/etcd-operator/pull/1275

**Comment by hongchaodeng** [comment]
fixed now

**Comment by blakebarnett** [comment]
Seeing this also in AWS on 0.4.2, will this be in 0.4.3 soon?  Can't seem to get a cluster running anymore.

**Comment by hongchaodeng** [comment]
@blakebarnett 
Can you create an new issue? Paste operator logs, etcd logs, etc.

**Comment by blakebarnett** [comment]
sure: https://github.com/coreos/etcd-operator/issues/1326
