### ISSUE TITLE
Set TolerateUnreadyEndpoints for service of peer URLs

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#1257]

**Comment by hongchaodeng** [comment]
Normal service endpoints looks like:
```yaml
subsets:
- addresses:
  - ip: 10.244.2.81
    nodeName: kubernetes-minion-group-hnk5
    targetRef:
      kind: Pod
      name: example-0000
      namespace: default
      resourceVersion: "347215"
      uid: 2157e923-62aa-11e7-8be1-42010af00002
  - ip: 10.244.5.64
    nodeName: kubernetes-minion-group-hlxq
    targetRef:
      kind: Pod
      name: example-0002
      namespace: default
      resourceVersion: "347303"
      uid: 2deb6871-62aa-11e7-8be1-42010af00002
  - ip: 10.244.6.194
    nodeName: kubernetes-minion-group-x0t0
    targetRef:
      kind: Pod
      name: example-0001
      namespace: default
      resourceVersion: "347255"
      uid: 26262588-62aa-11e7-8be1-42010af00002
```

Headless service endpoints looks like:

```yaml
subsets:
- addresses:
  - hostname: example-0000
    ip: 10.244.2.81
    nodeName: kubernetes-minion-group-hnk5
    targetRef:
      kind: Pod
      name: example-0000
      namespace: default
      resourceVersion: "347215"
      uid: 2157e923-62aa-11e7-8be1-42010af00002
  - hostname: example-0002
    ip: 10.244.5.64
    nodeName: kubernetes-minion-group-hlxq
    targetRef:
      kind: Pod
      name: example-0002
      namespace: default
      resourceVersion: "347303"
      uid: 2deb6871-62aa-11e7-8be1-42010af00002
  - hostname: example-0001
    ip: 10.244.6.194
    nodeName: kubernetes-minion-group-x0t0
    targetRef:
      kind: Pod
      name: example-0001
      namespace: default
      resourceVersion: "347255"
      uid: 26262588-62aa-11e7-8be1-42010af00002
```

**Comment by hongchaodeng** [comment]
ref: https://github.com/coreos/etcd-operator/issues/1267

Actually we don't need the service to access the FQDN

**Comment by hongchaodeng** [comment]
One more finding, with the headless service, we can ping FQDN without the cluster domain. For example, "foo.bar.default.svc" instead of "foo.bar.default.svc.cluster.local".

**Comment by xiang90** [comment]
> One more finding, with the headless service, we can ping FQDN without the cluster domain. For example, "foo.bar.default.svc" instead of "foo.bar.default.svc.cluster.local".

is this documented anywhere under k8s doc?

**Comment by hongchaodeng** [comment]
> is this documented anywhere under k8s doc?

The official docs about service talks about the shortname. But it doesn't mention about subdomain though.

**Comment by hongchaodeng** [comment]
Also verified that with network partition, the endpoint of unready (FQDN, subdomain, headless service) pod will be removed in the same way as normal service.

**Comment by xiang90** [comment]
> Also verified that with network partition, the endpoint of unready (FQDN, subdomain, headless service) pod will be removed in the same way as normal service.

even with the toleration enabled?

**Comment by hongchaodeng** [comment]
Finally, verified that using `service.alpha.kubernetes.io/tolerate-unready-endpoints` will keep the endpoint even under unreadiness.
