### ISSUE TITLE
make sure the service is up before adding the second self-hosted etcd member

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd-operator#1260]
When scaling the etcd cluster size from 1 to 2, adding a "unready" member can cause the k8s cluster to become unavailable due to quorum loss. And the cluster cannot be recovered automatically. 

So before adding the member, we need to make sure the network is fully set up.

A quick workaround can be increasing the sleep after the pod started and before running the member add command. But it is still unreliable.

**Comment by hongchaodeng** [comment]
So the question is how can we determine the first member gets the DNS entry. For example, if we check the DNS in the second member, it might still be unpopulated in the first member. And vice versa. And to etcd service as well.

**Comment by hongchaodeng** [comment]
fixed by https://github.com/coreos/etcd-operator/pull/1266
