### ISSUE TITLE
e2e flake umbrella

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#1265]
We have about 1/5 chance of flakes after migrating to k8s 1.7 .
This issue tracks all flakes and ongoing work.

**Comment by hongchaodeng** [comment]
test failure: https://jenkins-etcd-public.prod.coreos.systems/job/etcd-operator/2102/consoleText

```
--- FAIL: TestDisasterRecoveryMaj (106.71s)
	util.go:102: 2017-07-07 18:47:00.033941935 +0000 UTC created etcd cluster: test-etcd-r042x
	recovery_test.go:137: failed to create backup pod: still failing after 12 retries
```

```
--- FAIL: TestClusterRestoreDifferentName (377.61s)
	restore_test.go:156: failed to create 3 members etcd cluster: still failing after 30 retries
	restore_test.go:150: fail to wait backup deleted: failed to wait storage (PersistentVolume) to be deleted: still failing after 5 retries
```

**Comment by hongchaodeng** [comment]
Have a lot of fix commits and now have 2/30 failures in last stress testing.
Closing this.

**Comment by xiang90** [comment]
@hongchaodeng 2/30 is still very high failure rate. it is ~8%.

**Comment by hongchaodeng** [comment]
This is the umbrella issue. We will make issue for individual failure in finer granularity.
