### ISSUE TITLE
How to backup etcd cluster from 3.1.0-alpha.1_0000000000000001_etcd.backup

### ISSUE THREAD

**Issue by wwyiwzhang** [coreos/etcd-operator#1268]
Unfortunately, I did something that caused the etcd cluster go down and I could not recover the data yet. The cluster used persistent volume claim (PVC) to back up data daily and I found this '3.1.0-alpha.1_0000000000000001_etcd.backup' in the PVC. How can I recover the data from this backup file?

**Comment by raoofm** [comment]
@wwyiwzhang you mentioned cluster version, does it have v2 or v3 data or both

**Comment by wwyiwzhang** [comment]
Hi Raoof,

Thanks for getting back to me early in the morning. I really appreciate it.
Our team have lost all of the data in the etcd cluster unless there is a
way to restore it from the backup file. As far as I know, we have *V2* (API
version2) data.

Thanks,
Weiwei

**Comment by raoofm** [comment]
Sorry my previous post got deleted by mistake where i wrote

> @wwyiwzhang you mentioned cluster version, does it have v2 or v3 data or both

etcd-operator doesn't backup v2 data, so there is no way to restore. It only backs up v3 data. I mentioned this earlier #1123 as this is big problem for existing users. I hope you can request on that issue too and give a vote.

In case you have backed up v2 data manually then I can elaborate, but doesn't seem the case.

**Comment by wwyiwzhang** [comment]
Hi Raoof,

Thanks a lot for giving me this info. At least I know that I can stop
trying. :)

I think we will move to API version 3 in the future. In the meanwhile, we
will do manual data backup for API version 3.

I would greatly appreciate if there will be some documentation on how to
back up data for API version 3 since I googled it and I could not find it.
If you need to to create an issue for it in Github, please feel free to
ask. I'd be happy to do it.

Also, it will be very helpful if this image is tagged with version 0.1.0 so
it can prevent others from being the situation like we do.
https://github.com/coreos/etcd-operator/blob/v0.1.0/example/deployment.yaml

Btw, I want to thank the etcd team (including etcd-operator) for creating
this tool. It has been helping my team a lot!!! Awesome work guys~

Best,
Weiwei

**Comment by raoofm** [comment]
>  In the meanwhile, we
will do manual data backup for API version 3.
I would greatly appreciate if there will be some documentation on how to
back up data for API version 3 since I googled it and I could not find it.

@wwyiwzhang you meant to type version 2 here right?

**Comment by wwyiwzhang** [comment]
yep, version2.

**Comment by raoofm** [comment]
For v3 you can find examples here
https://github.com/coreos/etcd-operator/blob/3ec1a1d38e0fc91a2e757ed322227c6816e5f110/example/example-etcd-cluster-with-backup.yaml
https://github.com/coreos/etcd-operator/blob/3ec1a1d38e0fc91a2e757ed322227c6816e5f110/example/deployment-s3-backup.yaml.template

and doc here
https://github.com/coreos/etcd-operator/blob/master/doc/user/backup_service.md
https://github.com/coreos/etcd-operator/blob/master/doc/user/download_backup.md

For v2, it has to be done manually.

**Comment by wwyiwzhang** [comment]
Cool, thanks @raoofm. 

Can you also add the section in https://github.com/coreos/etcd-operator/blob/master/doc/user/download_backup.md on what to do after retrieving the .back files? for example, what command to run to restart a new etcd cluster with the .back files. I think the examples are not clear to me.

**Comment by raoofm** [comment]
The backups that etcd operator saves are etcd snapshots.

You can use this later to recover from a v3 snapshot
https://github.com/coreos/etcd/blob/master/Documentation/op-guide/recovery.md#restoring-a-cluster

This is how you will restore from a v2 backup
https://github.com/coreos/etcd/blob/master/Documentation/v2/admin_guide.md#backing-up-the-datastore
https://github.com/coreos/etcd/blob/master/Documentation/v2/admin_guide.md#restoring-a-backup

Now the real problem is I dont think you can restore a cluster from both v2 backup and v3 snapshot at the same time. I think you may have to recreate v2 keys manually. (etcd owners can confirm, @xiang90 )

**Comment by hongchaodeng** [comment]
Closing this.
Feel free to ping me if there is any more question
