### ISSUE TITLE
Add nodeName field to PodPolicy

### ISSUE THREAD

**Issue by jamiehannaford** [coreos/etcd-operator#1269]
kubeadm is current affected by https://github.com/kubernetes/kubernetes/issues/45717 which prevents any pod from being scheduled on a node without any CNI solution (kubeadm allows users to install SDN after init). The workaround is to use DaemonSets for the control panel, since it bypasses the scheduler.

In order to bypass the scheduler for normal pods, we need to set the `nodeName` for the pods in the etcd-clusters. When https://github.com/kubernetes/kubernetes/pull/42406 is fixed, kubeadm can remove this constraint, but I think it's an okay compromise for the time being.

**Comment by hongchaodeng** [comment]
I didn't catch the problem. So what are you trying to achieve?

**Comment by jamiehannaford** [comment]
kubeadm does not deploy flannel or weave, meaning that the node is marked as `NotReady`, so no pods can be scheduled to them. In order for `kube-etcd-0000` to be deployed by the operator, it needs a `nodeName` to exist in the PodSpec.

**Comment by jamiehannaford** [comment]
Proposed solution is to add a field to [the spec](https://github.com/coreos/etcd-operator/blob/master/pkg/spec/cluster.go#L131) and then ensure it exists in the PodSpec for the pod [here](https://github.com/coreos/etcd-operator/blob/aca372af9457a0c93648bcd6eee7066c10d7ab36/pkg/util/k8sutil/pod_util.go#L114). I can submit a PR tomorrow

**Comment by hongchaodeng** [comment]
> kubeadm does not deploy flannel or weave, meaning that the node is marked as NotReady

Why is the node marked "NotReady"?

**Comment by jamiehannaford** [comment]
It's a known bug: https://github.com/kubernetes/kubernetes/issues/45717. 

If a CNI network isn't set up, kubelet marks all nodes as `NotReady`. kubeadm doesn't deploy flannel during the init phase - it lets the user pick a network provider afterwards. This is a deliberate design choice to be vendor agnostic.

For v1.8 we're working on [adding more granular taints](https://github.com/kubernetes/kubernetes/pull/42406#issuecomment-313664091) that will solve this problem. But for now, setting `spec.nodeName` on the Pod will bypass the scheduler.

**Comment by luxas** [comment]
This would be super handy @hongchaodeng @xiang90 and is currently a blocker for adding support for self-hosted etcd in kubeadm. 
As @jamiehannaford said -- no Pod besides those created by a DaemonSet can be scheduled when there is no CNI network, due to that the scheduler filters out all `NotReady` nodes and the node goes `NotReady` when CNI is uninitialized.

**Comment by xiang90** [comment]
@jamiehannaford @luxas 

To be honest, I do not feel comfortable to bypass the scheduler for just the initial placement. We do have plan to let the operator to assign pods to nodes for good reasons, and what you describe is one of them. But I do not have time to write the full story at the moment.

Adding a random feature to the etcd operator to fix a short term blocker is really not the way to go forward.

**Comment by luxas** [comment]
@xiang90 Thanks, this is actually the answer I wanted to hear -- just wanted to test if you'd agree or not with that statement :)
I'm very fine with letting k8s fix the issue

**Comment by jamiehannaford** [comment]
That's fair enough. I'll close this and focus efforts on the upstream solution.
