### ISSUE TITLE
Deployment etcd node hangs ,but etcd-operator can not be automatically restored

### ISSUE THREAD

**Issue by wilhelmguo** [coreos/etcd-operator#1279]
If kubernetes node down , the pod.status.phase is still Running,
So etcd-operator  reconcile think the pods is running.Then, do nothing.

func (c *Cluster) reconcile(pods []*v1.Pod) error {
	c.logger.Infoln("Start reconciling")
	defer c.logger.Infoln("Finish reconciling")

	defer func() {
		c.status.Size = c.members.Size()
	}()

	sp := c.cluster.Spec
	running := podsToMemberSet(pods, c.isSecureClient())
	if !running.IsEqual(c.members) || c.members.Size() != sp.Size {
		return c.reconcileMembers(running)
	}
...
} 

And then updateMemberStatus checked unhealth member also do nothing.

func (c *Cluster) updateMemberStatus(pods []*v1.Pod) {
	var ready, unready []*v1.Pod
	for _, pod := range pods {
		m := &etcdutil.Member{Name: pod.Name, Namespace: pod.Namespace, SecureClient: c.isSecureClient()}
		url := m.ClientAddr()
		healthy, err := etcdutil.CheckHealth(url, c.tlsConfig)
		if err != nil {
			c.logger.Warningf("health check of etcd member (%s) failed: %v", url, err)
		}
		...
}

So, if one node of kubernetes down ,the etcd member will nerver be restart.

You can recurrence  by shutdown one node machine.

**Comment by xiang90** [comment]
That is how kubernetes works in general. Same thing will happen with replicaset, stateful set, etc.. We might add application level healthy checking, but it is a longer term goal. You need to config k8s controller manager correctly to evict pods from unready nodes correctly to solve your specific issue.

**Comment by wilhelmguo** [comment]
Deployment will create new pod if there is pod unready.
[root@docker3006 ~]# kubectl get pods
NAME                                     READY     STATUS    RESTARTS   AGE
etcd-etcd-operator-319525704-hbmbf       1/1       Unknown   1          9d
etcd-etcd-operator-319525704-z5hhj       1/1       Running   0          1h

and my deployment replicas is 1.

I suggest if health check reach max retry times（for example 3 times every 30second），then remove this member and start a new member.

**Comment by xiang90** [comment]
> If kubernetes node down , the pod.status.phase is still Running,

if this happens to deployment, deployment controller will also do nothing about it.

> Deployment will create new pod if there is pod unready.

This is VERY different from pod.status.phase is still running. You need an apple to apple comparison.

**Comment by wilhelmguo** [comment]
This unknown pod phase also Running.
[root@docker3006 ~]# kubectl get  pod etcd-etcd-operator-319525704-hbmbf  -o yaml|grep phase
  phase: Running

**Comment by xiang90** [comment]
Sorry, I do not understand what is unknown pod but also running. Pod phase can only be one of https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase

**Comment by wilhelmguo** [comment]
You can stop one node kubelet .
Then kubectl get pod will be become unready.But pod status.phase is still Running.
kubectl get pod status unready is probe health error, then return unready.

You can see kubernetes source code.

k8s.io/kubernetes/pkg/registry/core/componentstatus/validator.go

func (server *Server) DoServerCheck() (probe.Result, string, error) {
	// setup the prober
	server.Once.Do(func() {
		if server.Prober != nil {
			return
		}
		server.Prober = httpprober.NewWithTLSConfig(server.TLSConfig)
	})

	scheme := "http"
	if server.EnableHTTPS {
		scheme = "https"
	}
	url := utilnet.FormatURL(scheme, server.Addr, server.Port, server.Path)

	result, data, err := server.Prober.Probe(url, nil, probeTimeOut)

	if err != nil {
		return probe.Unknown, "", err
	}
...
}

**Comment by wilhelmguo** [comment]
When one kubernetes' node down ,pods on the node status.phase  still Running ,
But status.conditions Ready will be false. I think should combine ready conditions and status.phase
to decision is pod Running.

**Comment by xiang90** [comment]
readiness and pod phase are two different things. i am not sure how we are going to handle pod unknown probe result. create new issue to track that if you wish.

**Comment by wilhelmguo** [comment]
Now kubernetes evict pods from unready nodes only set  deletionTimestamp,deletionGracePeriodSeconds.
Will not delete the pods resource for node recovery delete this pod's container,volums etc ...
Once deletionTimestamp  before now should we think the pods is dead. Because even if the node recovery the pod will be deleted by kubelet. 

"kind": "Pod",
"apiVersion": "v1",
"metadata": {
"deletionTimestamp": "2017-07-13T09:44:26Z",
"deletionGracePeriodSeconds": 30,
