### ISSUE TITLE
prototype with bootkube

### ISSUE THREAD

**Issue by philips** [coreos/etcd-operator#128]
I think we need to get the integration with bootkube prototyped ASAP. The last remaining difficult thing for a fully self-hosted Kubernetes cluster is etcd. The Kubelet, API server, etc all have a path forward and we can prove that it works.

xref https://github.com/kubernetes-incubator/bootkube/issues/31#issuecomment-248815638

**Comment by xiang90** [comment]
Closing based on https://github.com/kubernetes-incubator/bootkube/pull/184
