### ISSUE TITLE
etcd-operator can not be automatically restored etcd cluster  once node down 

### ISSUE THREAD

**Issue by wilhelmguo** [coreos/etcd-operator#1281]
Now kubernetes evict pods from unready nodes only set deletionTimestamp,deletionGracePeriodSeconds.
Will not delete the pods resource for node recovery delete this pod's container,volums etc ...
Once deletionTimestamp before now should we think the pods is dead. Because even if the node recovery the pod will be deleted by kubelet.

"kind": "Pod",
"apiVersion": "v1",
"metadata": {
"deletionTimestamp": "2017-07-13T09:44:26Z",
"deletionGracePeriodSeconds": 30,

refer to [https://github.com/coreos/etcd-operator/issues/1279](url)

**Comment by wilhelmguo** [comment]
Node lost but phase still Running. So if a machine down, the phase of the pod is still Running.The operator will never start a new member .

"phase": "Running",
"message": "Node docker3004 which was running pod etcd-cluster-0045 is unresponsive",
"reason": "NodeLost",

**Comment by hongchaodeng** [comment]
Closing this issue due to unclearness.
If you still have this issue, feel free to reopen but provide clear description and details around the issue.
