### ISSUE TITLE
Race condition when using a service after cluster creation

### ISSUE THREAD

**Issue by jsilberm** [coreos/etcd-operator#1290]
Running the file below --- it fails on a new cluster:

root@master:~# kc create -f etcd_all.yml
clusterrole "etcd-operator" created
serviceaccount "etcd-operator" created
clusterrolebinding "etcd-operator" created
deployment "etcd-operator" created
service "etcd-px-client" created
error: unable to recognize "etcd_all.yml": no matches for etcd.coreos.com/, Kind=Cluster

Then I delete everything and try again, and everything works fine.    It's as if the service is trying to create before the cluster has been created (fully formed).
root@master:~# kc delete -f etcd_all.yml
clusterrole "etcd-operator" deleted
serviceaccount "etcd-operator" deleted
clusterrolebinding "etcd-operator" deleted
deployment "etcd-operator" deleted
service "etcd-px-client" deleted
Error from server (NotFound): error when deleting "etcd_all.yml": thirdpartyresourcedatas.extensions "etcd-cluster" not found
root@master:~# kc create -f etcd_all.yml
clusterrole "etcd-operator" created
serviceaccount "etcd-operator" created
clusterrolebinding "etcd-operator" created
deployment "etcd-operator" created
cluster "etcd-cluster" created
service "etcd-px-client" created

root@master:~# kc version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T22:55:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

[etcd_all.yml.txt](https://github.com/coreos/etcd-operator/files/1146947/etcd_all.yml.txt)

**Comment by jsilberm** [comment]
After a bit more head-banging, it looks like there are actually 2 distinct race conditions.    Both are evident in the referenced file.

Once you can run [this script](https://github.com/portworx/px-docs/blob/gh-pages/k8s-samples/px-startall.sh) without the 'waitfor' and race checks around etcd-operator and etcd-cluster, then this issue should be closed.

**Comment by hongchaodeng** [comment]
TPR is one time installment. Once it is set up, operator doesn't need to install it second time.
For the first time, you need to wait.
Just do:
```
if ! kubectl get thirdpartyresources cluster.etcd.coreos.com ; then
  sleep 60
fi
```

**Comment by hongchaodeng** [comment]
I think this is a docs issue.

**Comment by jsilberm** [comment]
I don't think it's just a docs issue, no.

Look at the script.  I already do a waitfor TPR --- and the cluster creation still fails (unless I retry).

All of this goes against Kubernetes accepted practices, if I'm not mistaken.   "Sleep/waitfor" is never an acceptable way of managing dependencies, right?

**Comment by hongchaodeng** [comment]
> and the cluster creation still fails (unless I retry).

That sounds like an issue for TPR.

**Comment by hongchaodeng** [comment]
@jsilberm 

You might want to report an issue to upstream about this. But since k8s is deprecating TPR and going to use CRD instead, can you try if CRD still have the same issue? If it has, please report it to upstream.

**Comment by hongchaodeng** [comment]
For current workaround, you need to check the actual TPR endpoint, e.g. `cluster.etcd.coreos.com`

**Comment by hongchaodeng** [comment]
Closing this since we migrated to CRD from TPR already.
Please create a new issue if you still have this problem with CRD
