### ISSUE TITLE
check pod condition besides pod status

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd-operator#1291]
for non-self hosted case, it is ok to take more aggressive member replacement policy. So if a pod is in a unknown healthy state, we can assume it is dead and replace it as soon as possible.

for self hosted case, this is probably too destructive. for self hosted case, we should keep pod as stable as possible. Only moving pods when we know they are dead, and there are enough nodes to schedule pods.

**Comment by hongchaodeng** [comment]
This is also what https://github.com/coreos/etcd-operator/issues/1320 is about.
Closing this to converge.
