### ISSUE TITLE
I install the operator in v1.6.4 k8s, but it run operator images is failed?

### ISSUE THREAD

**Issue by yan234280533** [coreos/etcd-operator#1295]
I install the operator in v1.6.4 k8s, but it run operater images is failed.

The error log is :

FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  26s		26s		1	default-scheduler				Normal		Scheduled		Successfully assigned etcd-operator-417324745-6wmzn to vm-129-125-ubuntu
  26s		26s		1	kubelet, vm-129-125-ubuntu			Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "etcd-operator-token-5n8ws" 
  26s		0s		26	kubelet, vm-129-125-ubuntu			Warning		FailedSync		Error syncing pod
  25s		0s		25	kubelet, vm-129-125-ubuntu			Normal		SandboxChanged		Pod sandbox changed, it will be killed and re-created

**Comment by hongchaodeng** [comment]
Issue is confusing.. I'm closing it.
Please create new issue with more details
