### ISSUE TITLE
Deletes cluster when upgrade fails

### ISSUE THREAD

**Issue by cehoffman** [coreos/etcd-operator#1301]
There is an issue I opened in etcd https://github.com/coreos/etcd/issues/8268 that highlighted what I think is a bug in expected behavior for the operator. When upgrading a cluster in this case, the operator deletes the entire cluster instead of reverting the cluster to the old etcd image.

It would seem preferable to me that the cluster enters a degraded state or reverts fully to the previous version instead of straight deletion. The reason for deletion in the logs is that no backup configuration exists in the spec.

**Comment by hongchaodeng** [comment]
So you mean when upgrade halted in the middle, revert to previous version?

To extend this topic, currently you can backup before upgrade and if anything goes wrong just restore fro it.

**Comment by hongchaodeng** [comment]
We can possibly add a timeout in upgrade.

**Comment by cehoffman** [comment]
The intention is that when upgrading, if upgraded members do not actually become part of the cluster the upgrade should be stopped or rolled back.

**Comment by xiang90** [comment]
> The intention is that when upgrading, if upgraded members do not actually become part of the cluster the upgrade should be stopped or rolled back.

Right. However, it is unplanned right now. Can you open a feature request for the upgrade rollback feature

**Comment by cehoffman** [comment]
Done
