### ISSUE TITLE
backup sidecar tolerances and taints

### ISSUE THREAD

**Issue by sstarcher** [coreos/etcd-operator#1304]
As a user I would of expected the backup sidecar to have the same taints and tolerances as the TPR for the etcd cluster itself, but instead the backup sidecar did not contain any of the taints.  In an AWS environment this restricts the ability to use the same credentials as the server the etcd pods are running on.

**Comment by hongchaodeng** [comment]
Backup policy has pod policy which can be used to set tolerations: https://github.com/coreos/etcd-operator/blob/master/pkg/spec/backup.go#L34.

 Does that work for you?

**Comment by sstarcher** [comment]
@hongchaodeng I'll check that out, but that looks like it could resolve my issue.

**Comment by sstarcher** [comment]
I verified that adding the pod spec for taint and tolerance under the backup object works.

**Comment by hongchaodeng** [comment]
We re-architect the backup story and build another backup operator.
If you have issues on the backup operator, please create a new issue for it. Thanks!
