### ISSUE TITLE
support etcd bucket prefix

### ISSUE THREAD

**Issue by sstarcher** [coreos/etcd-operator#1305]
Current the format for ETCD backups in a self-hosted cluster requires that each cluster has it's own bucket.  From a management perspective it could be helpful to have a single bucket that contains multiple clusters.

Current the format is `BUCKET/v1/NAMESPACE/ETCD_CLUSTER`
Would it be possible to support or interested in supporting a custom location or a prefixed location.

`BUCKET/ID/v1/NAMESPACE/ETCD_CLUSTER` would work in my situation as we don't give each cluster a bucket, but a subfolder under the bucket itself.

**Comment by hongchaodeng** [comment]
fixed in https://github.com/coreos/etcd-operator/pull/1372
