### ISSUE TITLE
RBAC security model discussion

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#1319]
Currently etcd operator is built for convenience. It automatically create TPR/CRD, storage class, etc. However, in a multi-tenant world, we want one cluster's operation not affect another.

There are many problems in current design:

- Operator have non-namespaced resources (CRD, storageClass) in RBAC and need to create global ClusterRole, not namespace specific Role. This could be delegated to external.
- Operator would require non-resourceName specific verbs ('create') on CRD, storageClass because we need 'create' verb. This could be delegated to external.
- One cluster's operation could affect another. Operator could touch resources like etcdcluster, Pods, Services within the same namespace.
- Even if we separate one cluster's operation into a specific deployment and limit RBAC of it on specific resource names, e.g. etcdcluster, there are still unrestrained names like pods. It also needs `list` which does not allow resourceName specific.
- The top level operator needs full access on a resource kind anyway in order to create, delete, list stuff.

**Comment by ericchiang** [comment]
General thought:

I view an operator as a way to enable a specific resource. Running the etcd-operator in a namespace make the etcd CRDs actually do something. An admin thinks about resources like `etcd.coreos.com/v1beta1.Cluster` the same way they think about resources like `Deployments`, as resources that spawn other resources.

In this world, you should never be running more than one etcd-operator per namespace, even if multiple tenants in that namespace are creating `Cluster` resources.

> Operator would require non-resourceName specific verbs ('create') on CRD, storageClass because we need 'create' verb. This could be delegated to external.

Yes, I think we should have whoever is deploying etcd-operator create the CRD. I wish we had done it this way in dex: not have dex create the CRD.

> One cluster's operation could affect another. Operator could touch resources like etcdcluster, Pods, Services within the same namespace.

Can you elaborate on that a little bit more? I would expect spawned resources like pods to be prefixed based on the etcdcluster resource, the same way the pods created through a replicaset are always prefixed with the name of the resplicaset.

> Even if we separate one cluster's operation into a specific deployment and limit RBAC of it on specific resource names, e.g. etcdcluster, there are still unrestrained names like pods. It also needs list which does not allow resourceName specific.

If you actually need to hide an etcd cluster from another user you should probably be running it in a separate namespace.

> The top level operator needs full access on a resource kind anyway in order to create, delete, list stuff.

That's fine. Just like the replicaset controller has the ability to create and delete pods. Please make sure etcd operator can run in a single namespace and not at cluster scope, though.

**Comment by hongchaodeng** [comment]
> > One cluster's operation could affect another. Operator could touch resources like etcdcluster, Pods, Services within the same namespace.
>
> Can you elaborate on that a little bit more? I would expect spawned resources like pods to be prefixed based on the etcdcluster resource, the same way the pods created through a replicaset are always prefixed with the name of the resplicaset.

If you view operator like deployment controller, don't mind about this. Otherwise, what I mean here is that the operator has the privileges to touch resources across etcd clusters.

> If you actually need to hide an etcd cluster from another user you should probably be running it in a separate namespace.

OK. I agree.

**Comment by hongchaodeng** [comment]
Closing this. Not a problem anymore.

**Comment by xiang90** [comment]
this is still a problem. just not hurting us in short term. i would suggest to keep it open.

**Comment by xiang90** [comment]
i added a future milestone.

**Comment by hongchaodeng** [comment]
A lot of issues don't hold true anymore since we separated out backup components and add the capability for `create-crd=false`.

Closing it. Revisiting RBAC security later needs re-listing existing models and issues.
