### ISSUE TITLE
Cluster domain is not respected.

### ISSUE THREAD

**Issue by zhenyuxx** [coreos/etcd-operator#1322]
When I create a Kubernetes cluster with 'example.com.' as the cluster domain, etcd-operator seems still use 'cluster.local.' for client/peer communication. Below is the log.

`2017-07-25 03:19:37.473124 W | pkg/netutil: failed resolving host etcd-cluster-0000.etcd-cluster.default.svc.cluster.local:2380 (lookup etcd-cluster-0000.etcd-cluster.default.svc.cluster.local on 10.3.0.10:53: no such host); retrying in 1s`

The code in etcd-operator/pkg/util/etcdutil/member.go might cause the issue.

```
func (m *Member) FQDN() string {
	return fmt.Sprintf("%s.%s.%s.svc.cluster.local", m.Name, clusterNameFromMemberName(m.Name), m.Namespace)
}
```

**Comment by hongchaodeng** [comment]
Dup to https://github.com/coreos/etcd-operator/issues/1021
Please wait for v0.5.1

**Comment by hongchaodeng** [comment]
Patch is welcome :)

**Comment by hongchaodeng** [comment]
Closing since dup.
