### ISSUE TITLE
etcd-backup timeout

### ISSUE THREAD

**Issue by immesys** [coreos/etcd-operator#1342]
The snapshot operation done by etcd-backup uses the default timeout which is pretty conservative. Snapshots can take many seconds, especially for large databases. This causes the backups to stop working once the DB reaches a certain size. Perhaps this can be tuned?

**Comment by immesys** [comment]
I am of the opinion that a hardcoded timeout is ok, but you should make it fairly large (e.g >30s)

**Comment by xiang90** [comment]
@immesys submit a pr to get it improved?

**Comment by immesys** [comment]
Sure
