### ISSUE TITLE
Migration from self-hosted etcd to CRD based etcd-operator

### ISSUE THREAD

**Issue by cehoffman** [coreos/etcd-operator#1356]
Using a self-hosted ETCD install that was managed by etcd-operator 0.3.0. Is there a path forward to migrate to 0.5.0 and CRD? The migration instructions intend for you to delete the etcd cluster and recreate it which is not feasible in this case.

**Comment by hongchaodeng** [comment]
Sorry for the late reply... Dismiss this issue before.
We don't really support 0.3.0 due to our limited support bandwidth.
Please just recreate it.
