### ISSUE TITLE
How to specify resource limits/requests for the etcd-cluster-backup-sidecar?

### ISSUE THREAD

**Issue by raoofm** [coreos/etcd-operator#1371]
The pod creation fails with message 

Error creating: pods "etcd-cluster-backup-sidecar-4275925802-" is forbidden: failed quota: security-rq: must specify limits.cpu,limits.memory,requests.cpu,requests.memory

I think the cause is 

> If quota is enabled in a namespace for compute resources like cpu and memory, users must specify requests or limits for those values; otherwise, the quota system may reject pod creation.

**Comment by raoofm** [comment]
backup sidecar pod fails

**Comment by hongchaodeng** [comment]
You can set in:

```
backup:
  pod:
    resources
```

https://github.com/coreos/etcd-operator/blob/master/pkg/spec/backup.go#L34

**Comment by raoofm** [comment]
@hongchaodeng thnx
