### ISSUE TITLE
Deprecate operator S3 flag

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#1377]
The operator S3 flag and per cluster S3 spec has diverged more and more. Operator S3 flag is a subset of cluster S3 spec. It's unnecessary burden to maintain two.

**Comment by fanminshi** [comment]
Deprecating operator S3 flag is plan to be included in v0.5.2 release

Plan:
1. Add deprecate warning when using operator S3 flag such as `--backup-aws-secret`, `backup-aws-config`, and `backup-s3-bucket`.
2. Add deprecation Note to [Operator level configuration](https://github.com/coreos/etcd-operator/blob/master/doc/user/backup_config.md#operator-level-configuration) documentation.

**Comment by fanminshi** [comment]
TODO: Need to add upgrade doc on upgrading 0.5.2 to 0.6.0

**Comment by hongchaodeng** [comment]
This is done.
