### ISSUE TITLE
v3.2.x compatibility?

### ISSUE THREAD

**Issue by brunomcustodio** [coreos/etcd-operator#1396]
Is `v3.2.x` supported? Are there any known issues? I've seen #1222 and #1360, but I see they are fixed now. What is the current status?

**Comment by hongchaodeng** [comment]
Not supported yet.
Blocked on issue: https://github.com/coreos/etcd-operator/issues/1384

**Comment by raoofm** [comment]
ping ?

**Comment by hongchaodeng** [comment]
Moving forward, etcd 3.2+ is definitely preferred.
The requirements on top of my head is to just change the default version and do stress testing on our CI. I will create new jobs to run it later this week.

As a side note, it is appreciated that if you guys can try it and provide more feedback, report any problems you have. Thanks!

**Comment by raoofm** [comment]
#1384 is one issue

**Comment by hongchaodeng** [comment]
ref: https://github.com/coreos/etcd-operator/pull/1607

**Comment by brunomcustodio** [comment]
@hongchaodeng I am facing all the TLS issues described in #1607 in `0.7.0`, so IMHO this should not be closed. Is at least etcd `3.2.10` still fully supported by `0.7.0`?

**Comment by hongchaodeng** [comment]
@brunomcustodio 
See "Milestone". It is in 0.7.1 .
