### ISSUE TITLE
discuss expected s3 backup restore behavior

### ISSUE THREAD

**Issue by fanminshi** [coreos/etcd-operator#1405]
There are two way to restore a s3 backup cluster: restore from existing backup and from backup of another cluster.

Two common scenarios can happen:

Backup exists: 
* Restore from existing backup or from another cluster works as intended.

Backup doesn't exist:
* Restore from existing backup fails because it can't find the backup; booting the new backup cluster fails. Is this the expected behavior?
* Restore from another cluster simple ignores the non-existent backup and boots up. is this the expected behavior?

As seem from above. The behaviors of restoring from non-existent backup are not consistent.

**Comment by hongchaodeng** [comment]
First of all, if a user wants to set "restore" policy, "backup" policy should also exist. "restore" policy would use the configuration defined in "backup" policy". It seems a mistake to have "storageType" defined in both policies. We should remove the one in restore policy.

For ease of use, a user might just set the "restore" policy ahead without concerning the case whether the backup has been made or not. Thus it should ignore non-existent backup and boot up empty etcd cluster. This is for simplicity and ease of use.

@xiang90 @fanminshi Any thoughts?

**Comment by fanminshi** [comment]
if restore policy depends on backup policy. Should restore policy be inside the backup policy as well?

**Comment by hongchaodeng** [comment]
> Should restore policy be inside the backup policy as well?

This is gonna be breaking change. Not a big issue for restore policy sitting outside.

**Comment by fanminshi** [comment]
Will removing `storageType` from restore policy also breaks change?
