### ISSUE TITLE
etcd-operator lost all clusters if I stop/start the k8s cluster

### ISSUE THREAD

**Issue by yagonobre** [coreos/etcd-operator#1467]
I get this in the pod log
```
time="2017-10-02T12:26:16Z" level=warning msg="fail to handle event: ignore failed cluster (test). Please delete its CR" pkg=controller
```

**Comment by hongchaodeng** [comment]
Can you give more details?

**Comment by yagonobre** [comment]
I created somes etcd clusters in my k8s cluster, this k8s cluster is used only for staging is shutdown at night and restarted at morning.

If I list the pods in the operator namespace I get only the pod of operator, If I try to recreate the etcd cluster the operator says that it already exists.

**Comment by hasbro17** [comment]
@yagonobre Can you please give us a series of detailed steps so that we can reproduce your issue.
Like the operator and cluster specs that you are using. And the k8s setup and environment. Also how exactly are you shutting down and restarting the k8s cluster.

**Comment by yagonobre** [comment]
@hasbro17 
1. Create a `1.7.5` k8s cluster on aws with kops.
2. Deploy the etcd operator using the `deployment-aws.yaml` example
3. Create a etcd cluster
```
apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: "test"
spec:
  size: 3
  version: "3.1.8"
```
4. Shut down the k8s cluster, by setting min,max and desire to zero in master/workers asgs.
5. Start the cluster again

**Comment by hongchaodeng** [comment]
etcd pods won't survive nodes restart until (local) PV support lands.
Currently it can only be restored via backup if such failure happened.
Closing this right now. Feel free to reopen if you still have any issues/questions.
