### ISSUE TITLE
storageType: hostPath

### ISSUE THREAD

**Issue by gintautassulskus** [coreos/etcd-operator#1504]
Hi,

Would you consider adding storageType: "hostPath"?

I am using with Rackspace Cloud provider. The smallest volume size the provider offers is 50GB SSD which is an overkill for my use, especially if it's created for each etcd node.

Although the hostPath is a suboptimal solution, still it provides some degree of persistence in case of node crashes.

PS. OpenStack's object storage might be an even better solution. Not sure if Rackspace's solution is compatible with it though.

Cheers,
Gintas

**Comment by xiang90** [comment]
storageType for what? backup?

**Comment by gintautassulskus** [comment]
Yes. Sorry, missed it.

```
  backup:
    storageType: "hostPath"
```

**Comment by hongchaodeng** [comment]
Closing this.
We have decoupled backup logic: https://github.com/coreos/etcd-operator/issues/1626
