### ISSUE TITLE
migrate date from 3 node etcd cluster to etcd operator cluster

### ISSUE THREAD

**Issue by simon-k8s** [coreos/etcd-operator#1515]
I have a 3 node etcd cluster for kubernetes. I created the cluster with kubespray. I would like to migrate the data in the old etcd to a new etcd cluster with the etcd operator. Is that possible? I have a snapshot.db of the old cluster. I tried to copy the snapshot to the volume of the etcd-cluster-backup-sidecar. I was hoping I would be able to restore from the volume if i deleted all the nodes in the etcd operator cluster. I tried this following this example:

https://github.com/coreos/etcd-operator/blob/master/doc/user/spec_examples.md#three-members-cluster-that-restores-from-previous-pv-backup

I would be grateful for any help.

**Comment by hongchaodeng** [comment]
Yes. It's possible and in our current roadmap to have a way to restore/migrate etcd data onto etcd operator managed cluster. See: https://github.com/coreos/etcd-operator/blob/master/doc/design/restore_operator.md

Right now I don't have any good answer for you. One suggestion would be to dig into the code and figure out how to use the old data to create the seed member yourself, and then create the EtcdCluster CR.

We should get this better designed and documented along the way about the specification of how etcd operator will pick up a seed member and start managing it.

**Comment by simon-k8s** [comment]
Thank you. Glad you have it on you roadmap for future versions. Moving to the etcd operator from an existing etcd cluster should be an easy task in an ideal world.
