### ISSUE TITLE
restore-operator: create backup service

### ISSUE THREAD

**Issue by fanminshi** [coreos/etcd-operator#1529]
When restore operator creates a etcd seed member, it needs a way to supply a backup snap to the seed member. Serving snapshot can be accomplished  through a backup service pod.

The backup service pod is configured with specific backup policy such as s3 where it can retrieve the latest backup from storage type. It is also exposed as a service in which the seed member can discovery it.

In order to create the back up service pod, following steps is needed:
* Expose service account discovery from cluster.
* Refactor/expose backup pod creation from cluster.
* Refactor/expose backup service creation from cluster.
* Create backup service in restore operator.

this issue keeps track of the progress of creating backup service.

**Comment by xiang90** [comment]
we should not do this for now. let only focus on s3. s3 backup can get directly from s3.
