### ISSUE TITLE
Restore process proposal

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#1531]
The new restore process:

1. restore CR is created and restore operator gets the event
2. restore operator creates the seed member, and tells it the service URL to reach for pulling backup. For now restore operator will serve the endpoint.
3. seed member tries to pull backup by sending its cluster name in HTTP param. Restore operator find its corresponding config to pull backup from remote storage and serve it to seed member.
4. seed member gets the backup. It will starts etcd process with given data.

**Comment by hongchaodeng** [comment]
A service pointing to restore operator will be created outside operator. Thus we will need to pass the service info as well, maybe via ENV?

**Comment by xiang90** [comment]
> A service pointing to restore operator will be created outside operator. Thus we will need to pass the service info as well, maybe via ENV?

restore controller should be able to figure out its own addr somehow, then inject it into the init contaienr which downloads the backup etc..

**Comment by hongchaodeng** [comment]
>  figure out its own addr somehow

You mean the Pod IP? That would be ephemeral though.

**Comment by hongchaodeng** [comment]
done via #1570
