### ISSUE TITLE
node drain Unknown controller kind EtcdCluster

### ISSUE THREAD

**Issue by simon-k8s** [coreos/etcd-operator#1546]
Hi Guys,

Sorry if I am reporting this bug to the wrong people. But I am not sure if this is a etcd operator bug or a kubernetes bug. I am running an etcd operator with a backup side car. I wanted to replace my worker nodes with a upgraded kubernetes version. So I added new nodes and drained all of the old workers with this command:
 
kubectl drain  --ignore-daemonsets kube-worker01

The nodes with the etcd cluster pods gave the following error:

Unknown controller kind “EtcdCluster”: etcd-cluster-0001

The etcd pods were not rescheduled. But the etcd cluster was rebuilt from the backup sidecar. So my data was preserved.

**Comment by hongchaodeng** [comment]
@simon-k8s 

Can you give more details how to reproduce it?

**Comment by simon-k8s** [comment]
I was running 3 worker nodes with kubernetes 1.7.2. With a running etcd operator deployment with a backup sidecar. I wanted to exchange the 4 worker nodes running 1.7.2 with 4 new nodes running kubernetes 1.7.7. So I decided to create the new worker nodes first join the cluster and then drain the old workers afterwards. I was able to drain the first node without a problem. As I reached the nodes with the etcd cluster members I received the error:

Unknown controller kind “EtcdCluster”: etcd-cluster-0001

After trying to drain the worker. The etcd pods were not rescheduled as expected. I was left with an etcd cluster without nodes. The backup sidecar did get rescheduled. And the operator seeded a new cluster from the backup sidecar.

**Comment by hongchaodeng** [comment]
@simon-k8s 
What do you expect to see?

**Comment by hongchaodeng** [comment]
> The etcd pods were not rescheduled as expected. 

So you were expecting that etcd pods would be **migrated** to new nodes as node draining was happening, right?

**Comment by hongchaodeng** [comment]
> Unknown controller kind “EtcdCluster”: etcd-cluster-0001

This error is from that kubectl drain doesn't support custom resource kind:

https://github.com/kubernetes/kubernetes/blob/e292da8192da56eb515765922d8c93a048517b85/pkg/kubectl/cmd/drain.go#L330-L342

However, kubectl drain will continue and delete the pod.

**Comment by hongchaodeng** [comment]
## Solution

The "Kind"s are hardcoded in kubectl code now. So we can't easily change that to do migration.

Manual migration is needed during node draining:
- cordon the nodes to be drained first.
- delete one etcd member at a time. Make sure that after deleting A, before deleting B, another A' is created before deleting B.

**Comment by simon-k8s** [comment]
Thank you for your explanation

**Comment by blakebarnett** [comment]
We are hitting this on 1.8.0 cluster upgrades with both kops and `kubectl drain`, I can't find an upstream issue or PR for this, is it being tracked anywhere?

**Comment by hongchaodeng** [comment]
@blakebarnett 
I don't think this is intended to be fixed by k8s. It is application logic for migration.
I don't think etcd-operator would support `kubectl drain` too because we couldn't change kubectl unless kubectl support some extension mechanism.

**Comment by hongchaodeng** [comment]
Related upstream k8s issue could be https://github.com/kubernetes/kubernetes/issues/13606 .

Only if we can extend `kubectl drain` could we customize the logic to migrate etcd pods.

**Comment by blakebarnett** [comment]
Yeah I'm tracking this issue now instead: https://github.com/kubernetes/kubernetes/issues/57049
