### ISSUE TITLE
doc: add doc for backup operator.

### ISSUE THREAD

**Issue by fanminshi** [coreos/etcd-operator#1608]
backup operator is functionally complete, but it needs documentation to describe how it is being used.

Deliverables: 
- [x] Add readme sections highlight. 
 - [x] Add readme contents.
   - [x] add overview
   - [x] add getting started

ref: https://github.com/coreos/etcd-operator/pull/1609

**Comment by hongchaodeng** [comment]
Ultimately, the top README will only contain doc links to etcd operator, backup, restore .

Then etcd operator, backup, restore docs will be an example setup/walkthrough guide.
Once we have more patterns what features user would care most, we will write more reference docs for that.

**Comment by fanminshi** [comment]
@hongchaodeng I am planning for writing doc in series following the step by steps of the list.
