### ISSUE TITLE
Decoupling Backup and Restore Logic from Etcd Operator

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#1626]
# Decoupling Backup and Restore Logic from Etcd Operator

Currently the [backup][backup_policy] and [restore][restore_policy] are provided as features in the EtcdCluster API. These features have been useful and adopted by open source users. Over time, there are increasing requests to extend the functionalities (#1316, #1241). On the other hand, there is a limit for adding the features due to: 1. extending the API needs to happen in upstream codebase; 2. it is conflicted with making current API stable. Especially (2), because it blocks stabilizing the project.

To solve the above problems, we propose new ways to do backup and restore:

- Backup: Currently EtcdCluster includes [BackupPolicy][backup_policy] to periodically save etcd snapshots. Instead, we propose to add a new [EtcdBackup][etcd_bakcup_api] API which includes a reference to the EtcdCluster that it wants to make backup from. We built [etcd-backup-operator][backup_operator_doc] as an example to save backups onto S3. As a result, etcd operator doesn’t need to know anything about backup.
- Restore: Currently EtcdCluster includes [RestorePolicy][restore_policy] to restore an etcd member from a backup. Instead, we propose to add a new [EtcdRestore][etcd_restore_api] API which includes the backup resource information and the EtcdCluster to be restored. We built [etcd-restore-operator][restore_operator_doc] as an example to restore the data and create a new EtcdCluster. etcd operator can still manage the restored cluster, but it doesn’t need to know anything about the restore process.

By using the above methods, we can decouple backup and restore logic from etcd operator, and thus can remove BackupPolicy and RestorePolicy from EtcdCluster API.

## User effect

Existing backup and restore features in EtcdCluster API won’t be supported after 0.7.0 release. Please check [migration docs][migrate_doc] before upgrading.

The open source etcd-backup-operator and etcd-restore-operator are provided as examples for how to use EtcdCluster API. Based on what we know, most Internet company users have their own ways to do etcd backup and restore. We expect these users would write their own tooling and make their work easier by decoupling them from our codebase. For enterprise users, we recommend trying out [Tectonic](https://coreos.com/tectonic/) and make [contacts](https://coreos.com/contact/) for customized etcd backup/restore solutions.

Moving forward, we will focus on stabilizing etcd operator and make a stable release soon.

[backup_policy]:https://github.com/coreos/etcd-operator/blob/9f38be4ddbf7cb9873d95e9fd7411ebd25118f28/pkg/apis/etcd/v1beta2/cluster.go#L112
[restore_policy]:https://github.com/coreos/etcd-operator/blob/9f38be4ddbf7cb9873d95e9fd7411ebd25118f28/pkg/apis/etcd/v1beta2/cluster.go#L118
[etcd_bakcup_api]:https://github.com/coreos/etcd-operator/blob/9f38be4ddbf7cb9873d95e9fd7411ebd25118f28/pkg/apis/etcd/v1beta2/backup_types.go#L32
[etcd_restore_api]:https://github.com/coreos/etcd-operator/blob/9f38be4ddbf7cb9873d95e9fd7411ebd25118f28/pkg/apis/etcd/v1beta2/restore_types.go#L33
[backup_operator_doc]:https://github.com/coreos/etcd-operator/blob/ea97b1d554354550626640945d42dd08c38445d5/doc/user/walkthrough/backup-operator.md
[restore_operator_doc]:https://github.com/coreos/etcd-operator/blob/ea97b1d554354550626640945d42dd08c38445d5/doc/user/walkthrough/restore-operator.md
[migrate_doc]:https://github.com/coreos/etcd-operator/blob/ea97b1d554354550626640945d42dd08c38445d5/doc/user/upgrade/migrate_cr_070.md

**Comment by hongchaodeng** [comment]
v0.7.0 is released: https://github.com/coreos/etcd-operator/releases/tag/v0.7.0

**Comment by swapnilgm** [comment]
Sorry for replying on closed issue, but I think this is best place to have correct context. 

> The open source etcd-backup-operator and etcd-restore-operator are provided as examples for how to use EtcdCluster API. Based on what we know, most Internet company users have their own ways to do etcd backup and restore. We expect these users would write their own tooling and make their work easier by decoupling them from our codebase.

Does that mean this project will only stabilise etcd-operator and not backup and restore operator? Or is it under the roadmap that will eventually give fixed/stabilised  backup operator structure/template and add some basic backup interface (something like save, delete, list API)  and let user handle  implementation of this interface for storage provider rather than whole backup operator. I think this is why issue #1241 is still open.

**Comment by xiang90** [comment]
We will support an example backup/restore operator with limited functionality. Users want more advanced or customized feature can fork it, and develop on their own.

**Comment by raoofm** [comment]
@xiang90 a backup or restore operator with limited functionality is fine and I totally agree with getting away from maintaining tons of usecases that might pop up. But there is a concern where this basic functionality comes with a warning to not use in production. It would be great if at least 1 production grade usecase is implemented/satisfied for others to follow even if it is just s3 or pv.

**Comment by xiang90** [comment]
@raoofm 

Yes. We will make the basic functionality stable overtime, and suggest that it is production ready.
/cc @fanminshi @hongchaodeng
