### ISSUE TITLE
migrate etcd or run etcd before run kubernetes

### ISSUE THREAD

**Issue by beatlejuse** [coreos/etcd-operator#1636]
i'm using CoreOS and run fisst etcd cluster, embedded in CoreOS, for initialisation kubernetes.
how can i include my old etcd instances (on coreos) to new etcd cluster, managed by etcd-operator?
or, how can i use etcd-operator to start first etcd cluster, used to initialize kubernetes?

**Comment by hongchaodeng** [comment]
That's not supported now.

We are now reducing etcd operator's responsibility. There is a way to migrate as demonstrated by [restore operator](https://github.com/coreos/etcd-operator/blob/master/doc/user/walkthrough/restore-operator.md) to restore a backup and the let etcd operator.

**Comment by beatlejuse** [comment]
Thank you for answer!
 in bootkube (https://github.com/kubernetes-incubator/bootkube) described the process of transition from native etcd cluster fo etcd-cluster (https://youtu.be/EbNxGK9MwN4 from 31:30).
I can't understand how this is realized. Do you know, how can this be done?
I really need this automation element

**Comment by hongchaodeng** [comment]
That's self-hosted etcd. It is for k8s only.
Please follow the progress on bootkube and kubeadm.

> I can't understand how this is realized. Do you know, how can this be done?
> I really need this automation element

For support, see CoreOS contact: https://coreos.com/contact/
We only handle technical coding & design in this repo.
