### ISSUE TITLE
Provide scripts to run e2e tests inside a pod

### ISSUE THREAD

**Issue by hasbro17** [coreos/etcd-operator#1640]
Being able to run e2e tests inside a pod on a kubernetes cluster would make it easy to run the e2e tests during local development without testing against the CI.

- [x] Run e2e tests (https://github.com/coreos/etcd-operator/pull/1638)
- [x] Have the `run-test-pod` script check if the test-pod succeeds or fails
- [x] Have the `run-test-pod` script setup the RBAC for the test-pod and tests 
- [x] Log collector program to collect all interested logs (e.g. e2e test, etcd operator)
- [x] Consolidate build scripts for operator and test-pod and run them in a container.
- [x] Use it in Jenkins
  - [x] Change existing workflow: Build the operator image first, then run e2e tests in a pod
- [x] use hack/ci/run to:
  - build operator and test-pod images
  - generate test-pod spec from the template
  - run test-pod
- [x] Run upgrade tests
- [x] Remove the build pass from `hack/test` once all CI jobs are using the pod testing workflow.
- [x] Remove `hack/ci/run`

**Comment by hongchaodeng** [comment]
@hasbro17 
I think it already works today:
https://github.com/coreos/etcd-operator/tree/master/test/pod#run-the-test-pod
Right?

There are two more steps:
- logs
- concurrent jobs

I would recommend to finish the logs first and then switch our existing jenkins jobs to use it.

Currently we have two jenkins jobs and we can combine them into one and solve concurrent jobs in one jenkins job as a second step.

**Comment by hasbro17** [comment]
Yes the `run-test-pod` script already works right now by running each pass serially. So if you run a single pass `e2e` it work. The PR(https://github.com/coreos/etcd-operator/pull/1685) was meant to run the passes concurrently. But as suggested we can tackle that separately.

For now I'll change the `run-test-pod` script to save logs to a file and then update the jenkins jobs for each pass to use the script.

**Comment by hongchaodeng** [comment]
The primary goal is to containerize all tests, incl. unit, upgrade.
After that, we can think about how to improve them. Running them concurrently in one jenkins job is an improvement.

**Comment by hongchaodeng** [comment]
I added the task for collecting logs.
My proposal: build a new program "log collector". Replacing [these lines](https://github.com/coreos/etcd-operator/blob/9bdfb337f92f349ba495e21e379367bddebfee6b/test/pod/run-test-pod#L74-L78) to collect all interested logs, e.g. e2e test, etcd operator.

**Comment by hasbro17** [comment]
Currently running e2e test in CI requires building and pushing the following images before testing:
- operator image: etcd-operator, backup-operator, and restore-operator
- test-pod image

The build step for the operator image is currently in [hack/test](https://github.com/coreos/etcd-operator/blob/62d20d4d25bf0d090856899517f8d19630846447/hack/test#L87-L106)

Both these build steps should be consolidated into a single script e.g `hack/build/e2e`. Secondly, both builds should be run inside a docker container with the image `golang:1.9-alpine` and not locally on the CI machine.

I've added a task for this above.

**Comment by hasbro17** [comment]
The build steps for e2e tests have been containerized and consolidated.
https://github.com/coreos/etcd-operator/pull/1717

Now replacing the existing CI jobs on jenkins with the pod testing workflow.

**Comment by hongchaodeng** [comment]
Some ideas around speeding up the performance:

- Currently "e2e" test suite do not have any parallelization. We could optimize it. I'm not sure whether "docker run" has this issue or not.
- Build e2e test binaries along with build step. This could make use of caching.
- Run three operators in same pod. Save time in creating the pod and image pulling (they use the same image).

**Comment by hasbro17** [comment]
Once all the CI jobs are using the pod testing script `hack/ci/run_e2e` we can remove the `build` pass from `hack/test`. 
https://github.com/coreos/etcd-operator/blob/master/hack/test#L29-L48
Added a TODO for this.
