### ISSUE TITLE
Example etcd-backup-operator has no image

### ISSUE THREAD

**Issue by akauppi** [coreos/etcd-operator#1649]
The example [etcd-backup-operator/deployment.yaml](https://github.com/coreos/etcd-operator/blob/master/example/etcd-backup-operator/deployment.yaml#L14) has:

`        image: <operator-image>
`

This is likely a placeholder that should get replaced by a proper image address, like `quay.io/coreos/etcd-backup-operator:v0.6.1`? If not, people need instructions on how to build such an image ourselves.

Related to: #1626

**Comment by akauppi** [comment]
This also applies to the [etcd-restore-operator/deployment.yaml](https://github.com/coreos/etcd-operator/blob/master/example/etcd-restore-operator/deployment.yaml#L16)

**Comment by fanminshi** [comment]
@akauppi good catch. I'll improve the walkthrough.

in the meantime, you can to build the image with following.

building backup-operator image:

first, build operator binary:
`./hack/build/backup-operator/build`

then push your image with `docker_push` script:
`IMAGE=<your-image-name> ./hack/build/docker_push`

the build and push script is simple enough. you can read it yourself.

**Comment by akauppi** [comment]
Thanks, @fanminshi 

I noticed the build places all three operators in the same image (good approach), so one option for me would be simply to wait until the `etcd-operator` release that has them. Would that mean 0.7.0 and how much calendar time?

note: I had a look at [ROADMAP](https://github.com/coreos/etcd-operator/blob/master/ROADMAP.md) but it seems out-of-date, so I need to ask... :)

**Comment by hongchaodeng** [comment]
Yeah. ROADMAP is outdated. We now usually track roadmaps in github milestone and design docs.

**Comment by fanminshi** [comment]
@akauppi 0.7.0 is released https://github.com/coreos/etcd-operator/releases/tag/v0.7.0. you should have no trouble of following the examples. Please let me know if you have any questions!
