### ISSUE TITLE
Use full image to replace `baseImage` field

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#1675]
Currently we provide simple `version` field to indicate the etcd version and provide upgrade functionality.

Later we add `baseImage` field to support custom image. But the custom image feature is weird because it assumes format:
```
${baseImage}:v${version}
```

First of all, not all tags are semantic versions. Second, the middle `v` is weird. We should probably add an `image` field in PodPolicy. When not empty, `image` field is used and `version` field is ignored.

**Comment by xiang90** [comment]
We want to control the version field. We should not let users to provide arbitrary image, which will make our upgrade story harder.

**Comment by hongchaodeng** [comment]
> We want to control the version field.

Controlling `version` field is definitely good for everyone. And we can provide better version management based on that.

The problem comes from `baseImage` field. These are custom/thirdparty images that we don't support. Since there is big demand so we add it. But coupling it with the `version` field  is not right as described above.

**Comment by xiang90** [comment]
> The problem comes from baseImage field. These are custom/thirdparty images that we don't support. Since there is big demand so we add it. But coupling it with the version field is not right as described above.

The baseimage field is to solve that problem that users have a cloned repo of etcd. It should contain all tags, versions the original etcd repo has. If not, it wont work.

I do not think we are going to support arbitrary image/repo anytime soon. Now etcd operator assumes it controls the version of etcdserver through tagging. Before doing arbitrary image, we need to be able to detect etcd server versions from a random image.
