### ISSUE TITLE
Split etcd across different AZs

### ISSUE THREAD

**Issue by drewwells** [coreos/etcd-operator#1676]
When picking nodes to lay down etcd pods, we want these to be evenly distributed across AZs. As an example, AZ1 AZ2 AZ3. If 3 etcd pods are desired, then each one should be created in a different AZ. The assumption here is that nodes have some sort of label to identify which AZ they are part of or other mechanism for doing so. 

A snapshot of ETCDs running would look like this

AZ1 etcd-0001
AZ2 etcd-0002
AZ3 etcd-0003

If one pod dies, a new one gets created and put in an AD that the previous etcd died in

AZ1 etcd-0001
AZ2 etcd-0002 (died) etcd-0004 (new)
AZ3 etcd-0003

**Comment by hongchaodeng** [comment]
Thanks @drewwells !
Original conversation: https://groups.google.com/forum/#!topic/coreos-dev/gCjKG3MmGz0

> etcd operator currently only supports anti-affinity across nodes. However, it could extend the feature beyond that.

**Comment by xiang90** [comment]
i thought we also support node selector?

**Comment by hongchaodeng** [comment]
> i thought we also support node selector?

Node selector will put all pods onto the same set of nodes. In this case, it is different sets of nodes on different zones probably. It needs pod anti-affinity rules to spread across zones.

**Comment by xiang90** [comment]
i thought we can label nodes in the AZs that the user wants etcd landing on, also we need to add anti-affinity. So etcd nodes will spread out to achieve the requirement.

**Comment by hongchaodeng** [comment]
You are right about this.
The issue here is another problem. We currently hard-code "anti-affinity" topologyKey to  "kubernetes.io/hostname". We could probably change that to more generic anti-affinity field.

**Comment by xiang90** [comment]
ok. got it. thanks.

**Comment by discordianfish** [comment]
I came here wondering if the etcd-operator even distributes the pods across *nodes*. I can't find a clear answer to that and browsing through the code I can't find anything that would ensure this.
How does etcd-operator make sure not all my pods end up on the same node?

**Comment by drewwells** [comment]
K8s will generally do this just by spreading load. You can also specify
antiAffinity in the spec.
