### ISSUE TITLE
Remove GC from etcd-operator

### ISSUE THREAD

**Issue by hasbro17** [coreos/etcd-operator#1678]
All EtcdCluster resources(services and pods) have their owner reference set to their cluster Custom Resource.
https://github.com/coreos/etcd-operator/pull/525/files

K8s Garbage Collection(GC) for CRs is already enabled since 1.7 so the GC in etcd-operator is no longer needed.
https://github.com/coreos/etcd-operator/blob/master/pkg/garbagecollection/gc.go

**Comment by hongchaodeng** [comment]
dup to https://github.com/coreos/etcd-operator/issues/1337
