### ISSUE TITLE
Recovering from total loss.

### ISSUE THREAD

**Issue by brunomcustodio** [coreos/etcd-operator#1689]
Unless I am missing something, the documentation is not clear on how to proceeed in this situation:

- I was running `etcd-operator` (0.6.0 in case it matters).
- I had an `EtcdCluster` with three members.
- I got hold of a snapshot of the cluster at revision `X` which I got from the backup sidecar's API.
- I lost the Kubernetes cluster (could be anything — an accidental delete, etc).
- I created a new Kubernetes cluster and want to relaunch `etcd-operator` and an `EtcdCluster` at revision `X`.

My question is, then, how can I use the snapshot file that I got hold of to achieve this.

**Comment by hongchaodeng** [comment]
From 0.7.0+, a restore operator will take the snapshot file and do the restore process.

See:
- https://github.com/coreos/etcd-operator/blob/master/doc/user/walkthrough/restore-operator.md
- https://github.com/coreos/etcd-operator/blob/master/example/etcd-restore-operator/restore_cr.yaml

**Comment by brunomcustodio** [comment]
@hongchaodeng I see, but I am running 0.6.0 and cannot upgrade at the moment. Isn't there a way to achieve this in 0.6.0?

**Comment by hongchaodeng** [comment]
Yes. There was previous restore policy embedded in the cluster spec: https://github.com/coreos/etcd-operator/blob/v0.6.0/doc/user/spec_examples.md#three-members-cluster-that-restores-from-previous-s3-backup .

**Comment by brunomcustodio** [comment]
@hongchaodeng isn't there a way to drop the snapshot somewhere else (e.g., in the PV) and have it restored from there (without involving S3)?

**Comment by hongchaodeng** [comment]
Open source support only provides S3 backup/restore:
https://github.com/coreos/etcd-operator/blob/master/doc/user/walkthrough/restore-operator.md

**Comment by hongchaodeng** [comment]
Closing this issue since docs is provided already.
