### ISSUE TITLE
There is no option available for setting the S3 API endpoint

### ISSUE THREAD

**Issue by givia** [coreos/etcd-operator#1720]
We would like to use S3-compatible services instead of AWS.

**Comment by hongchaodeng** [comment]
@givia Can you give more details about the use case?

**Comment by givia** [comment]
We are using etcd operator so for backup/restore procedure, we need to use S3. But for some reasons we are not able to use AWS. There are some S3-comptible storage solutions such as Ceph and Minio. We use them instead of AWS S3. But in etcd backup operator there is no way to specify a custom endpoint for S3 and so we can't use these solutions.

**Comment by hongchaodeng** [comment]
Thanks for the clarification!

**Comment by alexandrem** [comment]
This is addressed by #1820

**Comment by xiang90** [comment]
this is fixed by https://github.com/coreos/etcd-operator/pull/1855
