### ISSUE TITLE
Kubernetes 1.8 (Custom Resource) support?

### ISSUE THREAD

**Issue by libesz** [coreos/etcd-operator#1747]
Hi,
 I've just tried to spin up the etcd-operator on kubernetes 1.8. I did it with the stable helm chart, but should not matter I think. I got the logs like:
`time="2017-12-08T15:43:20Z" level=error msg="initialization failed: fail to create TPR: the server could not find the requested resource" pkg=controller `
This is I believe due to kubernetes 1.8 totally deprecated the TPR resource in favor of CRs.

Is there any plan to support the custom resources with the etcd-operator?

**Comment by hongchaodeng** [comment]
etcd operator has already supported CRD.
But in helm the etcd operator version is very old.
This is helm issue? Please report it to helm. If you want to use newer versions of etcd operator please follow our README.

**Comment by hongchaodeng** [comment]
Closing this since it is more a helm issue.

**Comment by libesz** [comment]
Oops! Sorry about that.
