### ISSUE TITLE
etcd backup operator persistent volumes

### ISSUE THREAD

**Issue by simon-k8s** [coreos/etcd-operator#1757]
I am trying to use the etcd backup operator to backup a etcd cluster to a persistent volume. I am not sure if this is possible yet. I can't find any information in the docs. The only example I could find is for an S3 bucket. I am seeing the following error:

` kubectl logs etcd-backup-operator-7d9d7db887-bh2v7
time="2017-12-12T10:06:04Z" level=info msg="Go Version: go1.9.1"
time="2017-12-12T10:06:04Z" level=info msg="Go OS/Arch: linux/amd64"
time="2017-12-12T10:06:04Z" level=info msg="etcd-backup-operator Version: 0.0.1+git"
time="2017-12-12T10:06:04Z" level=info msg="Git SHA: ba1ce6e"
time="2017-12-12T10:06:04Z" level=info msg="Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"default", Name:"etcd-backup-operator", UID:"2a8fd5c7-defa-11e7-bd6c-0a580ae94263", APIVersion:"v1", ResourceVersion:"5794433", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' etcd-backup-operator-7d9d7db887-bh2v7 became leader"
time="2017-12-12T10:06:05Z" level=info msg="starting backup controller" pkg=controller
time="2017-12-12T10:06:05Z" level=fatal msg="unknown StorageType: PersistentVolume"`

Am I doing something wrong? Or is the support for persistent volumes missing?

This is my backup yaml:

apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdBackup"
metadata:
  name: etcd-cluster-backup
spec:
  clusterName: etcd-cluster
  storageType: "PersistentVolume"
  PersistentVolume:
    volumeSizeInMB: 1024 
    storageClass: generic

**Comment by hongchaodeng** [comment]
It's not supported yet.

**Comment by simon-k8s** [comment]
Ok thanks would be great to see support for this soon.
