### ISSUE TITLE
EtcdBackup/EtcdRestore API groomming

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#1763]
EtcdBackup was originally decoupled from EtcdCluster and had many legacy parts. We did that for speed.

We need to further improve EtcdBackup/EtcdRestore API:
- [x] take in etcd endpoint instead of clusterName: https://github.com/coreos/etcd-operator/issues/1721
   - PR: https://github.com/coreos/etcd-operator/pull/1772, https://github.com/coreos/etcd-operator/pull/1779
- [x] write to S3 path instead of relying on combinations of clusterName and internal scheme
  - PR: https://github.com/coreos/etcd-operator/pull/1774, https://github.com/coreos/etcd-operator/pull/1775
- [x] EtcdRestore should take in EtcdCluster ref: https://github.com/coreos/etcd-operator/issues/1770
- [x] expose etcd version and revision in backup status.
  - PR: https://github.com/coreos/etcd-operator/pull/1792
- [x] EtcdRestore should take in BackupStorageType.
  - Fields added. Still needs validation.
  - PR: https://github.com/coreos/etcd-operator/pull/1794

**Comment by hongchaodeng** [comment]
I'm removing the "delete CR would delete backup" item from this issue.
Because it is not obvious how that would be a safe way -- how would I know if a CR was deleted and its backup still existed?
We'd better create an new issue for this specifically.

**Comment by xiang90** [comment]
> Because it is not obvious how that would be a safe way -- how would I know if a CR was deleted and its backup still existed?
We'd better create an new issue for this specifically.

agreed. can you create a new issue now?
