### ISSUE TITLE
Restore failed with non-TLS cluster backup

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#1804]
If I made a snapshot from a fresh cluster, restore will fail:
`Error:  snapshot missing hash but --skip-hash-check=false`

**Comment by hongchaodeng** [comment]
Seems like I also encountered the issue even if I write some data.

**Comment by hongchaodeng** [comment]
Closing this now since I couldn't get TLS cluster work either.
I'm digging into it and will provide more details.

**Comment by ultimateboy** [comment]
If you are landing here, you probably have a corrupt backup. Recommendation is to delete the newest backup and hopefully your second-newest is not corrupt.
