### ISSUE TITLE
Use etcd-operator package to manage cluster programatically

### ISSUE THREAD

**Issue by radu-matei** [coreos/etcd-operator#1811]
Hi, everyone!
First of all thanks for a great tool!

I'm getting started with `etcd-operator` and I'm thinking about using this to programatically deploy and manage clusters on Kubernetes.

Is this a scenario you've taken into consideration? I'll basically vendor this repo and use the `pkg` packages to do it - but before I'm actually trying, just wanted to know if this scenario is supported.

Thanks,
Radu M

**Comment by hongchaodeng** [comment]
Can you provide more details of what you are going to do? Maybe with some real use cases?

**Comment by radu-matei** [comment]
I'm adding state management to a CLI and web based tool - the state management is optional, and if opted-in, then the tool should automatically deploy an etcd cluster and use it to store its state.

Now I'm trying to understand the most convenient way to deploy and manage the cluster.

**Comment by hongchaodeng** [comment]
If you want to programmatically deploy and manage etcd clusters, use API to achieve manipulation:
https://github.com/coreos/etcd-operator/tree/master/pkg/apis/etcd/v1beta2

**Comment by radu-matei** [comment]
Thanks a lot, closing this.
