### ISSUE TITLE
Support custom S3 api endpoint

### ISSUE THREAD

**Issue by alexandrem** [coreos/etcd-operator#1830]
Currently it is not possible to use a different object storage service than AWS S3 when doing backups of type S3.

A common use case would be to deploy etcd-operator on-premise and use a compatible S3 service like OpenStack Swift or Minio.

backup-operator and restore-operator should work seamlessly with this API service by using an appropriate configuration.

Related issues:
#1720

**Comment by alexandrem** [comment]
Feature was submitted: #1820

**Comment by xiang90** [comment]
this is fixed by https://github.com/coreos/etcd-operator/pull/1855
