### ISSUE TITLE
e2e master is failing

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#1831]
https://jenkins-etcd.prod.coreos.systems/job/etcd-operator-master/749/

```
time="2018-01-05T10:53:34Z" level=error msg="fail to setup framework: failed to setup etcd operator: failed to wait pod running, it is still pending: still failing after 12 retries" 
FAIL	github.com/coreos/etcd-operator/test/e2e	61.341s
```

Tried it twice and failed consistently.

**Comment by hasbro17** [comment]
Taking a look at this.

**Comment by hongchaodeng** [comment]
The root:

Jenkins [Workspace Cleanup](https://wiki.jenkins.io/display/JENKINS/Workspace+Cleanup+Plugin) plugin was not working, and leaving many timestamp-ed job dirs (one per build!):
```
# ls workspace/
etcd-operator-master_ws-cleanup_1515185270677  etcd-operator-master_ws-cleanup_1515186750450
```

Each dir consume 330MB. `vendor/` consumes 180MB and `_output/` consume 120MB.

**Comment by hongchaodeng** [comment]
If we could set the dir permissions correctly, the workspace cleanup should work.
