### ISSUE TITLE
example: cron job example for periodic backups

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd-operator#1832]
some users wonder if we can provide an example of this. i think it is a good idea.

**Comment by xiang90** [comment]
/cc @rjtsdl 

we do not have an example so far... actually if you can play with it, and create an example, it would be awesome!

**Comment by mat285** [comment]
Seems like there isn't a way to specify a backup interval in the go sdk, is there a reason for this?

**Comment by rjtsdl** [comment]
@mat285 

Yeah, the interval is removed. The recommended way is to use CronJob to faciliate the regular schedule. I am trying to work out a CronJob sample myself today. 

Hopefully i can share it.

**Comment by rjtsdl** [comment]
@xiang90 

If I read the code right, backup operator will only create the backup once, when backup CRD is created. So the CronJob is basically doing things like.

while (true)
   1. Try to delete stale backup CR if exist.
   2. Create a backup CR (cannot have name conflict with existing CR)

Does that sounds right? I was thinking, there is other way instead of create CR, that can trigger another round of backup.

**Comment by hongchaodeng** [comment]
> Does that sounds right?

Right. Please submit the CronJob as a PR. We don't need a fully working example at first.

**Comment by rjtsdl** [comment]
@hongchaodeng 

For this piece code, I would expect on the **Update** scenario, we can also handle the backup. Do you have any objection? I can send a PR for this.
```
        // don't process the CR if it has a status since
	// having a status means that the backup is either made or failed.
	if eb.Status.Succeeded || len(eb.Status.Reason) != 0 {
		return nil
	}
```

**Comment by xiang90** [comment]
@rjtsdl 

I think the cronjob should simply asking for new backups with new CR name (probably timestamped like: etcd-backup-"01/02 03:04:05PM").

we can worry about backup retention, and clean up later on.

**Comment by xiang90** [comment]
> For this piece code, I would expect on the Update scenario, we can also handle the backup. Do you have any objection? I can send a PR for this.

I do not think we want to handle CR update. one CR per backup is what we want. Once a backup is made for that CR, it is immutable.

**Comment by hongchaodeng** [comment]
ref: https://github.com/coreos/etcd-operator/issues/1841
