### ISSUE TITLE
etcd-operator doesn't restart services after VM reboot

### ISSUE THREAD

**Issue by AlvinCJin** [coreos/etcd-operator#1840]
I use the example yml files to deploy an etcd cluster in K8s in following steps.
I use this version etcd-operator:v0.5.1
1. Create name space
   - kubectl create -f namespace.yml
2. Create required RBAC objects
   - kubectl create -f etcd-k8s-init.yml
3. Deploy etcd operator
   - kubectl create -f deployment.yaml
4. Create etcd cluster
   - kubectl create -f example-etcd-cluster.yaml

Everything goes well, except that after we reboot VMs, etcd pods, operator are auto-deployed except below 2 services
example-etcd-cluster 
example-etcd-cluster-client 
Any ideas about it?

Thanks.

**Comment by hongchaodeng** [comment]
> after we reboot VMs

Can you provide operator logs and etcdcluster CR?

> etcd-operator:v0.5.1

This seems really outdated. What are you using etcd operator for? Also try to update to latest version?

**Comment by AlvinCJin** [comment]
Hi @hongchaodeng ,

I upgraded etcd-operator to v0.8.0 in K8s 1.8
The script I used is the same as ones in the example folder, except adding a namespace.
After upgrading, the rebooting VMs causes pods issues. While the services can be restart automatically.
$ kubectl get svc -n etcd-k8s
NAME                          TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                               AGE
example-etcd-cluster          ClusterIP      None             <none>        2379/TCP,2380/TCP                     59m
example-etcd-cluster-client   ClusterIP      10.103.201.232   <none>        2379/TCP 

$ kubectl logs etcd-operator-196720154-9kq54 -n etcd-k8s
time="2018-01-09T20:13:00Z" level=info msg="etcd-operator Version: 0.8.0"
time="2018-01-09T20:13:00Z" level=info msg="Git SHA: 14aa69c"
time="2018-01-09T20:13:00Z" level=info msg="Go Version: go1.9.2"
time="2018-01-09T20:13:00Z" level=info msg="Go OS/Arch: linux/amd64"
time="2018-01-09T20:13:00Z" level=info msg="Event(v1.ObjectReference{Kind:"Endpoints", Namesp                  ace:"etcd-k8s", Name:"etcd-operator", UID:"88b08643-f571-11e7-92ed-023ca6e24342", APIVersion:                  "v1", ResourceVersion:"7966444", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' etcd                  -operator-196720154-9kq54 became leader"
time="2018-01-09T20:13:00Z" level=info msg="start running..." cluster-name=example-etcd-clust                  er pkg=cluster
time="2018-01-09T20:13:13Z" **level=error msg="failed to update members: list members failed**: c                  reating etcd client failed: grpc: timed out when dialing" cluster-name=example-etcd-cluster p                  kg=cluster
time="2018-01-09T20:13:21Z" level=warning msg="all etcd pods are dead." cluster-name=example-                  etcd-cluster pkg=cluster
time="2018-01-09T20:13:29Z" level=warning msg="all etcd pods are dead." cluster-name=example-                  etcd-cluster pkg=cluster

Any suggestions?
Thanks.

**Comment by hongchaodeng** [comment]
> After upgrading, the rebooting VMs causes pods issues. 

If you see the following logs:
```
all etcd pods are dead.
```
Rebooting the VM would causes all etcd pods to go down. Currently etcd operator can't handle it.

**Comment by xiang90** [comment]
@AlvinCJin 

how many VMs do you have? Are all the etcd pods in the cluster bind to the VMs that you restarted at the same time?

**Comment by AlvinCJin** [comment]
Hi @hongchaodeng  and @xiang90 
Thank for your response.
6VMs for K8s cluster in AWS. yes, since we schedule shotdown our dev cluster during weekend.

**Comment by xiang90** [comment]
@AlvinCJin 

then you need https://github.com/coreos/etcd-operator/issues/1323 to make the cluster persist data to recover from full down case. please track that issue instead.
