### ISSUE TITLE
[Proposal] support periodic backups

### ISSUE THREAD

**Issue by rjtsdl** [coreos/etcd-operator#1841]
I already seen a bunch of ask about how to schedule periodic backup. 

The current design will not support that, and suggest to use CronJob to create backup CR periodically (Only creation can trigger the actual backup handling function). 

Here are some **cons** of this methods.
- CronJob is scheduled by k8s scheduler. For clusters has 100s etcd-operators, it will be a big load on the scheduler. (It is not the option for me at Azure) @khenidak on more thoughts.
- For users seeking backup operator, they are looking into a solution. Backup scheduling always comes with Backup itself 
- It is not very intuitive to create a CronJob with access to k8s api-server. It involves secret handling.

So, i propose to have **backupPolicy** option. 
- If backupPolicy not provided, it will not do periodic backup. It will be the same of existing behavior, which does one-time backup.
- For backupIntervalInSecond 
  - unit in Sec
  - \>0 means interval. Of course, we will have the minimal interval limit.
  - \=0 means explicit disable interval backup, it will just do one time backup.
  - \<0 not allowed, failed validation
  - It doesn't need to strictly refer to the interval. For any reason the backup operator get restarted, we can just ignore the last backup time
- For maxBackups
  - specify how many backups we want to keep
  - maxBackups == 0 => unlimited backup

Related Issues: #1787

-----------------------------------------------------------------------------------------------------------------

Based on above proposal,

When user specify in backup CR
```
spec:
  backupPolicy:
    maxBackups: 4
    backupIntervalInSecond: 30
  s3:
     path: "mybucket/mycluster_backup"
  ...
```

We will have "mybucket/mycluster_backup_v{revision}_{date}"
And for each revision, we keep up to 4 revisions.

The same logic apply to restore operator as well.

**Comment by xiang90** [comment]
i do not like the idea to overwrite other backups. maybe we can append suffix after the provide path, , do periodic backups, and configured retentions.

**Comment by rjtsdl** [comment]
@xiang90 updated the proposal a bit, based on your comment.

**Comment by rjtsdl** [comment]
Update the proposal, we don't need to split it to slices anymore.

**Comment by xiang90** [comment]
i suggest to group the backup policy related fields together, so that people do not need the feature can simply ignore them as a whole. other than that, it looks fine.

**Comment by khenidak** [comment]
Shall we consider this proposal approved?

**Comment by xiang90** [comment]
@khenidak 

i am ok with it. @fanminshi any opinions?

**Comment by fanminshi** [comment]
@rjtsdl what do you mean by `revision`? is this the etcd kv revision?

**Comment by fanminshi** [comment]
@rjtsdl also if I want to manually trigger an backup now? how would this proposal support that? do we want to support that scenario?

**Comment by khenidak** [comment]
@fanminshi what is the use case for manual trigger (Specially if a backup is running at short interval)?

**Comment by rjtsdl** [comment]
@fanminshi  revision will mean etcd kv revision.

If you just want to trigger one time backup. Just don't specify values below.
```
  maxBackups: 4
  backupIntervalInSecond: 30
```

**Comment by fanminshi** [comment]
@khenidak for short interval. I agree with you it doesn't matter that much. However, for a longer one, it can be useful. Suppose that user wants to re-create an etcd cluster from the backup. The user could either waits until next backup to happen which can be in an hour or trigger an backup now.

**Comment by fanminshi** [comment]
@rjtsdl `>0 means interval, <=0 mean disable`. if we don't specify `maxBackups` and `backupIntervalInSecond`,  the `backupIntervalInSecond` will be 0 right which means disable backup. So what does disable mean in this case? does it mean etcd operator will do one time backup trigger but without `periodic backups`?

**Comment by khenidak** [comment]
@fanminshi in this case a CRD + schedule should be implemented. I agree.

**Comment by hongchaodeng** [comment]
Please see comment https://github.com/coreos/etcd-operator/issues/1841#issuecomment-357119113

> i suggest to group the backup policy related fields together, so that people do not need the feature can simply ignore them as a whole. 

This would be a better format.

> <=0 mean disable

Instead of "disable", we should set a default internal. As a user I might not have a specific number ahead. Additionally, we can have some automatic, dynamic setting in the future based on snapshot size.

**Comment by fanminshi** [comment]
agree with @hongchaodeng  suggestions. we can have another field fo backup policy. if backup policy is not specified, then it is one time trigger.

**Comment by fanminshi** [comment]
suggest to add a new `backupPolicy` field:
```
spec:
  backupPolicy:
    maxBackups: 4
    backupIntervalInSecond: 30
  s3:
     path: "mybucket/mycluster_backup"
  ...
```

**Comment by xiang90** [comment]
@fanminshi 

yes. that is what i suggested here: https://github.com/coreos/etcd-operator/issues/1841#issuecomment-357119113

**Comment by rjtsdl** [comment]
@xiang90 @fanminshi update the proposal according to your suggestion.

**Comment by fanminshi** [comment]
@rjtsdl few things:

1. To disable periodical backup. we can simply not provide `backupPolicy` in the spec. Don't allow negative number for `maxBackups` and `backupIntervalInSecond` which doesn't make any sense. 

2. if maxBackups == 0, we probably shouldn't do any backup.

3. I am not sure about attaching `revision` to backup. it is possible that two backup have same revision. In that case, do the newer one overrides the old one or not overriding backup at all. The issue with backup with same revision is that its content might not be the same. a backup can have  a rev == 100 but compacted at rev == 50 and another backup has rev == 100 with no compaction. Hence, two backups with same revision might not have the same contents. I think it is simpler just attach time to backup`mybucket/mycluster_backup_{date}`. However, This suggestion is up to debate.

cc/ @xiang90 @hongchaodeng

**Comment by hongchaodeng** [comment]
> backupPolicy

Should be "periodic policy" or something like that.

> maxBackups == 0, we probably shouldn't do any backup.

Not do any backup should be specified by not giving "periodic policy".

> mybucket/mycluster_backup_{date}

A date is a better idea.
We also need to make sure backup etcd version is reflected in the backup. As a user, I could have one backup made 2h ago and one backup made 1h ago, the 1h ago one is of "v4" and 2h ago one of "v3". I am encountering issues with "v4" and that's why I am restoring data from backup. I would prefer to pick 2h ago one of "v3".

**Comment by rjtsdl** [comment]
@fanminshi based on https://github.com/coreos/etcd-operator/issues/1841#issuecomment-360318339

Made another round update on the proposal.

**Comment by hongchaodeng** [comment]
@rjtsdl 
Thanks! This looks good now. Would you like to submit a spec/api changes?

**Comment by fanminshi** [comment]
i added the `maxBackups == 0` into you proposal and everything looks good from myside.

**Comment by fanminshi** [comment]
@rjtsdl like what @hongchaodeng  said. the first pr should be spec change only.  modify https://github.com/coreos/etcd-operator/blob/master/pkg/apis/etcd/v1beta2/backup_types.go this file to include the new spec. once that is done. we can discuss the next step.

**Comment by rjtsdl** [comment]
@fanminshi  thx for the pointer

I will start probably later next week. :)

**Comment by xiang90** [comment]
@rjtsdl kindly ping on this one.

**Comment by rjtsdl** [comment]
@xiang90 , I am currently not having cycle anytime soon. If someone want to pick it up, I am totally good with it.

**Comment by fanminshi** [comment]
currently, there is a default backup timeout of 60s which is not configurable which can cause problem for slow machine that can't finish backup under 60s as seen in https://github.com/coreos/etcd-operator/issues/1903.

I also propose to include a configurable backup timeout in backupPolicy.

**Comment by chengliangli0918** [comment]
Do you have plan to support periodic backups in near future?
