### ISSUE TITLE
Specify the service account etcd cluster pods run under

### ISSUE THREAD

**Issue by mat285** [coreos/etcd-operator#1864]
Is there a way to specify the service account for etcd cluster pods? Right now my operator is failing to create the cluster because the seed member cannot mount the tls secrets.

```time="2018-01-18T00:42:02Z" level=error msg="cluster failed to setup: failed to create seed member (etcd-cluster-0000): pods "etcd-cluster-0000" is forbidden: volume with secret.secretName="etcd-peer-tls" is not allowed because service account default does not reference that secret" cluster-name=etcd-cluster pkg=cluster ```

**Comment by hongchaodeng** [comment]
Closing this to converge discussion on https://github.com/coreos/etcd-operator/issues/1866
