### ISSUE TITLE
kubectl drain node fails with: Unknown controller kind "EtcdCluster"

### ISSUE THREAD

**Issue by edulop91** [coreos/etcd-operator#1878]
Attempting to `kubectl drain  --delete-local-data --ignore-daemonsets --force <node>` fails with `error: Unknown controller kind "EtcdCluster": example-etcd-cluster-0000`

kubectl 1.8.6
kubernetes 1.8.6
etcd operator 0.8

I am not yet familiar with how kubectl is supposed to interact with CRDs, in this particular case EtcdCluster.  Is support for draining something that needs to be implemented etcd-operator side?

**Comment by hongchaodeng** [comment]
duplicate to https://github.com/coreos/etcd-operator/issues/1546.
Please check that issue.
