### ISSUE TITLE
What is it and can I use it for k8s 1.4?

### ISSUE THREAD

**Issue by UCSBGauchos** [coreos/etcd-operator#1890]
Hi,

I have 2 questions.

1. Is it something like an interface to control the etcd in k8s?

2. Can I use it in k8s 1.4?

**Comment by panamafrancis** [comment]
1. no, it does not interact with the Etcd cluster backing k8s
2. no, 1.4 is very old now and won't support custom resource definitions which came out in 1.7

**Comment by hongchaodeng** [comment]
Closing this.
Recommend starting with https://github.com/coreos/etcd-operator/blob/master/README.md
