### ISSUE TITLE
etcd-operator quits on SIGPIPE

### ISSUE THREAD

**Issue by akrennmair** [coreos/etcd-operator#1892]
I noticed that one of our `etcd-operator` instances restarted on one of our test systems, with the last log lines being the following:
```
time="2018-01-28T22:59:56Z" level=error msg="fail to poll pods: failed to list running pods: Get https://XXX.YYY.0.1:443/api/v1/namespaces/ZZZ/pods?labelSelector=app%3Detcd%2Cetcd_cluster%3Detcd-cluster: read tcp XXX.YYY.102.183:55266->XXX.YYY.0.1:443: read: connection reset by peer" cluster-name=etcd-cluster pkg=cluster 
time="2018-01-28T22:59:56Z" level=info msg="received signal: broken pipe"
```
In https://github.com/coreos/etcd-operator/blob/master/cmd/operator/main.go#L84 I noticed that `etcd-operator` handles all signals it receives by logging `received signal: %v` and calling `os.Exit(1)`. I see no reason why `etcd-operator` would do this, as `SIGPIPE` can be trivially recovered from if writes to file descriptors that error with `EPIPE` are handled accordingly. In this situation, the log suggests that the error was most likely caused by a transient error. Is there any reason to handle `SIGPIPE` the way it is being handled at the moment?

**Comment by hongchaodeng** [comment]
What are the component versions?
Do you know how to reproduce this with SIGPIPE? And talk about how you encountered this issue?

**Comment by akrennmair** [comment]
The `etcd-operator` version was 0.8.2, the `etcd` version was 3.2.15, all Kubernetes nodes are on version 1.8.1+coreos.0.

I haven't been able to reproduce the `SIGPIPE` issue. If there's any way to provoke transient networking issues within a Kubernetes cluster, that's what I would like to try, as I would guess from the log output posted above that the failure to query the API is somehow related to the `SIGPIPE` issue.

I encountered the issue on a test system where `etcd-operator` was running in its own namespace with 5 `etcd` pods spawned. This happened over the weekend, there was no load on `etcd` itself, and practically no load on the whole Kubernetes cluster.

**Comment by hongchaodeng** [comment]
We should ignore SIGPIPE.

ref: http://man7.org/linux/man-pages/man2/send.2.html
```
       EPIPE  The local end has been shut down on a connection oriented
              socket.  In this case, the process will also receive a SIGPIPE
              unless MSG_NOSIGNAL is set.
```

**Comment by hongchaodeng** [comment]
More golang handling of SIGPIPE on docs:
https://golang.org/pkg/os/signal/
