### ISSUE TITLE
backup: make backup timeout configurable 

### ISSUE THREAD

**Issue by fanminshi** [coreos/etcd-operator#1906]
Currently, etcd backup operator has a default non-configuration backup timeout of 60s. This can causing issue when retrieving and saving backup is more than 60s as seen in https://github.com/coreos/etcd-operator/issues/1903.

TODOs:
- [x] Define a new backup field to take in a backup timeout. https://github.com/coreos/etcd-operator/pull/1907
- [x] Implement backup timeout in etcd backup operator. https://github.com/coreos/etcd-operator/pull/1908
- [x] Add ctx to BackupWriter.Write() method. https://github.com/coreos/etcd-operator/pull/1910
- [x] Manual testing plan.

**Comment by xiang90** [comment]
sgtm
