### ISSUE TITLE
etcd-operator resources not cleaned up after failed start leaves nodes unable to drain

### ISSUE THREAD

**Issue by mcginne** [coreos/etcd-operator#1930]
We are trying to run etcd-operator in an environment that has a fairly high container density (~100 containers per node)
We find the etcd containers provisioned by etcd-operator can be slow to startup - which can cause the cluster to never reach quorum (Seems like first container gets killed by readiness probe before the 2nd one starts up - we are still investigating this issue).
When this occurs, we find the etcd cluster doesn't start up and we end up with zero pods.

When this occurs I find it can prevent nodes from draining other pods. I already found this issue https://github.com/coreos/etcd-operator/issues/1546 - but this is different as that one is about the inability to drain etcd-operator pods, but this issue is etcd-operator preventing the drain of other pods.

I have ensured there are no etcd-operator pods running on my node, then issue the drain, but it fails due to the `Unknown controller kind "EtcdCluster"` error:

```
$ kubectl drain 10.142.218.178 --force --timeout 420s --ignore-daemonsets --delete-local-data
node "10.142.218.178" already cordoned
error: Unknown controller kind "EtcdCluster": testetcd-400-th10-15-etcd-djbkf85nfm, testetcd-400-th2-9-etcd-7hrlc5zrwt, testetcd-400-th3-4-etcd-dk56phth9m, testetcd-400-th6-5-etcd-2jn2zsg6cn, testetcd-400-th9-14-etcd-w8m8h24kpt, testetcd-400-th9-16-etcd-twr5dthrdv
```

I checked and none of these pods actually exist anymore:
```
$ kubectl get pods --all-namespaces -o=wide | grep testetcd-400-th2-9-etcd-7hrlc5zrwt

$ kubectl get pods --all-namespaces -o=wide | grep testetcd-400-th2-9

$ kubectl get pods --all-namespaces -o=wide --show-all | grep testetcd-400-th2-9
etcd-operator     testetcd-400-th2-9-etcd-7hrlc5zrwt                             0/1       Completed           0          20h       <none>           10.142.218.178
etcd-operator     testetcd-400-th2-9-etcd-wqxlbr5s4v                             0/1       Completed           0          20h       <none>           10.143.115.218
```
A describe of the etcdcluster shows it in a strange state (This state hasn't changed in 24 hours, so it doesn't seem to be making any attempt to recover):

```
$ kubectl describe etcdcluster testetcd-400-th2-9-etcd -n etcd-operator
Name:         testetcd-400-th2-9-etcd
Namespace:    etcd-operator
Labels:       <none>
Annotations:  <none>
API Version:  etcd.database.coreos.com/v1beta2
Kind:         EtcdCluster
Metadata:
  Cluster Name:        
  Creation Timestamp:  2018-02-19T14:06:55Z
  Generation:          0
  Resource Version:    41290045
  Self Link:           /apis/etcd.database.coreos.com/v1beta2/namespaces/etcd-operator/etcdclusters/testetcd-400-th2-9-etcd
  UID:                 2481333c-157e-11e8-9348-067cd1b19087
Spec:
  TLS:
    Static:
      Member:
        Peer Secret:    testetcd-400-th2-9-etcd-peer-tls
        Server Secret:  testetcd-400-th2-9-etcd-server-tls
      Operator Secret:  testetcd-400-th2-9-etcd-client-tls
  Repository:           quay.io/coreos/etcd
  Size:                 3
  Version:              3.2.13
Status:
  Client Port:  2379
  Conditions:
    Last Transition Time:  2018-02-19T14:12:04Z
    Last Update Time:      2018-02-19T14:12:04Z
    Message:               Current cluster size: 1, desired cluster size: 3
    Reason:                Scaling up
    Status:                True
    Type:                  Scaling
  Current Version:         
  Members:
    Unready:
      testetcd-400-th2-9-etcd-wqxlbr5s4v
  Phase:           Running
  Service Name:    testetcd-400-th2-9-etcd-client
  Size:            2
  Target Version:  
Events:            <none>
```

If an etcdcluster failed to start I would expect it to attempt to try again, or at the very least clean up resources so they do not block the operation of the rest of the environment.

I am using Kube 1.8.6 and etcd-operator v0.8.3

**Comment by hongchaodeng** [comment]
To clean up resources, delete the etcdcluster cr. Would that work for you?

**Comment by mcginne** [comment]
Hi, yes deleting the etcdcluster cr does work, I was just hoping etcd-operator could handle this a bit better automatically. 
Do you think etcd-operator should attempt to restart if it never reaches quorum? (I guess this may be a different issue to this one)

**Comment by hongchaodeng** [comment]
I'm not sure what you meant "handle this a bit better automatically"? Please clarify.

Closing this issue since resolved.
