### ISSUE TITLE
Facing issue while installation of ETCD cluster on kuberenetes over GCP

### ISSUE THREAD

**Issue by anshultayal2009** [coreos/etcd-operator#1941]
I would need suggestion/help to sort out issue while installation of ETCD cluster on kuberenetes over GCP environment.

Below are the steps which I have done so far.
•	created etcd operator on kubernetes
•	set up basic RBAC rules for etcd operator
•	While creating etcd-cluster on kubernetes I am getting exception.

Exception :
#error: unable to recognize "example-etcd-cluster.yaml": no matches for etcd.database.coreos.com/, Kind=EtcdCluster
#Though yaml file is present at the particular location.

Moreover while going through etcd-operator logs  there is an exception regarding TPR initialization failed.
Exception :
time="2018-03-09T06:20:15Z" level=error msg="initialization failed: fail to create TPR: the server could not find the requested resource" pkg=controller
time="2018-03-09T06:20:15Z" level=info msg="retry in 30s..." pkg=controller
time="2018-03-09T06:20:45Z" level=error msg="initialization failed: fail to create TPR: the server could not find the requested resource" pkg=controller
time="2018-03-09T06:20:45Z" level=info msg="retry in 30s..." pkg=controller

Link Referred :
https://coreos.com/blog/introducing-the-etcd-operator.html
https://github.com/coreos/etcd-operator

Kubernetes version of master :
v1.8.7-gke.1

I would be happy to provide any further information if required.

Thanks in Advance !!

**Comment by hasbro17** [comment]
@anshultayal2009 Can you please specify the etcd-operator version that you are using. 
From the etcd-operator logs it seems you are using a very old version that uses Third Party Resources(TPR) instead of Custom Resource Definitions(CRD). The switch from TPR to CRD was made in [v0.5.0](https://github.com/coreos/etcd-operator/releases/tag/v0.5.0).

Can you try again with the latest v0.9.1 release.

**Comment by anshultayal2009** [comment]
Thanks @hasbro17 for the response,
Post applying new etcd-operator version, images was unstable and started to crash.
