### ISSUE TITLE
Etcd Restore no longer works, relies on image that's been deleted

### ISSUE THREAD

**Issue by azuretek** [coreos/etcd-operator#2006]
The restore operation is no longer working, the image it relies on seems to have been deleted.

https://github.com/coreos/etcd-operator/blob/a0523eca24f328c62dd52805f21d995b3efbef4d/pkg/util/k8sutil/k8sutil.go#L106

`tutum/curl` gives me a 404 on dockerhub.

https://hub.docker.com/r/tutum/curl/

**Comment by canhnt** [comment]
We can replace `tutum/curl` with another Docker image providing `curl` command, e.g. `appropriate/curl`

**Comment by azuretek** [comment]
Looks like it's no longer 404ing, so maybe it was an issue with dockerhub?
