### ISSUE TITLE
k8s.io/client-go branch

### ISSUE THREAD

**Issue by ice-tao** [coreos/etcd-operator#2038]
cmd/{operator,backup-operator,restore-operator}/main.go
mathod <leaderelection.RunOrDie> in <func main()> need two parameters when client-go branch in (master, release-10.0, release-9.0), branch <= 8.0 is OK.

Is some where remark it?

**Comment by hexfusion** [comment]
@ice-tao we are currently using kubernetes-1.11.4 deps internally which is 8.0.x I believe. I hope that helps.

https://github.com/coreos/etcd-operator/blob/cb35c2d35a3d1813f4df6028b6f11b0b8659b192/Gopkg.toml#L33-L36

**Comment by ice-tao** [comment]
@hexfusion maybe kubernetes version cause it, I use 1.13.0

**Comment by hexfusion** [comment]
> @hexfusion maybe kubernetes version cause it, I use 1.13.0

@ice-tao are you interested in looking into bumping these deps and see if it resolved your issue. I am curious then about the backwards compatibility, thanks.
