### ISSUE TITLE
ETCD rechability and health check

### ISSUE THREAD

**Issue by sanamsarath** [coreos/etcd-operator#2042]
I have ETCD running on a remote cluster. I need to keep track of the readability/liveliness of the ETCD cluster from the application side cluster. I have a proxy monitoring app between the ETCD and applications that  rely on ETCD.

Following are the 2 possibilities I could think of:

1. start a dummy watch request, and if the connection fails I will update the applications that the server is not reachable.  
2. Keep sending the dummy get requests with some time interval and if 3 get responses fail continuously , could assume the ETCD is not reachable.

What would be the best practice in general to keep track of the ETCD liveliness ??

Thanks.

**Comment by nvtkaszpir** [comment]
Your question better suits to repo coreose/etcd and not coreos/etcd-operator.
Also the simplest way would be to connect to the cluster and check /healthcheck or /metrics endpoints of each cluster node. Especially /metrics report if given node has leader.
Also please look at https://coreos.com/etcd/docs/latest/op-guide/grpc_proxy.html
