### ISSUE TITLE
etcd image in the CR Etcdcluster 

### ISSUE THREAD

**Issue by sanamsarath** [coreos/etcd-operator#2104]
can the etcd image that etcd-operator pulls during runtime be provided by the user??

In our company we have a restriction of pulling external images, so a copy of stable etcd docker image is saved in our internal repository with different name(our company specific standard name). Is there way that I can direct etcd-operator to pull our local image ??

I don't see any options other than size and version in CRD(EtcdCluster).

If this does't exist now, can this functionality be supported in future??

Thanks.

**Comment by nvtkaszpir** [comment]
This is possible, example below:
```apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: "etcd-custom"
  ## Adding this annotation make this cluster managed by clusterwide operators
  ## namespaced operators ignore it
  # annotations:
  #   etcd.database.coreos.com/scope: clusterwide
spec:
  size: 3
  repository: "quay.io/kaszpir/etcd"
  version: "3.2.13"
```

see https://github.com/coreos/etcd-operator/blob/master/pkg/apis/etcd/v1beta2/cluster.go#L80

**Comment by sanamsarath** [comment]
@nvtkaszpir Thanks.
