### ISSUE TITLE
Expose cluster dead status to user

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#215]
If we can't recover a cluster to run a quorum, we will mark the cluster as dead and remove all data we created in k8s: pods, services, etc.

However, there are two places we want to improve:
1. We still have the etcd cluster object in API Server. For this point, we should be careful during restore and shouldn't run anything for a dead cluster.
2. Communicate failure to user. Initially, we will write it to logs and it could be found via `kubectl logs kube-etcd-controller` .

We make this issue to keep track of records.

**Comment by hongchaodeng** [comment]
Closing this.
This belongs to broad topic of "status reporting".
We should create another issue or have a doc about it.

**Comment by xiang90** [comment]
> This belongs to broad topic of "status reporting".

Can you create an issue for it?
