### ISSUE TITLE
e2e flake: wrong id counter 

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#234]
From failure logs:

```
time="2016-10-15T04:56:51Z" level=info msg="Running members: test-etcd-cxtay-0000,test-etcd-cxtay-0001,test-etcd-cxtay-0002" 
time="2016-10-15T04:56:51Z" level=info msg="Expected membership: test-etcd-cxtay-0002,test-etcd-cxtay-0000,test-etcd-cxtay-0001" 
time="2016-10-15T04:56:51Z" level=error msg="fail to add new member (test-etcd-cxtay-0002): etcdserver: Peer URLs already exists" 
time="2016-10-15T04:56:51Z" level=info msg="Finish reconciling" 
time="2016-10-15T04:56:51Z" level=error msg="cluster (test-etcd-cxtay) fail to reconcile: etcdserver: Peer URLs already exists" 
```

**Comment by hongchaodeng** [comment]
I sort of get what's happening here.

Our assumption on id counter is that if a pod is created counter should increment. This wasn't always true previously because we have wait ready logic in CreateEtcdPod().

It seems fine now, but I will change the code to make it obvious.

**Comment by hongchaodeng** [comment]
Closing this right now since it's not a bug anymore

**Comment by xiang90** [comment]
> Our assumption on id counter is that if a pod is created counter should increment. This wasn't always true previously because we have wait ready logic in CreateEtcdPod().

Can you show me the previous code?

**Comment by hongchaodeng** [comment]
https://github.com/coreos/etcd-operator/blob/46dbc28ac988ff63cc236a1c41be20a3ea2f9109/pkg/util/k8sutil/k8sutil.go#L157-L168

**Comment by xiang90** [comment]
i see. thanks.
