### ISSUE TITLE
Controller crashes on poll PVC timeout

### ISSUE THREAD

**Issue by lachie83** [coreos/etcd-operator#342]
This issue in this case was that I was using the gce-pd PV provisioner on AWS which left the PVC in PENDING state
```
time="2016-11-04T22:59:02Z" level=error msg="fail to poll PVC (etcd-cluster-pvc): timed out waiting for the condition" 
panic: timed out waiting for the condition

goroutine 16 [running]:
panic(0x18dc520, 0xc420101660)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/coreos/etcd-operator/pkg/controller.(*Controller).Run.func2(0xc420258180, 0xc42039df20)
    /go/src/github.com/coreos/etcd-operator/pkg/controller/controller.go:143 +0x4e4
created by github.com/coreos/etcd-operator/pkg/controller.(*Controller).Run
    /go/src/github.com/coreos/etcd-operator/pkg/controller/controller.go:154 +0x2e9
```

**Comment by hongchaodeng** [comment]
For this issue, ideally we should have some way to reject user spec that doesn't match our environment. For example, we are running on AWS, and it's asking GCE stuff. However, there is no admission control for TPR objects yet. 

Nonetheless, such error shouldn't crash controller. As a fix for this, we will fail the cluster only, i.e. make the cluster die itself. Further, we will print the error and PVC status in logs, and in the future we could report via status.

**Comment by hongchaodeng** [comment]
@lachie83 
This bug should have been fixed by #344. We have inflight PR for test coverage.

Can you try again and verify no panics?
I have pushed to quay image. FYI, you can build your image following https://github.com/coreos/etcd-operator/blob/master/hack/release/README.md

**Comment by hongchaodeng** [comment]
@lachie83 
Can we close this?

**Comment by xiang90** [comment]
I think we can close it now. @lachie83 please reopen if you find the issue still exists.
