### ISSUE TITLE
remove backup from example-etcd-cluster

### ISSUE THREAD

**Issue by philips** [coreos/etcd-operator#350]
This doesn't work on minikube because the backup requires a PV.

```
kubectl create -f https://coreos.com/operators/etcd/latest/example-etcd-cluster.yaml
```

We need to fix `https://coreos.com/operators/etcd/latest/example-etcd-cluster.yaml` as well cc @spoonben

**Comment by philips** [comment]
error:

```
time="2016-11-07T02:36:20Z" level=error msg="cluster (etcd-cluster) is dead due to failure to create backup: fail to wait PVC (etcd-cluster-pvc) 'Bound': timed out waiting for the condition"
```

**Comment by xiang90** [comment]
@hongchaodeng Yes. Probably we should disable backup in the example by default, since most people will try this on local env. We need to update README section: if you want to try backup example, do xxx.

**Comment by hongchaodeng** [comment]
In the future we might consider "local" persistent volume: 
https://github.com/kubernetes/kubernetes/issues/7562

**Comment by xiang90** [comment]
@hongchaodeng Yes. Seems promising.

**Comment by philips** [comment]
Yes, that is nice for the future, but right now it is confusing as things don't work.
