### ISSUE TITLE
Pass in backup storage provider, instead of creating it

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#356]
What's storage provider? It's something that would gave us some storage if we requested.

What?
Currently we automatically creates the storage provider inside operator, specifically in [CreateStorageClass()](https://github.com/coreos/etcd-operator/blob/48f7aa5e585718c9cfa1afbca428c02a7392aa2e/pkg/controller/controller.go#L215).

We should change to that we pass in a storage provider, and create a claim on that.

Why?
From cluster operation perspective, usually k8s admin will setup default storage provider: storage classes for dynamic provisioning, object stores. This is the pattern in k8s. If somebody wants to use etcd operator, he knows where to store backup data into, whether it's EBS or S3, and then passes in the storage provider which he has privileges of. etcd operator will be able to use that.

This will not only simplify our model of backup storage path, but also provide better security/auth for that.
`------------`

## Conclusion

We will keep our current solution as it's easy and cloud based for new users. We will add fields to backup spec in the future if there are user requests to satisfy different storage needs.

**Comment by harryge00** [comment]
What if the cluster does not support storage class? Such like old version kubernetes.

**Comment by hongchaodeng** [comment]
@harryge00 
What's your use case? Can you clarify more detailedly?

**Comment by harryge00** [comment]
log:
```
time="2016-11-30T06:51:21Z" level=info msg="retry in 30s..." pkg=controller 
time="2016-11-30T06:51:51Z" level=info msg="finding existing clusters..." pkg=controller 
time="2016-11-30T06:51:51Z" level=error msg="initialization failed: fail to create storage class: the server could not find the requested resource" pkg=controller 
time="2016-11-30T06:51:51Z" level=info msg="retry in 30s..." pkg=controller 
time="2016-11-30T06:52:21Z" level=info msg="finding existing clusters..." pkg=controller 
time="2016-11-30T06:52:21Z" level=error msg="initialization failed: fail to create storage class: the server could not find the requested resource" pkg=controller
```

kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.3+v0.10.0", GitCommit:"058003537e9cdbd13580b2cd72184c0526fd8025", GitTreeState:"clean", BuildDate:"2016-08-30T11:54:27Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.3+v0.10.1", GitCommit:"56a9d3556cca836041533bf033b14099a5ca31b1", GitTreeState:"clean", BuildDate:"2016-09-26T14:51:14Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```
I think it is because our cluster does not support storage class.

**Comment by xiang90** [comment]
@harryge00 

We have a requirement on k8s version: see https://github.com/coreos/etcd-operator#requirements.

**Comment by hongchaodeng** [comment]
@harryge00 
This is unrelated here. Please do not continue on this issue.
I think your question has been answered. Next time please consider opening a new issue.

**Comment by xiang90** [comment]
@hongchaodeng Based on our offline discussion, we will still keep today's simple cloud based solution for creating one storage pool for all clusters.

We will add a storage class field for cluster.spec.bacup.spec in the future if there is a request.

Can you update this issue (or create a new one) to reflect that? 

Thank you.

**Comment by hongchaodeng** [comment]
Updated.

I'm closing this issue and creating another one to better keep track of it.

**Comment by hongchaodeng** [comment]
track: https://github.com/coreos/etcd-operator/issues/691
