### ISSUE TITLE
Build our own small util instead of using external dep

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#375]
Currently we are using some util functions like `wait.Poll(...)`.
Those are small functions. But using external dependency would cause more problem to us over time (e.g. updating dependency).
We should probably build our own util functions.

**Comment by xiang90** [comment]
or we can copy them into our codebase :)

**Comment by xiang90** [comment]
Is this already resolved?

**Comment by hongchaodeng** [comment]
Yes. Closing.
