### ISSUE TITLE
jenkins: Can't access GCE node internal IP from pod

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#385]
Our migration tests on jenkins are now failing consistently. Digging into the problem, it seems that k8s pod couldn't access IP of nodes.

In migration test, we use GetDefaultHost(), which returns internal IP "10.240.0.x". Then we use it as network interface that etcd binds to. But etcd operator was trying to do migrate, it failed:
```
grpc: time out when dialing
```

I test it by running an etcd server locally:
```
etcd --listen-peer-urls 'http://10.240.0.7:12380' --listen-client-urls 'http://10.240.0.7:12379' --initial-advertise-peer-urls http://10.240.0.7:12380 --advertise-client-urls http://10.240.0.7:12379 --initial-cluster 'boot=http://10.240.0.7:12380' --name boot
```

Then create a pod to contact it:
```
kubectl run --rm -i --tty fun --image quay.io/coreos/etcd --restart=Never -- /bin/sh
/ # ETCDCTL_API=3 etcdctl --endpoints http://10.240.0.7:12379 get foo
Error:  grpc: timed out when dialing
```
It also turns out to be inaccessible.

**Comment by hongchaodeng** [comment]
@xiang90 
I rethink about the network assumptions made in e2e test, and come up with ideas to get rid of those assumptions to make test simpler and more generic.

## 1. migrate boot member

It requires an IP address that's accessible from within k8s cluster. Other than that, we don't really care where it's running, as long as it's an etcd server and will get migrated successfully.

Why don't we just create a pod for it? Conceptually, it's just another service that we can access matching exactly what we did now.

## 2. make backup 

In disaster recovery test, we don't need to assume service IP is accessible on test machine as in: https://github.com/coreos/etcd-operator/blob/50c140012bc4a24342bf49b76e0c58d223fc7db4/test/e2e/util.go#L59-L62

Because we are already using the http client inside kube client, we can actually use it to access the known backup service directly.

**Comment by xiang90** [comment]
The proposal wont solve all problems I am afraid.

Yes, we can run the boot member in pod, but not the actual self-hosted members. We do want to test self-hosted features which should run on host network.

I do not want to make stuff complicated now. I think we can:

1. run jenkins jobs sequentially
2. do not run anything other than CI on jenkins slaves

For 2, yea, it does not really matters.

> Digging into the problem, it seems that k8s pod couldn't access IP of nodes.

Do we know why? It should be able to access.

**Comment by hongchaodeng** [comment]
> Do we know why? It should be able to access.

No idea. It was still OK yesterday.

**Comment by hongchaodeng** [comment]
> Yes, we can run the boot member in pod, but not the actual self-hosted members.

It's just boot member. So you agree on this too?

**Comment by xiang90** [comment]
> No idea. It was still OK yesterday.

We should figure this out.

> It's just boot member. So you agree on this too?

I mean we can. But why we need to?

**Comment by hongchaodeng** [comment]
We need to fix the test.
Currently it's failing all the time.
Changing it to pod will also make it simpler and more generic, e.g. we don't need to set up kubelet/proxy on test machine anymore.

**Comment by xiang90** [comment]
> Changing it to pod will also make it simpler and more generic, e.g. we don't need to set up kubelet/proxy on test machine anymore.

I do not understand. Right now, we start etcd boot member on local network. It does not rely on k8s network. I do not think it has anything to do with kubelet/proxy.

Also I do not understand why it is simper and more generic.

**Comment by xiang90** [comment]
> We need to fix the test.
Currently it's failing all the time.

How will move the boot member into pod fix the problem? We need to fix this:
pod should be able to access node ip

**Comment by hongchaodeng** [comment]
We start an pod as a single etcd server.
We take it as boot member, and get uses its Pod IP to form bootMemberClientEndpoint.

**Comment by hongchaodeng** [comment]
> I do not understand. Right now, we start etcd boot member on local network. It does not rely on k8s network. I do not think it has anything to do with kubelet/proxy.

It needs proxy because it needs to talk to migrated cluster before being removed off membership.
It's simpler because e2e test infra doesn't need to assume test machine needs to setup kubelet/proxy anymore.

**Comment by xiang90** [comment]
> We start an pod as a single etcd server.
We take it as boot member, and get uses its Pod IP to form bootMemberClientEndpoint.

Why do we need to do this? What exactly problem can this solve?

**Comment by xiang90** [comment]
> It needs proxy because it needs to talk to migrated cluster before being removed off membership.

No, it does not need. migrated member is on host network.

**Comment by hongchaodeng** [comment]
> Why do we need to do this? What exactly problem can this solve?
master is failing now.
The failure is caused by network issue talking to test machine IP.

**Comment by xiang90** [comment]
> The failure is caused by network issue talking to test machine IP.

Right. Fix this.

**Comment by hongchaodeng** [comment]
All right.
I have fixed it.
It's firewall issue. Not sure why it works before though.

**Comment by xiang90** [comment]
Can we close this issue then?

**Comment by hongchaodeng** [comment]
Verified it's fixed.

**Comment by hongchaodeng** [comment]
The second point (make backup) isn't true
