### ISSUE TITLE
Why not Petsets?

### ISSUE THREAD

**Issue by dhilipkumars** [coreos/etcd-operator#404]
Hi ,

First of all awesome project and great idea. 

I was browsing through this project and found that `etcd-operator` is built on top of `POD` primitives is there any reasoning why you choose PODs instead PetSet? 

On the other-hand `prometheus-operator` appears to be built on top of `PetSet`.   

What was the reason behind these decisions ? ie to choose Pods for etcd and PetSet for Prometheus.

Regards,
Dhilip

**Comment by hongchaodeng** [comment]
Curious what's your use case?

**Comment by xiang90** [comment]
@dhilipkumars We use POD for better control over everything. Yea, but from users' perspective, why do you need to care? Any specific use case in mind?

**Comment by dhilipkumars** [comment]
@xian90 and @hongchaodeng, sure we like the idea of operators we are starting to write one for a stateful workload, we are now in a dilemma weather or not to use PETSET as the underlying primitive.  Wanted to check if your team went through similar thought process ?

**Comment by xiang90** [comment]
@dhilipkumars I believe Kuberentes community is a better place for this discussion. There is a slack channel http://slack.k8s.io/. Let's talk there.

**Comment by dhilipkumars** [comment]
@xiang90 Sure, i was thinking a Rationale section on docs on why was POD chosen as the underlying primitive for etcd-operator would help the readers.

**Comment by philips** [comment]
From the Operators blog post: https://coreos.com/blog/introducing-operators.html

> Q: How is this different than StatefulSets (previously PetSets)?

> A: StatefulSets are designed to enable support in Kubernetes for applications that require the cluster to give them "stateful resources" like static IPs and storage. Applications that need this more stateful deployment model still need Operator automation to alert and act on failure, backup, or reconfigure. So, an Operator for applications needing these deployment properties could use StatefulSets instead of leveraging ReplicaSets or Deployments

From my HN comment: https://news.ycombinator.com/item?id=13225359

> Great to see! StatefulSet's are an example of how Kubernetes is enabling applications of all types to run on cluster. This doesn't mean the user can't take zero action to port to Kubernetes, the application needs to be running in a container of course, but it is proof that an application doesn't need to be "12 Factor" to run on Kubernetes.
Essentially I see the world broken down into four potential application types:
> 1) Stateless applications: trivial to scale at a click of a button with no coordination. These can take advantage of Kubernetes deployments directly and work great behind Kubernetes Services or Ingress Services.
> 2) Stateful applications: postgres, mysql, etc which generally exist as single processes and persist to disks. These systems generally should be pinned to a single machine and use a single Kubernetes persistent disk. These systems can be served by static configuration of pods, persistent disks, etc or utilize StatefulSets.
> 2) Static distributed applications: zookeeper, cassandra, etc which are hard to reconfigure at runtime but do replicate data around for data safety. These systems have configuration files that are hard to update consistently and are well-served by StatefulSets.
> 3) Clustered applications: etcd, redis, prometheus, vitess, rethinkdb, etc are built for dynamic reconfiguration and modern infrastructure where things are often changing. They have APIs to reconfigure members in the cluster and just need glue to be operated natively seemlessly on Kubernetes, and thus the Kubernetes Operator concept https://coreos.com/blog/introducing-operators.html
> You can see more from about Operators in my short KubeCon keynote here: https://youtu.be/Uf7PiHXqmnw?t=11
> Overall, great progress in Kubernetes v1.5! Great to see critical features moving from Alpha to Beta.

**Comment by dhilipkumars** [comment]
Thanks, if someone writes a new operator.  Where do we contribute it right now? coreos or kubernetes?
