### ISSUE TITLE
where is the cluster data stored?

### ISSUE THREAD

**Issue by philips** [coreos/etcd-operator#428]
How do I force recreation of a cluster if I want to? The Operator seems to store metadata about existing clusters somewhere but I don't know where. 

xref #387

**Comment by xiang90** [comment]
All the metadata are stored in TRP etcd-cluster resources.

> How do I force recreation of a cluster if I want to?

What do you mean by cluster recreation? Can you give an example?

**Comment by hongchaodeng** [comment]
@philips What's the question? Can you clarify?
