### ISSUE TITLE
Etcdctl not working with exposed etcd-operator

### ISSUE THREAD

**Issue by odacremolbap** [coreos/etcd-operator#434]
I'm facing an issue exposing etcd-operator using nodeport.

**kubernetes version:** 1.4.6
**etcd-operator version:** quay.io/coreos/etcd-operator:latest
**etcd version:** v3.1.0-alpha.1 
**etcdctl version:** 2.3.7

## Description

The service is defined like[ this one](https://github.com/coreos/etcd-operator/blob/master/example/example-etcd-cluster-nodeport-service.json)

The problem is that I can't use etcdctl from outside the custer. It seems that for any sub-command etcdctl lists all members in the cluster and contacts them one by one.

In the etcd-operator case, it tries to resolve internal pods from external dns systems, which will most probably fail.

## Example

Using the internal clusterIP exposed endpoint, etcdctl succeeds
```
# ./etcdctl --debug --endpoints=http://testoperator-exposed:2379 cluster-health
Cluster-Endpoints: http://testoperator-exposed:2379
cURL Command: curl -X GET http://testoperator-exposed:2379/v2/members
member 954f8f7bc5f80cb is healthy: got healthy result from http://testoperator-0002:2379
member 5b41f4ad2e5d18ea is healthy: got healthy result from http://testoperator-0000:2379
member a43d9958dcee1286 is healthy: got healthy result from http://testoperator-0001:2379
member db79e0a98fe2b2ec is healthy: got healthy result from http://testoperator-0003:2379
cluster is healthy
```

From outside the cluster (no firewalls involved) etcdctl it fails
```
$ etcdctl --debug --endpoints=http://localhost:32379 get /test      
start to sync cluster using endpoints(http://localhost:32379)
cURL Command: curl -X GET http://localhost:32379/v2/members
got endpoints(http://testoperator-0000:2379,http://testoperator-0001:2379,http://testoperator-0002:2379,http://testoperator-0003:2379) after sync
Cluster-Endpoints: http://testoperator-0000:2379, http://testoperator-0001:2379, http://testoperator-0002:2379, http://testoperator-0003:2379
cURL Command: curl -X GET http://testoperator-0000:2379/v2/keys/test?quorum=false&recursive=false&sorted=false
cURL Command: curl -X GET http://testoperator-0001:2379/v2/keys/test?quorum=false&recursive=false&sorted=false
cURL Command: curl -X GET http://testoperator-0002:2379/v2/keys/test?quorum=false&recursive=false&sorted=false
cURL Command: curl -X GET http://testoperator-0003:2379/v2/keys/test?quorum=false&recursive=false&sorted=false
Error:  client: etcd cluster is unavailable or misconfigured
error #0: dial tcp: lookup testoperator-0000: no such host
error #1: dial tcp: lookup testoperator-0001: no such host
error #2: dial tcp: lookup testoperator-0002: no such host
error #3: dial tcp: lookup testoperator-0003: no such host
```

same as before, but using the API
```
$ curl http://127.0.0.1:32379/v2/keys/test 
{"action":"get","node":{"key":"/test","value":"my test","modifiedIndex":10,"createdIndex":10}}
```

## Observ

I don't think there is nothing wrong with etcd-operator, maybe there should be an option at etcdctl to avoid contacting all clusters, or there should be a warning at the docs that warns people from using etcdctl with an exposed etcd-operator.

**Comment by xiang90** [comment]
> I don't think there is nothing wrong with etcd-operator, maybe there should be an option at etcdctl to avoid contacting all clusters, or there should be a warning at the docs that warns people from using etcdctl with an exposed etcd-operator.

With v2, can you specify --no-sync. etcdctl v3 will not do auto membership sync. This operator is designed for etcd3 only in theory.

Try

```bash
ETCDCTL_API=3 ./etcdctl --endpoints=xxx get key
```

**Comment by xiang90** [comment]
@odacremolbap It would be great if you can contribute to the doc about how to access the etcd cluster created by the operator.
