### ISSUE TITLE
Developer Guide

### ISSUE THREAD

**Issue by dhilipkumars** [coreos/etcd-operator#456]
Hi 

Is there a developer guide / build instructions for this project? What is the dependency manager being used? `godeps` ? Im unable to compile the operator with latest `K8s` sources as package unversioned appears to be deprecated.  

Also is the minimum requirement `go 1.7`? could we use below package for backward compatibility?

```
"golang.org/x/net/context"
```

Thanks in Advance,
Dhilip

**Comment by dhilipkumars** [comment]
If i `git checkout` to 1.4 branch for both `k8s.io/kubernetes` and `k8s.io/client-go` dependencies then `go build` works.

**Comment by hongchaodeng** [comment]
See https://github.com/coreos/etcd-operator/tree/master/hack/release.

We will have more formal dev docs soon. @dhilipkumars  Would you like to write one?

**Comment by dhilipkumars** [comment]
@hongchaodeng thanks, ooops have never used glide. :-) did not thing it was the dependency file. 

Sure I will give it a try, do you have any reference `dev doc` in mind from coreos that i should follow for this project?

**Comment by hongchaodeng** [comment]
In most cases we have a section in README talk about how to build the
project.
However, our README has been long enough. We should have a separate docs --
I would say, "docs/devel/development.md".

**Comment by xiang90** [comment]
@dhilipkumars We do not have an official dev doc template as far as I know.

I would image we can start something similar to  https://github.com/coreos/etcd/blob/master/Documentation/dl_build.md#build-the-latest-version, but developer facing to start with.

To test the build on devs local machine, they have to package the binary to a container, setup kuberntetes, run e2e etc.. But we can sort this out later.

**Comment by hongchaodeng** [comment]
fixed via #678
