### ISSUE TITLE
try minio-go client for s3 API

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd-operator#495]
Minio-go client makes it easier for etcd operator to talk with almost ANY s3 compatible APIs.

https://github.com/minio/minio-go

/cc @brianredbeard

**Comment by klizhentas** [comment]
I've spent some time digging the code and here are some things to consider:

* The benefit of your current S3 client is that it can use IAM and STS credentials and rotate them as needed:

https://github.com/aws/aws-sdk-go/blob/master/aws/credentials/ec2rolecreds/ec2_role_provider.go#L52

I could guess that many users would prefer this choice compared to static credentials here.

So I would recommend enabling the credential chain that can try to use IAM instance credentials in addition to static credentials.

If we move to Minio we could loose that nice feature with rotation and renewal

* After digging a bit in the code, I could not understand the purpose of mounting the config here:

https://github.com/coreos/etcd-operator/blob/45c1c96bcc414729c0bcb26a14d6ee3f2e949c74/pkg/util/k8sutil/backup.go#L154

I could not find any references to it in the Go AWS SDK, why do we mount it?

* If we enable minio client it will look somewhat like this:

https://github.com/gravitational/stolon/blob/master/pkg/store/s3.go

Now, it would be nice to support IAM/STS auto credentials for backups and also it would be nice to support minio clients for local/onprem backups.

As a possibility, we can feature two options:

* S3 that can use static credentials and can support IAM/STS credentials using native client
* S3-compat that uses static credentials and also accepts the endpoint for backups as a backup parameter

Let me know what do you think.

**Comment by hongchaodeng** [comment]
> So I would recommend enabling the credential chain that can try to use IAM instance credentials in addition to static credentials.

How to use the credential chain? Can you explain more about credential chain? References?

> I could not find any references to it in the Go AWS SDK, why do we mount it?

It's mounted to backup pod, the backup pod will use it.
See https://github.com/coreos/etcd-operator/blob/master/pkg/backup/backup.go#L78

> Now, it would be nice to support IAM/STS auto credentials for backups and also it would be nice to support minio clients for local/onprem backups.

I agree with more dynamic, rotating support of credentials. That's a good direction we will head towards

**Comment by klizhentas** [comment]
> How to use the credential chain? Can you explain more about credential chain? References?

https://github.com/aws/aws-sdk-go/blob/master/aws/credentials/chain_provider.go#L42

> It's mounted to backup pod, the backup pod will use it.

Right, you are using shared provider and you mount both `.credentials` and `.config` My question is about config, as I don't see it being used anywhere in static provider, only credentials:

https://github.com/aws/aws-sdk-go/blob/master/aws/credentials/shared_credentials_provider.go#L26

So I'm wondering what's the purpose of mounting config.

> I agree with more dynamic, rotating support of credentials. That's a good direction we will head towards

In this case we could either adopt minio to work with the `aws` credentials, or roll minio as a separate thing.

**Comment by hongchaodeng** [comment]
> In this case we could either adopt minio to work with the aws credentials, or roll minio as a separate thing.

Let me figure out how it rotates credentials first.

> So I'm wondering what's the purpose of mounting config.

We need config for aws, e.g. zone.

**Comment by klizhentas** [comment]
> We need config for aws, e.g. zone.

That's the thing - I could not find a place where this config is being used anywhere in the go-aws code, do you know what it's being used for?

**Comment by hongchaodeng** [comment]
> That's the thing - I could not find a place where this config is being used anywhere in the go-aws code, do you know what it's being used for?

If it's about where in aws-go codebase, I have looked into it before. But I don't recall the details. Why do you want look into the code details?

In the docs: http://docs.aws.amazon.com/sdk-for-go/api/aws/session/

> If the AWS_SDK_LOAD_CONFIG environment variable is set to a truthy value the Session will be created from the configuration values from the shared config (~/.aws/config)

And we have used `SharedConfigEnable` which will override env var `AWS_SDK_LOAD_CONFIG`

**Comment by klizhentas** [comment]
found it, thanks. So it looks like it is one more thing to consider when using Minio - it needs explicit region as a parameter while AWS client loads it from .config file. 

This means we'll have to parse ini file or specify it explicitly otherwise

**Comment by xiang90** [comment]
this is fixed by https://github.com/coreos/etcd-operator/pull/1855.
