### ISSUE TITLE
switch to kubernetes/client-go

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd-operator#496]
do not depend on full k8s repo

**Comment by hongchaodeng** [comment]
I have finished the change. Since it's a huge change, I'm going through two testing plans:
- Run with jenkins for 20 times
- soak-testing with one cluster for a while

**Comment by xiang90** [comment]
thanks for keeping us posted.

**Comment by xiang90** [comment]
@hongchaodeng Shall we close this out?

**Comment by hongchaodeng** [comment]
Leader election code isn't imported yet.

**Comment by hongchaodeng** [comment]
I will submit a PR to upstream to import leader election code for client-go 1.5 branch.

**Comment by xiang90** [comment]
Fixed.
