### ISSUE TITLE
A new cluster could be affected by previous garbage pod

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#500]
There could be leftover garbage pods created by the cluster of same name previously. 
For example:
- cluster "A" is deleted, but we have "oldpod-A" belongs to "A" failed to be deleted.
- then create cluster "A" again. It will create seed member "seedpod-A".
- In reconcile logic, it will put both "oldpod-A" and "seedpod-A" as endpoints of etcd client to do member list. However, They are two different groups of etcd cluster. And if it picks the old one, it will use it and then all the old data will be there :(

**Comment by hongchaodeng** [comment]
@xiang90 

We should use OwnerReference field to create and check etcd pods.

**Comment by xiang90** [comment]
@hongchaodeng is this fixed by https://github.com/coreos/etcd-operator/pull/571?

**Comment by hongchaodeng** [comment]
Yes. closing.
