### ISSUE TITLE
regression on k8s v1.5.1

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#501]
Today I upgraded cluster to v1.5.1 and master e2e test failed:

https://jenkins-etcd-public.prod.coreos.systems/job/etcd-operator-master/173/console

**Comment by hongchaodeng** [comment]
logs:
```
20:22:48 --- FAIL: TestCreateSelfHostedClusterWithBootMember (120.45s)
20:22:48 	self_hosted_test.go:80: etcdserver is ready
20:22:48 	self_hosted_test.go:112: failed to create 3 members etcd cluster: timed out waiting for the condition
...
20:20:48 --- FAIL: TestCreateSelfHostedCluster (240.03s)
20:20:48 	self_hosted_test.go:48: failed to create 3 members self-hosted etcd cluster: timed out waiting for the condition
```

**Comment by hongchaodeng** [comment]
Seems like defaulting has regression:
```
20:20:48 time="2016-12-22T20:20:30Z" level=error msg="fail to reconcile: Pod \"test-etcd-3x3vp-0044\" is invalid: spec.initContainers[0].env[0].valueFrom.fieldRef.apiVersion: Required value" cluster-name=test-etcd-3x3vp pkg=cluster 
```

**Comment by hongchaodeng** [comment]
Another problem, namespace getting stuck:
![screen shot 2016-12-22 at 3 00 17 pm](https://cloud.githubusercontent.com/assets/920884/21443123/8888177a-c857-11e6-93ca-3803286a2a37.png)

**Comment by hongchaodeng** [comment]
jenkins cluster downgraded to 1.4.7

**Comment by hongchaodeng** [comment]
Defaulting issue tracked on upstream: https://github.com/kubernetes/kubernetes/issues/39189

**Comment by hongchaodeng** [comment]
Just tried on latest master. Another issue:
```
$ k logs -f etcd-operator                
E0104 03:16:45.980462       5 leaderelection.go:252] error retrieving endpoint: the server does not allow access to the requested resource (get endpoints etcd-operator)
...
```

**Comment by hongchaodeng** [comment]
another regression on GC unable to recognize kind in REST mapping: https://github.com/kubernetes/kubernetes/issues/39816

**Comment by xiang90** [comment]
@hongchaodeng Are these all "resolved" on upstream?

**Comment by xiang90** [comment]
If all of them are tracked on upstream, and we have work around in our code, we suggest to close this umbrella issue.

**Comment by hongchaodeng** [comment]
Right.
- defaulting has been worked around
- GC is worked around on upstream
- RBAC is tracked on another issue
