### ISSUE TITLE
tls: static configuration

### ISSUE THREAD

**Issue by philips** [coreos/etcd-operator#504]
https://github.com/coreos/etcd-operator/pull/218 describes a dynamic etcd TLS setup.

I think we should support a static configuration. Essentially a user would provide the TLS certificates in the etcd-cluster object and the secrets would be provided via a secret.

This would mean that all cluster members would use the same secret but I think it is an acceptable stop-gap to enable people to launch TLS secured clusters.

**Comment by hongchaodeng** [comment]
Is this duplicate to #409?

**Comment by hongchaodeng** [comment]
closed as dup to https://github.com/coreos/etcd-operator/issues/409
