### ISSUE TITLE
etcd cluster TPR's relation with the resources (pods, svcs) it manages

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#517]
Currently a cluster has the following relations with the pods/svcs it manages:
- an etcd pod will have label{"etcd_cluster": $cluster_name, "app":"etcd"}
- an etcd service will have label{"etcd_cluster": $cluster_name}
- they have some naming conventions making them unique to one cluster

Recently we are working on GC and this would make it more necessary for us to have clear definition how to correlate them.

A problem with previous relation graph is that we could have same name cluster created again. For example, cluster "A" was created and then deleted. Then "A" was created again. We want to differentiate them as two. EtcdCluster TPR object's UID would be ideal to differentiate and we could make use of OwnerReference field in pod/svc to construct relation with stronger guarantee.

Another option is to use resource version. For example, all pod/svc that has smaller resource version won't belong to a cluster. However, this is having assumptions on versions.

**Comment by hongchaodeng** [comment]
@xiang90 

ListOptions doesn't have a way to List by OwnerRef currently.

**Comment by xiang90** [comment]
>  EtcdCluster TPR object's UID would be ideal to differentiate and we could make use of OwnerReference field in pod/svc to construct relation with stronger guarantee.

Can we easily select `cluster=X && owner.ref.ID!=currentTPR.ID`? If yes, probably owner ref is a better approach.

**Comment by xiang90** [comment]
@hongchaodeng 

So we need to select all pods with `cluster=X`, and then scan over them to find all pods with refID!=currentID?

**Comment by hongchaodeng** [comment]
@xiang90 
I feel like this is a field selector thing.
My understanding is that this isn't supported in field selector yet. In fact, a lot of fields couldn't..

**Comment by xiang90** [comment]
@hongchaodeng 

OK. Probably we should just go with refID and hope we can select in the future? It is a little bit more work than just use resource version, but it followers k8s api design. And we have a hope to directly select the bad items in the future. So I now go towards ref id approach.
