### ISSUE TITLE
Designing garbage collector

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#518]
GC issues:
- https://github.com/coreos/etcd-operator/issues/290
- https://github.com/coreos/etcd-operator/issues/464
- https://github.com/coreos/etcd-operator/issues/500

Object ownership: https://github.com/coreos/etcd-operator/issues/517

We need a garbage collector to remove pods/services that etcd cluster failed to delete.

Two strategies:
- lazy GC: When creating a cluster , remove all potential previous garbage. When deleting a cluster, remove all potential garbage (see https://github.com/coreos/etcd-operator/pull/507#discussion_r93810299)
- periodic full GC (every 10minutes or so): find out all pods/svcs that are parentless -- that doesn't have a managing cluster. For efficiency concern, we can do some caching.

**Comment by xiang90** [comment]
> periodic full GC (every 10minutes or so): 

let's just do full scanning initially. we can optimize it later on.

**Comment by xiang90** [comment]
I am less concerned on the full GC case. A normal operator would manage ~O(10) etcd clusters. The totally selected items with (app=etcd) is at most ~O(100). Finding the orphan items is trivial. 

there are already other places we do full select. we should optimize all by using reflector for example.

**Comment by xiang90** [comment]
Can you create a design doc talking about how:

1. we do ownership tracking
2. what is our GC initial strategy and why

**Comment by hongchaodeng** [comment]
@xiang90 
Sure

**Comment by hongchaodeng** [comment]
closed by #519
