### ISSUE TITLE
e2e flake: fail to wait pods deleted: still failing after 5 retries

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#607]

**Comment by hongchaodeng** [comment]
https://jenkins-etcd.prod.coreos.systems/job/etcd-operator-master/229/console

At the end:

e2e logs:
```
util.go:245: waiting pod (test-etcd-e4s09-0000) to be deleted.
restore_test.go:121: fail to wait pods deleted: still failing after 5 retries
```

operator logs:
```
2017-01-06T04:46:51Z" level=info msg="deleted pod (test-etcd-e4s09-0000)
```

**Comment by hongchaodeng** [comment]
From logs, operator have created and then deleted cluster and its resources.

**Comment by hongchaodeng** [comment]
One cause is that the DELETE operation reflects too slow (25s) on APIServer even though on operator side delete() returns.

**Comment by hongchaodeng** [comment]
This happened again: https://jenkins-etcd-public.prod.coreos.systems/job/etcd-operator/1130/console

Seems like an annoying issue.

Again
```
util.go:254: waiting pod (test-etcd-h9182-0000) to be deleted.
```

Operator deletes it:
```
time="2017-01-06T05:20:16Z" level=info msg="deleting cluster" cluster-name=test-etcd-h9182 pkg=cluster
time="2017-01-06T05:20:16Z" level=info msg="deleted pod (test-etcd-h9182-0000)" pkg=gc 
```

**Comment by xiang90** [comment]
If this is easy to reproduce, let's try to make the waiting longer to see if this can go away.

**Comment by xiang90** [comment]
We do not really control the API server, so if the slowness is caused by api server there is nothing we can do.

**Comment by hongchaodeng** [comment]
tracked at https://jenkins-etcd.prod.coreos.systems/job/etcd-operator-flaketest/

**Comment by hongchaodeng** [comment]
This still happen:
```
13:14:21         	util.go:246: waiting pod (test-etcd-wds6b-0000) to be deleted.
13:14:21         	util.go:253: pod (test-etcd-wds6b-0000) status.phase is (Running): init container status:
13:14:21         		fetch-backup: Terminated: message () reason (Completed)
13:14:21         		restore-datadir: Terminated: message () reason (Completed)
13:14:21         		container status:
13:14:21         	restore_test.go:121: fail to wait pods deleted: still failing after 10 retries
13:14:21 2017-01-06 13:13:26.027460 I | embed: listening for peers on http://10.240.0.10:12380
```

**Comment by hongchaodeng** [comment]
Conclusion on this issue:
- apiserver should immediately delete with grace period 0
- but we can still get the pod after delete
- kubelet stuck in reporting to apiserver.

**Comment by hongchaodeng** [comment]
Next action:
- We will try to reproduce this by constantly creating and deleting pods.

**Comment by hongchaodeng** [comment]
This is caused by cluster blocking each other due to controller sequentially handling cluster one by one.

Evidence:

On e2e:
```
 01:11:42.373898444 +0000 UTC waiting pod (test-etcd-8oqrs-0000) to be deleted.
```
'test-etcd-8oqrs' was deleted before that.

Operator handles another cluster in between and blocks:
```
time="2017-01-10T01:12:26Z" level=info msg="backup replica set and service created" cluster-name=test-etcd-5uss7 
```

On operator, it deletes 'test-etcd-8oqrs' 40s afterwards:
```
time="2017-01-10T01:12:26Z" level=info msg="cluster is deleted by the user" cluster-name=test-etcd-8oqrs
```
