### ISSUE TITLE
GC and backup manager overlap-manages Backup RS

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#615]
See https://github.com/coreos/etcd-operator/issues/612

**Comment by hongchaodeng** [comment]
@xiang90 
I think we should remove that responsibility from backup manager

**Comment by xiang90** [comment]
Hmm... I guess it is fine after we added the notFound error checking.

**Comment by hongchaodeng** [comment]
@xiang90 Just to clarify. This is not full GC, but lazy GC.
Basically, we call gc.CollectCluster() first, then bm.cleanup(). So they are overlapping each time we are deleting cluster

**Comment by hongchaodeng** [comment]
Yep.
There are two motivations: 1. efficiency as you mentioned; 2. we aren't GC-ing backup service. I'm inclined to combining these two and also put backup service into GC.

**Comment by xiang90** [comment]
We can do this after we fix our e2e?

**Comment by hongchaodeng** [comment]
Sure. Just to create this issue to track
