### ISSUE TITLE
controller restore (due to rev compaction) doesn't need to "kill" clusters

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#652]
Currently, if APIServer returns error like StatusGone (i.e. rev compacted), controller will need to restart:
- signals all cluster "manager" to delete (or "exit").
- waits them
- relists all clusters and restarts those cluster "managers"
- watches again.

During this restart, some knowledge will be lost (e.g. membership) and need to reinstated. We can probably optimize this without "killing" all clusters.

**Comment by xiang90** [comment]
#727 solves this in another way. We do not really need to restart controller in every out of date event. We only restart when necessary. So we do not need to worry about the inefficiency of the state build that much. Of course, we can still try to optimize it (not killing clusters even if restart happens) in the future.

/cc @hongchaodeng
