### ISSUE TITLE
Reviewing TPR naming/versioning before next release

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#655]
Our previous TPR naming isn't well thought enough. For example, we just "v1" for apiVersion.

Another problem is our TPR naming ("etcd-cluster.coreos.com") also needs further review.

We need to review these two before beta release.

**Comment by xiang90** [comment]
It seems that the only thing we need to do is to bump the apiVersion to v1, indicting that the spec is stable now?

**Comment by xiang90** [comment]
Actually it is already v1 :(... We made a mistake before. Closing this one.
