### ISSUE TITLE
doc: s3 backup

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd-operator#667]
we need to cover:

- how snapshot files are named
- how backup sidecar will access the s3 buckets
  - create a backup every interval 
  - purge backup when number reaches X
- how user should pull backup from s3

**Comment by hongchaodeng** [comment]
> - how backup sidecar will access the s3 buckets
>    - create a backup every interval 
>    - purge backup when number reaches X

This belongs to more general backup doc.

**Comment by xiang90** [comment]
Sure.

```

## Backup

How backup works

### S3

How does it access S3

### PV

How does it access PV

```

**Comment by hongchaodeng** [comment]
IIUC, we only have following items not documented:

> - create a backup every interval
> - purge backup when number reaches X

I don't think it should be documented in backup docs. It should belong to backup spec docs which we will also resolve in 
https://github.com/coreos/etcd-operator/issues/752

I'm gonna close this as duplicate.
