### ISSUE TITLE
versioning backup sidecar API

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd-operator#673]
Clearly, it becomes a user facing API once we want to enable user driven disaster recovery when K8S itself is down.

**Comment by hongchaodeng** [comment]
Action plan:
- make backup service API versioned: `/v1/backup?etcdVersion=v3.1.0`
- make S3 dir versioned: `${BUCKET_NAME}/${CLUSTER_NAME}/v1`
- We are still in progress deciding how to deal with PV stuff. It's not final yet. Let's deal with it once it's more clear.

**Comment by xiang90** [comment]
ok
