### ISSUE TITLE
stabilize release image 

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd-operator#674]
the default release image should be versioned.

we should create a etcd-operator-dev image to track github master.

**Comment by hongchaodeng** [comment]
I agree.
After beta, we should set "quay.../etcd-operator:latest" to latest version.

**Comment by xiang90** [comment]
> After beta, we should set "quay.../etcd-operator:latest" to latest version.

What does this mean? I think quay.../etcd-operator should never track our master branch anymore. it should track the release branch.

**Comment by hongchaodeng** [comment]
Yes. It's release branch. The latest release version, e.g. I have release "v1.0", "v1.1", "latest" = "v1.1"

**Comment by xiang90** [comment]
sure.

**Comment by hongchaodeng** [comment]
Closing this after v0.2.0 release.
We will keep it stabilized.
