### ISSUE TITLE
CI: add upstream master test

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd-operator#675]
1.5 regressions hit us pretty seriously. to become a better k8s citizens and avoid issues, we'd better help test k8s head to catch any potential regression early.

idea: add k8s master test. that cluster will be rebuilt every night automatically.
it wont block our pr, but we can see if it fails.

/cc @hongchaodeng @philips

**Comment by philips** [comment]
cc @ethernetdan

**Comment by ethernetdan** [comment]
@xiang90 do you have specific suites you want to have run?

**Comment by xiang90** [comment]
@ethernetdan https://github.com/coreos/etcd-operator/blob/master/test/e2e/main_test.go

this is the test entrance. @hasbro17 is working on this. the plan is to use pluton + bootkube to setup a k8s master built cluster nightly. then run this test against it.

**Comment by hongchaodeng** [comment]
done
