### ISSUE TITLE
Provide storage class options in cluster backup spec

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#691]
Currently, we only allow GCE, AWS as input and set up storage class for users. This is simple and cloud based for most users, especially new ones.

For the future, if there are user requests, we will add storage class field in backup spec. This issue to track it.

**Comment by EugeneKha** [comment]
We use glasterfs as persistence provider in Kubernetes. To make operator save backups to PV created by glusterfs we manually created storageClass named 'etcd-backup-gce-pd' that use glusterfs provider. Now we can use '--pv-provisioner=kubernetes.io/gce-pd' and PV is created in glusterfs cluster and operator works all right.

**Comment by xiang90** [comment]
implemented by #1358. Thanks @jamiehannaford!
