### ISSUE TITLE
versioning PV backup API

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#692]
Continue https://github.com/coreos/etcd-operator/issues/673

## Problem:
- how to get data from PV directly?
- version above API

## Proposed solution

First of all, We need a way to tell user what PV is for a specific cluster. In my experience, a PV created on GCE will have "pdName" indicating the actual disk's name.
For example, the following PV:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: gce-pd-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/gce-pd
    volume.beta.kubernetes.io/storage-class: etcd-operator-backup-gce-pd
  creationTimestamp: 2017-01-28T23:07:42Z
  labels:
    failure-domain.beta.kubernetes.io/region: us-west1
    failure-domain.beta.kubernetes.io/zone: us-west1-b
  name: pvc-9027b390-e5ae-11e6-9399-42010a8a0070
  resourceVersion: "323384"
  selfLink: /api/v1/persistentvolumes/pvc-9027b390-e5ae-11e6-9399-42010a8a0070
  uid: 924ce10e-e5ae-11e6-9399-42010a8a0070
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: test-etcd-fs5kk-pvc
    namespace: e2e-etcd-operator-flaketest-1189
    resourceVersion: "323369"
    uid: 9027b390-e5ae-11e6-9399-42010a8a0070
  gcePersistentDisk:
    pdName: gke-jenkins-349dcc6c-d-pvc-9027b390-e5ae-11e6-9399-42010a8a0070
  persistentVolumeReclaimPolicy: Delete
status:
  phase: Bound
```

its disk name is `gke-jenkins-349dcc6c-d-pvc-9027b390-e5ae-11e6-9399-42010a8a0070`. We can write this to cluster TPR status.

Once we lock down the disk, then it's up to user how to mount the disk. Then we need to tell user the path on which the data was stored. Proposed here:
```
/var/etcd-operator-backup/v1/${cluster_name}/
```

**Comment by xiang90** [comment]
> /var/etcd-operator-backup/v1/${cluster_name}/

It is the relevant part to this issue I assume. This looks good to me.
