### ISSUE TITLE
Warn users about DOS

### ISSUE THREAD

**Issue by immesys** [coreos/etcd-operator#699]
While trying out the etcd operator I brought down the entire cluster due to https://github.com/kubernetes/kubernetes/issues/39816

Perhaps a note in the readme until the issue is solved?

**Comment by hongchaodeng** [comment]
Right. That's an k8s issue.

What kind of note are you expecting to see in readme?

**Comment by immesys** [comment]
Well it doesn't seem that they are pushing a fix for that issue soon (it's closed at the moment), so perhaps something like "as of Kubernetes 1.5.1 following this guide will bring down all your masters, please check k8s issue <>"

I'm not at all trying to say this is your problem, just that when I read "this is alpha" I assumed that this service itself (etcd operator) may not work as expected, not that it would bring down the whole cluster. I was just a little surprised.

**Comment by hongchaodeng** [comment]
@immesys 
Even though it's alpha, we have always maintained the stability of master and have extensive e2e testing. We are moving towards beta soon.

> so perhaps something like "as of Kubernetes 1.5.1 following this guide will bring down all your masters, please check k8s issue <>"

Sure. I will put a note.

**Comment by mikedanese** [comment]
This also happens in 1.4.

**Comment by hongchaodeng** [comment]
@mikedanese 
We are running test against 1.4 all the time and haven't seen it as severe as 1.5 . We are using GKE so we don't have the logs of controller manager. Will try to verify it.

**Comment by so0k** [comment]
seems this is resolved since 1.5.3? https://github.com/coreos/etcd-operator/commit/f465324f014a036158c5511bb79645dd8070fc8b#diff-04c6e90faac2675aa89e2176d2eec7d8 

I just killed the controller manager in one of our clusters (1.5.1) due to this, but we run a HA masters and luckily only 1 of 5 masters crashed and we easily recovered.
