### ISSUE TITLE
e2e: etcd pod keeps "pending"

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#706]
https://jenkins-etcd.prod.coreos.systems/job/etcd-operator/1271/consoleText

test failed:
```
--- FAIL: TestBasic (90.20s)
    --- FAIL: TestBasic/basic_test (0.00s)
        --- FAIL: TestBasic/basic_test/pause_control (60.15s)
```

Looking into operator logs:
```
skip reconciliation: running ([test-etcd-sabn1-0000]), pending ([test-etcd-sabn1-0001])
```
There is a pod keeps pending.

Although at last the pod resumes:
```
util.go:326: 2017-01-29 18:35:17.910728462 +0000 UTC waiting size (3), etcd pods: [test-etcd-sabn1-0000]
util.go:326: 2017-01-29 18:35:27.912140794 +0000 UTC waiting size (3), etcd pods: [test-etcd-sabn1-0000 test-etcd-sabn1-0001]
```

Time's up. Test failed

**Comment by hongchaodeng** [comment]
Happened again:

https://jenkins-etcd.prod.coreos.systems/job/etcd-operator-flaketest/1444/consoleText
```
util.go:361: 2017-02-02 00:46:30.281528323 +0000 UTC waiting size (5), etcd pods: [test-etcd-6xl29-0000 test-etcd-6xl29-0001 test-etcd-6xl29-0002 test-etcd-6xl29-0003]
util.go:219: pod (test-etcd-6xl29-0004): status (Pending), cmd ([/bin/sh -c sleep 5; /usr/local/bin/etcd --data-dir=/var/etcd/data --name=test-etcd-6xl29-0004 --initial-advertise-peer-urls=http://test-etcd-6xl29-0004:2380 --listen-peer-urls=http://0.0.0.0:2380 --listen-client-urls=http://0.0.0.0:2379 --advertise-client-urls=http://test-etcd-6xl29-0004:2379 --initial-cluster=test-etcd-6xl29-0002=http://test-etcd-6xl29-0002:2380,test-etcd-6xl29-0000=http://test-etcd-6xl29-0000:2380,test-etcd-6xl29-0004=http://test-etcd-6xl29-0004:2380,test-etcd-6xl29-0003=http://test-etcd-6xl29-0003:2380,test-etcd-6xl29-0001=http://test-etcd-6xl29-0001:2380 --initial-cluster-state=existing])
```

**Comment by pbx0** [comment]
Yes, I've had trouble reproducing this. Here are some incomplete logs I saved when looking at it the first time:

`kube-system   kube-etcd-0002     0/1       Init:CrashLoopBackOff   5        4m`

The last etcd pod out of 3 eventually ended up crashlooping and I had similar logs from the etcd-operator which was also restarting occasionally.

```
time="2017-02-01T23:34:08Z" level=info msg="use in cluster client from k8s library"
time="2017-02-01T23:34:08Z" level=info msg="finding existing clusters..." pkg=controller
time="2017-02-01T23:34:08Z" level=info msg="starts running from watch version: 1685" pkg=controller
time="2017-02-01T23:34:08Z" level=info msg="start watching at 1685" pkg=controller
time="2017-02-01T23:34:16Z" level=info msg="skip reconciliation: running ([kube-etcd-0000 kube-etcd-0001]), pending ([kube-etcd-0002])" cluster-name=kube-etcd pkg=cluster
time="2017-02-01T23:34:24Z" level=info msg="skip reconciliation: running ([kube-etcd-0000 kube-etcd-0001]), pending ([kube-etcd-0002])" cluster-name=kube-etcd pkg=cluster
```

**Comment by hongchaodeng** [comment]
Not seen anymore. Closing old flaky issue.

**Comment by bzub** [comment]
I've seen this, and it's preventing me from scaling up etcd clusters.  It may be a kubernetes bug with init containers, as many others have reported it with other software. See https://github.com/kubernetes/kubernetes/issues/29972

K8s master components seem to be unaffected and treat the pod as healthy since the pod reports Ready=True, but etcd-operator isn't satisfied since the initialization is erroneously "Pending" after it first succeeded.  So there could be a workaround or enhancement possible on the etcd-operator side to look at the Pod status as Ready and be satisfied?

To illustrate, when I `kubectl -n kube-system describe pod kube-etcd-0000` I see this status for the Pod:
```
Conditions:
  Type          Status
  Initialized   False 
  Ready         True 
  PodScheduled  True
```

and I see this state for the append-hosts init container:
```
    State:              Waiting
      Reason:           PodInitializing
    Ready:              False
    Restart Count:      0
    Environment:        <none>
```
