### ISSUE TITLE
e2e flake: TestFailureRecovery (PVC keeps pending)

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#730]
https://jenkins-etcd.prod.coreos.systems/job/etcd-operator-flaketest/1497/consoleText

From operator logs:
```
cluster failed to setup: fail to wait PVC (test-etcd-wsc2s-pvc) '(Pending)/Bound': still failing after 5 retries
...
cluster failed to setup: fail to wait PVC (test-etcd-2cpb4-pvc) '(Pending)/Bound': still failing after 5 retries
```

**Comment by hongchaodeng** [comment]
This is somehow expected.. We can't do anything if PVC isn't setup.

**Comment by xiang90** [comment]
Can we know why PVC is pending so long?

**Comment by hongchaodeng** [comment]
I just realized another problem.

There are some garbage disks left on GCE:
![screen shot 2017-02-02 at 4 24 07 pm](https://cloud.githubusercontent.com/assets/920884/22574503/1153461a-e964-11e6-9164-b6cd5b5f6895.png)

Although not confirmed, I suspect it was caused by this kind of failures.

**Comment by hongchaodeng** [comment]
We need to resolve this failure.
It happens quite frequently

**Comment by hongchaodeng** [comment]
I have tried to increase the wait PVC time from 20s to 60s to test if it's a timing issue, or if it's never bound.

**Comment by hongchaodeng** [comment]
OK. So after bumping up wait time to 60s, this failure doesn't show again for over a night's tests.

**Comment by hongchaodeng** [comment]
Run for another day. No failure after bumping up to 60s.

Now we are sure that it's just taking >20s from PVC is created to PVC is bound:

https://github.com/coreos/etcd-operator/blob/91c21ac04caafaa99e434fc7fbf96732cbb32c11/pkg/util/k8sutil/backup.go#L90-L105

**Comment by xiang90** [comment]
What is the normal creation time? We shall create an issue on k8s upstream.

**Comment by hongchaodeng** [comment]
One example:
```
time="2017-02-03T15:02:31Z" level=info msg="creating cluster with Spec (spec.ClusterSpec{Size:3, Version:\"3.1.0\", Paused:false, Pod:(*spec.PodPolicy)(nil), Backup:(*spec.BackupPolicy)(0xc4207a4ec0), Restore:(*spec.RestorePolicy)(nil), SelfHosted:(*spec.SelfHostedPolicy)(nil)}), Status (spec.Cluste...
time="2017-02-03T15:02:35Z" level=info msg="backup replica set and service created"
```

4s for everything to be created.

**Comment by xiang90** [comment]
@hongchaodeng Can you create an issue on upstream k8s? Explain that we observed some abnormal latency on creating PVC?

**Comment by hongchaodeng** [comment]
This is GKE cluster. Should we report to GKE?

**Comment by xiang90** [comment]
upstream please. the gce pd plugin is part of upstream k8s support

**Comment by xiang90** [comment]
Tracking at https://github.com/kubernetes/kubernetes/issues/40972 now. 

Let's bump the timeout and close it?
