### ISSUE TITLE
backup pod: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#731]
https://jenkins-etcd.prod.coreos.systems/job/etcd-operator-flaketest/1445/consoleText

```
restore_test.go:93: fail to make a backup: backup pod (test-etcd-x7p8h-backup-sidecar-wfsd9): backupnow (10.216.5.14:19999) failed: Get http://10.216.5.14:19999/v1/backupnow: dial tcp 10.216.5.14:19999: getsockopt: connection refused
```

**Comment by xiang90** [comment]
I cannot open the log. Can you check if the url is correct?

**Comment by hongchaodeng** [comment]
@xiang90 
The jenkins only store most recent 100 tests. Unfortunately we build 100 tests a day. So it's gone.

**Comment by xiang90** [comment]
@hongchaodeng Can we fix it fixed? Or we probably do this as etcd issues (always pre process log, copy related log to github issue when possible).

**Comment by hongchaodeng** [comment]
> Can we fix it fixed? 

Didn't catch that.

> Or we probably do this as etcd issues (always pre process log, copy related log to github issue when possible).

I agree we need some workflow for saving logs. Currently the logs isn't easy to copy and save around. We need to have some solutions for this.

**Comment by xiang90** [comment]
I mean can we get this fixed? Like can we increase 100 to 1000 temporarily?

**Comment by hongchaodeng** [comment]
@xiang90 
We didn't have any retry on this. This is rare case so we don't bother to make it robust.
When we try to make a backup in that test, the backup pod is ensured to be up. And we talk directly to pod ip.

I checked again the backup pod's log:
```

17:07:25.000
panic: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
17:07:25.000
17:07:25.000
goroutine 1 [running]:
17:07:25.000
panic(0x1503380, 0xc4204cf040)
17:07:25.000
/usr/local/go/src/runtime/panic.go:500 +0x1a1
17:07:25.000
github.com/coreos/etcd-operator/pkg/util/k8sutil.MustCreateClient(0x0, 0x0, 0x0, 0x0, 0xc42042f300, 0x0)
17:07:25.000
/home/jenkins/workspace/build-etcd-operator-flaketest-1386/gopath/src/github.com/coreos/etcd-operator/pkg/util/k8sutil/k8sutil.go:303 +0x108
17:07:25.000
main.main()
17:07:25.000
/home/jenkins/workspace/build-etcd-operator-flaketest-1386/gopath/src/github.com/coreos/etcd-operator/cmd/backup/main.go:72 +0x188
17:07:44.000
time="2017-02-02T01:07:44Z" level=info msg="listening on 0.0.0.0:19999"
17:14:46.000
shutting down, got signal: Terminated
```
This is totally wrong.. It's a pod, but it couldn't find in-cluster configs.

**Comment by xiang90** [comment]
> panic: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined

Is this our problem? Or kubernetes? Shall we report to upstream if this is a k8s issue?

**Comment by hongchaodeng** [comment]
@xiang90 
k8s problem.

We create in-cluster client using go. It failed to. But I don't think this is client problem because the logs showed that `KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT` isn't defined. They should be set in env by default.

**Comment by xiang90** [comment]
@hongchaodeng Can you create an issue on upstream? Thanks!

**Comment by xiang90** [comment]
https://github.com/kubernetes/kubernetes/issues/40973

**Comment by xiang90** [comment]
@hongchaodeng I do not think anyone is going to fix this for us... Let's work this around by trying on the error.

**Comment by hongchaodeng** [comment]
There are two ways to work around from following comments:
https://github.com/kubernetes/kubernetes/blob/fa0387c9fea7cf4b3e3032bb384d8b5f99580154/pkg/kubelet/kubelet_pods.go#L395-L398
```
// Note that there is a race between Kubelet seeing the pod and kubelet seeing the service.
// To avoid this users can: (1) wait between starting a service and starting; or (2) detect
// missing service env var and exit and be restarted; or (3) use DNS instead of env vars
// and keep trying to resolve the DNS name of the service (recommended).
```

I don't really get (1) so I'm picking (2) and (3).
(2) is what we are currently doing right now. In real world, this is fine. But it still caused test flaky.
(3) is done inside client-go, so we need client-go to fix that.

**Comment by hongchaodeng** [comment]
A new option: we can resolve DNS name and set the env ourselves.

**Comment by hongchaodeng** [comment]
@xiang90 
Let me explain further here.

Retrying `rest.InClusterConfig` isn't gonna help. The env is not set when pod is started up. We could either restart the pod or set the env by resolving DNS ourselves.

**Comment by xiang90** [comment]
@hongchaodeng I will check kubelet code to see what is really going on there. My impression was that the ENV might not set before the pod comes up, but eventually it will be set.

**Comment by jadonant** [comment]
What's the solution for this, I'm seeing the error message myself?
