### ISSUE TITLE
e2e flake: fail to wait services deleted

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#732]
https://jenkins-etcd.prod.coreos.systems/job/etcd-operator-flaketest/1442/consoleText

```
util.go:361: 2017-02-02 00:11:18.372351116 +0000 UTC waiting service (test-etcd-49rlw) to be deleted
restore_test.go:96: fail to wait services deleted: still failing after 5 retries
```

**Comment by xiang90** [comment]
@hongchaodeng I cannot open the url in the issue. Can you check if it is correct?

**Comment by hongchaodeng** [comment]
The jenkins only store most recent 100 tests. We build 100 tests a day. So it's gone.
