### ISSUE TITLE
operator metrics

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#737]
There are some metrics that we should expose so that users can better understand what happened if pressures goes up -- mem rises, cpu tight, requests burst.

This issue serves to track it and eventually we should expose prom metrics via http.

Some thoughts:
- status code from apiserver
- when operator rebuilds cache for all clusters.

**Comment by hongchaodeng** [comment]
Some related upstream issue:
https://github.com/kubernetes/community/pull/355
https://github.com/kubernetes/community/pull/288

We are having issues with long tail on PV provisioning.

**Comment by xiang90** [comment]
@hongchaodeng Do you want me to take this over?

**Comment by hongchaodeng** [comment]
Sure
