### ISSUE TITLE
print version in log when operator starts

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#744]
We should print version when operator starts.
For example:
```
version: 1.0.0
(or + git-hash if not at exact version)
version: 1.0.0+9cfacbe28857a5e400fb6e92095cc3139e495f59
```
Should include this in beta release

**Comment by xiang90** [comment]
I will take this one.

**Comment by xiang90** [comment]
Fixed by https://github.com/coreos/etcd-operator/pull/745
