### ISSUE TITLE
More docs about how to use cluster spec

### ISSUE THREAD

**Issue by sunnybi** [coreos/etcd-operator#752]
I am very glad to see the etcd operator product and it is really very nice to me.
Now I am using the etcd operator to create the etcd cluster. But I don’t know how to use the nodeSelector in the etcd cluster yaml file.
I tried below, but failed. Could you help provide one example? Thanks very much.
And another question, how can I use my private ETCD image instead of the coreos standard etcd image?

apiVersion: "coreos.com/v1"
kind: "EtcdCluster"
metadata:
  name: "etcd-cluster-test"
spec:
  size: 3
  version: "3.0.1"
  nodeSelector:
    kubernetes.io/hostname: ssc-8
  containers:
  - name: pause
    image: my_test:latest

**Comment by hongchaodeng** [comment]
Hi @sunnybi . Thanks for nice words.

> I tried below, but failed.

What failed?

> Could you help provide one example?

I would like to. But could you clarify what's your use case?

> And another question, how can I use my private ETCD image

We probably won't support private ETCD image on open source side. That's because we need to validate upgrade path and backup versions. Those are important for not breaking user etcd clusters.

If you really want to use private ETCD image, one option is to build and use your own etcd operator image. But this is at your own risk (upgrade, backup).

**Comment by hongchaodeng** [comment]
Also this selector doesn't make any sense:
```
kubernetes.io/hostname: ssc-8
```
Do you want to put all etcd pods onto one node?

We provide node selector so that user can choose nodes with better disk:
```
diskType: ssd
```

**Comment by sunnybi** [comment]
Thank you hongchaodeng.
yes, I want to setup etcd cluster on one node. Currently, kubernets supports many nodeselector, disktype is one of them.
Here I copied them from kubernets website.
kubernetes.io/hostname
failure-domain.beta.kubernetes.io/zone
failure-domain.beta.kubernetes.io/region
beta.kubernetes.io/instance-type
beta.kubernetes.io/os
beta.kubernetes.io/arch

https://kubernetes.io/docs/user-guide/node-selection/

**Comment by xiang90** [comment]
@sunnybi 

So you specify the node name in the etcd cluster spec and hoping etcd operator will schedule all members onto that specific node? And etcd operator fails to assign etcd members pods to that node?

What failed exactly?

**Comment by sunnybi** [comment]
@xiang90 
Thank you!
Yes, that's what I exactly want to do. When I use etcd operator to create ETCD instance, and use nodeSelector to assign it to one node. But the ETCD node is not what I assigned for it.

**Comment by xiang90** [comment]
@sunnybi Can you get the yaml description of the etcd cluster spec, the etcd pods and the nodes? I want to check if:

1. the spec is valid
2. the node selector is set on the pods
3. the node is labeled correctly

**Comment by sunnybi** [comment]
@xiang90
This is my etcd cluster yaml file. Do I need write one ETCD pod file? I thought only one deployment and cluster yaml is enough.
The node info is correct because we can set up one ETCD on this node by pod file which includes the same nodeSelector.

apiVersion: "coreos.com/v1"
kind: "EtcdCluster"
metadata:
  name: "etcd-cluster-test"
spec:
  size: 3
  version: "3.0.1"
  nodeSelector:
    kubernetes.io/hostname: foss-ssc-8
  containers:
  - name: pause
    image: my_test:latest

**Comment by xiang90** [comment]
@sunnybi 

The node selector needs to be put inside Pod struct: see https://github.com/coreos/etcd-operator/blob/master/pkg/spec/cluster.go#L78

you need something like

```
pod
     nodeselector: xxx
```

**Comment by xiang90** [comment]
But it does not really make sense to put ALL etcd nodes onto the same node though as @hongchaodeng mentioned above.

**Comment by sunnybi** [comment]
@xiang90 
Thanks. I thought it is in cluster yaml by reading the etcd operator best practices doc. It says to add nodeSelector in cluster spec. so I does. But how does the etcd-operator to read the etcd pod yaml? If I can write my own etcd pod file, then private image can be used.

Assign to nodes with desired resources

Kuberentes nodes can be attached with labels. Users can assign pods to nodes with given labels. Similarly for the etcd-operator, users can specify Node Selector in the pod policy to select nodes for etcd pods. For example, users can label a set of nodes with SSD with label "disk"="SSD". To assign etcd pods to these node, users can specify "disk"="SSD" node selector in the cluster spec.

**Comment by xiang90** [comment]
@sunnybi Sure. We will have a doc covering how to use the spec and provide more examples.

**Comment by sunnybi** [comment]
@xiang90
The deployment works fine using the same nodeSelector.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: etcd-operator
    spec:
      nodeSelector:
        kubernetes.io/hostname: foss-ssc-8
      containers:
        - name: etcd-operator
          image: quay.io/coreos/etcd-operator
          env:
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

**Comment by hongchaodeng** [comment]
Hi @sunnybi 

First of all, please write correct yaml file like this for easier reading:
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd-operator
spec:
  replicas: 1
  template: ...
```

Second, let me catch the question

> The deployment works fine using the same nodeSelector.

Do you mean it works by assigning etcd operator pod to the node? Why not?

Re. etcd pod's node selector, please following our spec:
https://github.com/coreos/etcd-operator/blob/master/pkg/spec/cluster.go#L59

We will have docs soon. Currently you can do:
```yaml

spec:
  size: 3
  pod:
    nodeSelector: ...
```

**Comment by sunnybi** [comment]
@hongchaodeng
Thank you!
Yes, I am writing the readable yaml. But when I copy it here, it is unordered. 
The etcd operator pod really works well by assigning the nodeSelector.
![image](https://cloud.githubusercontent.com/assets/25626516/22773281/2df41c04-eedc-11e6-992a-9f4b5c39cade.png)

**Comment by hongchaodeng** [comment]
> The etcd operator pod really works well by assigning the nodeSelector.

great. nice to hear that.

**Comment by hongchaodeng** [comment]
Updated the title to be more descriptive. Let me know if there is any more questions.
