### ISSUE TITLE
user: don't run as root

### ISSUE THREAD

**Issue by philips** [coreos/etcd-operator#806]
The etcd operator container is running as the root user by default. There is no reason to do this, please change to a UID other than 0.

**Comment by hongchaodeng** [comment]
@philips 
I'm just curious: most, if not all, Dockerfiles that I have seen are using default user account. What was the reason to change it? Any security concern?

**Comment by philips** [comment]
The default to root behavior is a hold over for backwards compatibility from early Docker days AFAIK. There is even a warning in the doc: https://docs.docker.com/engine/reference/builder/#user
