### ISSUE TITLE
Better information about decision to ignore a cluster

### ISSUE THREAD

**Issue by djMax** [coreos/etcd-operator#818]
etcd-operator logs this:

```
time="2017-02-23T21:07:47Z" level=info msg="finding existing clusters..." pkg=controller
time="2017-02-23T21:07:48Z" level=info msg="ignore failed cluster etcd-cluster" pkg=controller
```

And then does nothing. It's very hard to know WHY it's ignoring that cluster and how to make it bring it back up. I have a backup pv, shouldn't it pick it up?

**Comment by hongchaodeng** [comment]
@djMax 

> failed cluster etcd-cluster

Unlike normal pod (e.g. nginx), our TPR has states:
```
Initial -> Creating/Bootstraping -> Running -> End/Failed
```
in non-reversible order.

This is to guarantee cluster's safety.

Would you do:
```
$ kubectl get pvc
```

**Comment by djMax** [comment]
The pvc and the pv were still there. I deleted the deployment and created it again, and then it attempted to come up but bumped against the existing pvc. So I deleted that pvc, which then cascaded to the pv. So now I'm just bringing up the cluster fresh. But I still think it should give some clear indication of what to do in this case. Reset some value in the TPR? etc. Or if the desired action is "delete the cluster and make it again", so be it.

**Comment by hongchaodeng** [comment]
Let's keep this open.
If user made mistakes and delete the cluster, as long as the PVC is still there, we should be able to recover it.
I think the point here is that users don't know how to do it. There is some docs around backup thing in: https://github.com/coreos/etcd-operator/tree/master/doc/user . But this isn't covered yet. Let's add the user docs before closing this issue.

**Comment by hongchaodeng** [comment]
Some examples about how to restore from previous backup:

https://github.com/coreos/etcd-operator/blob/master/doc/user/spec_examples.md#three-members-cluster-that-restores-from-previous-pv-backup

**Comment by hongchaodeng** [comment]
Provide more info in https://github.com/coreos/etcd-operator/pull/852

Closing this
