### ISSUE TITLE
Setting up Jenkins infra on AWS

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#821]
Currently our Jenkins infra is running on GKE. We also need to test on AWS.

Action items:
- [x] Set up nightly job to run e2e tests of etcd operator "master". We can use static cluster here, e.g. reusing long running k8s v1.5.3 .
- [ ] Set up (another?) nightly job to build k8s master, and create new k8s cluster, then run e2e tests of etcd operator "master" on it.
- [ ] The e2e TestSelfHosted currently fails on an AWS cluster since the etcd-operator pod cannot connect(timeout) to a self hosted etcd-cluster pod(using hostNetwork) on a different node. Find a way to ping a hostedNetwork pod on a different node in an AWS vpc.
- [ ] https://github.com/coreos/etcd-operator/issues/788

**Comment by hongchaodeng** [comment]
xref: https://github.com/coreos/etcd-operator/issues/675

**Comment by hasbro17** [comment]
Nightly jenkins jobs are in place to build the upstream etcd operator master branch, and run e2e tests. One uses a static cluster while another uses kube-aws to launch a fresh cluster for every build.
So far both jobs have identical outputs, in the number of tests that they seem to be failing.

**Comment by xiang90** [comment]
@hasbro17 Great progress!

**Comment by hongchaodeng** [comment]
I'm moving this out from milestone.

We have ended up with e2e testing against k8s "master" version cluster on GCE due to easier maintenance.

**Comment by hongchaodeng** [comment]
Closing in favor of https://github.com/coreos/etcd-operator/issues/1598
