### ISSUE TITLE
unit test is taking way too long time

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#843]
Recent failure https://jenkins-etcd.prod.coreos.systems/job/etcd-operator/1505/console:

```
00:29:38.559 ok  	github.com/coreos/etcd-operator/test/e2e	1292.560s
...
01:23:05.043 ?   	github.com/coreos/etcd-operator/pkg/util/retryutil	[no test files]
```

We see that e2e finish at "00:29:38", but unit test finish at "01:23:05".

**Comment by hongchaodeng** [comment]
Another failure:
https://jenkins-etcd.prod.coreos.systems/view/operator/job/etcd-operator/1506/console

It doesn't even finish after ~1h.

**Comment by hongchaodeng** [comment]
jenkins slave has 8 cores, 3 concurrent jobs running I believe, and jump to 100% cpu usage.

**Comment by hongchaodeng** [comment]
Some benchmarks:

With coverage result:
```
PASSES="unit" hack/test  956.34s user 91.44s system 207% cpu 8:24.33 total
```

Without coverage result:
```
PASSES="unit" hack/test  117.42s user 12.17s system 193% cpu 1:06.87 total
```

**Comment by hongchaodeng** [comment]
This is significant difference.

I think we should disable coverage first since we aren't using it yet. We could enable coverage later once we have better solution for such long haul.

**Comment by xiang90** [comment]
@hongchaodeng Can you figure out why coverage makes tests take long time? Does the test itself take long time? Or build the test code with coverage takes longer? If it is the latter, we should not disable coverage. I have never seen this problem before. etcd enables coverage from day 1.

**Comment by hongchaodeng** [comment]
This is making master failed now.

**Comment by xiang90** [comment]
@hongchaodeng How do you know it is the test coverage makes the master fail? It really should not. I suspect there is something else going wrong.

**Comment by xiang90** [comment]
Also I do not believe it is the coverage causing the test took 1 hour to finish.

**Comment by hongchaodeng** [comment]
> How do you know it is the test coverage makes the master fail?

See my above comments. We know from from the timestamp that unit test took ~1h

**Comment by xiang90** [comment]
> We know from from the timestamp that unit test took ~1h

that does not mean it was caused by the coverage part.

**Comment by hongchaodeng** [comment]
I have PR https://github.com/coreos/etcd-operator/pull/844 to see if that alleviates the problem. Let's see the result then.

I'm fine as long as we can get PR/master jobs pass.

**Comment by xiang90** [comment]
> I'm fine as long as we can get PR/master jobs pass.

We shall find the root cause and fix it. We should not just guess around.

If you look back to history, there are quite a few tests passed after enabling coverage. I am not convinced it is the root cause. Even if #884 passes, we shall not disable coverage right now.

**Comment by hongchaodeng** [comment]
OK.. Let me debug further.

**Comment by xiang90** [comment]
@hongchaodeng Thanks!

**Comment by hongchaodeng** [comment]
This issue is caused by small machine (1 cpu). We re-deployed jenkins this afternoon.

master is fixed now:
https://jenkins-etcd.prod.coreos.systems/job/etcd-operator-master/381/console
```
00:17:07.807 ok  	github.com/coreos/etcd-operator/test/e2e	911.811s
...
00:23:24.536 ?   	github.com/coreos/etcd-operator/pkg/util/retryutil	[no test files]
```
