### ISSUE TITLE
put test infra scripts into different repo

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#845]
Currently we put our test infra scripts here for simpler management. Once our codebase grows larger, we can separate them out.

**Comment by hasbro17** [comment]
Closing this for now until we find a cleaner solution to separate/hide our jenkins specific files from the repo. 
This will become a higher priority if the number of jenkins jobs increases to warrant better management.  

We could still potentially move jenkins specific scripts to a private repo, and then fetch those within our jenkins jobs before.
