### ISSUE TITLE
TPR named "Cluster" is too generic

### ISSUE THREAD

**Issue by snarlysodboxer** [coreos/etcd-operator#860]
In prometheus operator, the main TPR, defining a _cluster_ of prometheus instances, is a `prometheus`, and you can `kubectl get prometheuses`.

In etcd operator, a cluster of etcd instances is a `cluster`, and `kubectl get clusters` is very confusing because k8s itself is a "cluster" and some of us work with multiple k8s clusters and run commands like `kubectl config get-clusters`.

I submit that the TPR should be called `etcd`, or `etcdCluster`, or anything other than `cluster`.  etcd is not the only thing of which you can have a "cluster", E.G. PostgreSQL, Redis, MongoDB, Casandra, on and on.

**Comment by hongchaodeng** [comment]
You can do `kubectl get cluster.etcd`

**Comment by hongchaodeng** [comment]
> TPR should be called etcd, or etcdCluster

We were previously (in alpha) using kind `EtcdCluster`, api group `coreos.com`. Due to some TPR bugs, we can't share api group with others. Thus, we have to make api group more specific, finally `etcd.coreos.com` . Now It doesn't make sense to make the whole endpoint `etcd.etcd.coreos.com` or `etcdcluster.etcd.coreos.com`, we finally come to the point `cluster.etcd.coreos.com` .

**Comment by xiang90** [comment]
@snarlysodboxer You are right. I was under the impression that only `cluster.etcd` will work... We will probably have to change the main TPR name back to `etcdCluster`.

**Comment by hongchaodeng** [comment]
ref: https://github.com/kubernetes/kubernetes/issues/42521

**Comment by so0k** [comment]
for me `kubectl get cluster.etcd` didn't work, but `kubectl get cluster.etcd.coreos.com` did! - thanks

**Comment by hongchaodeng** [comment]
@TimJones

Current plan is that we will make the change once we move to CRD (aka TPRv2). This will happen before k8s 1.8 .

**Comment by hongchaodeng** [comment]
Closing. Please track in https://github.com/coreos/etcd-operator/issues/1236
