### ISSUE TITLE
Change TPR resource `cluster` to `etcdcluster`

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#861]
The reason has been discussed in https://github.com/coreos/etcd-operator/issues/860

Action items:
- [ ] have migration plan
- [ ] make the change in the spec definition
- [ ] implement, test, docs migration tool

**Comment by xiang90** [comment]
I am still trying to see what is the best option here. Can we put this for thought for a while?

/cc @chancez I would like to know your opinion on this too.

**Comment by chancez** [comment]
I think `cluster` is fine, but I really dislike that kubectl doesn't require the API group by default. I think if by default `kubectl get cluster` is going to remain valid, I then I think the best option is to rename to `etcdcluster`. I'm not a fan of it, but perhaps it's the best option we have. I think we should ask, what are other operators/TPRs using for naming conventions?

**Comment by odacremolbap** [comment]
Federation API contains a cluster object.
`kubectl get cluster` is the `kubectl get pod` of kubernetes federations.

I'd avoid using that name, there can be a chance in the future that someone wants to use a federated etcd operator cluster.

**Comment by hongchaodeng** [comment]
Closing. Please track in https://github.com/coreos/etcd-operator/issues/1236
