### ISSUE TITLE
Any plan to implement etcd2 backup/restore?

### ISSUE THREAD

**Issue by snarlysodboxer** [coreos/etcd-operator#864]
We're loving etcd operator, thank you!

We have several applications that are still using the etcd v2 API, we hope to update them to v3 at some point, but in the meantime, I need to implement HA etcd clusters with backup and restore for etcd v2 storage.

Do you have any plans to implement backup and restore for etcd v2 storage?

**Comment by xiang90** [comment]
No. There is no current plan for implement v2 storage backup. But there is a potential effort to use v3 storage for v2 API. It depends on how much bandwidth we have at etcd side.

**Comment by snarlysodboxer** [comment]
@xiang90 Thank you for your feedback.

If I understand correctly, this means we cannot use etcd operator at all, even if we implement our own backup and restore.

On an etcd cluster without defined backup/restore, in the event of disaster, etcd operator will mark the cluster "dead" and delete the pods and service. My applications are now pointed at a service which doesn't exist and which I cannot recreate for manual data restore.

**Comment by xiang90** [comment]
> we cannot use etcd operator at all

you cannot use it for v2 if you want auto backup.

**Comment by snarlysodboxer** [comment]
i'm saying we can't use it for v2 even if we do manual backup. - because there's no ability to stand the dead cluster back up for manual recovery.

**Comment by xiang90** [comment]
@snarlysodboxer You could in theory (maybe with some little modification of the current code). There is a restore option in the cluster spec. You have to manually prepare the data directory for the restore to be successful.

**Comment by xiang90** [comment]
What I said is we do not have plan to do auto backup. If you want the restore part to work, PRs are welcomed.

**Comment by xiang90** [comment]
I am closing this one since we do not have plan to support the requested feature.
