### ISSUE TITLE
always fill in current version

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd-operator#888]
If user does not give a version, the operator will choose a default version for it. But it does not fill in current version filed in the status. Let's fix this.

/cc @hongchaodeng

**Comment by hongchaodeng** [comment]
@xiang90 
I tested it and it eventually sets version.
It needs all members to be set up before setting current version.

**Comment by xiang90** [comment]
Oh. That is right. I tried again. It works if I wait for a while.

We probably should improve that a little bit though. We should be able to set the current version directly if we set the default for the users?

**Comment by hongchaodeng** [comment]
TBH, it has nothing to do with "default version". This is a problem of a cluster's lifecycle's beginning.

For example, if it's not beginning, let's say, we see current version "3.1", target version "3.2". Then it take a while and finally current version will be "3.2". But at the beginning, there is no current version, only target version "3.1".
