### ISSUE TITLE
Self-hosted etcd pod restartPolicy should be `OnFailure`

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#902]
Currently it is `Always`. After a member was removed, if operator failed to remove its pod, then the member could restart again. If it exited 0, we should let it go. We need to cleanup `completed` pod though.

**Comment by xiang90** [comment]
How will k8s treat a restarted node's pods that are set to `OnFailure`?

**Comment by hongchaodeng** [comment]
Stopping a node in a short time won't change its pods statuses.

**Comment by hongchaodeng** [comment]
After some research, I don't think kubelet provides good guarantees on node restart. Docker daemon could return exit code=0 for all containers on restart.
