### ISSUE TITLE
Build on Mac fails

### ISSUE THREAD

**Issue by narayanan** [coreos/etcd-operator#907]
Building `etcd-operator` on my mac use to work. But builds stopped working recently. I see a recent change in `build` script  to add os & arch. Not sure if that is causing the issue.

```
$ IMAGE=etcd-operator hack/build/operator/build
go install: cannot install cross-compiled binaries when GOBIN is set
```

Is building source code on mac supported? or Should I try building with in a linux container?

**Comment by hongchaodeng** [comment]
Please read https://github.com/coreos/etcd-operator/blob/master/doc/dev/developer_guide.md .

If you want to support it on Mac, PR is welcome.

**Comment by narayanan** [comment]
Thanks for quick response.
