### ISSUE TITLE
Option to set auto compaction retention policy

### ISSUE THREAD

**Issue by snarlysodboxer** [coreos/etcd-operator#914]
We would like to be able to set [this setting](https://github.com/coreos/etcd/blob/master/Documentation/op-guide/configuration.md#--auto-compaction-retention), otherwise we have to run jobs to periodically do compaction.

There are a couple others that would be nice to be able to set as well, like [v2](https://github.com/coreos/etcd/blob/master/Documentation/op-guide/configuration.md#--enable-v2), [cors](https://github.com/coreos/etcd/blob/master/Documentation/op-guide/configuration.md#--cors), and others.

**Comment by xiang90** [comment]
Yes. This is something we will address soon.

**Comment by xiang90** [comment]
@snarlysodboxer do you want to add this feature?

we need to:

1. introduce etcdPolicy into the cluster spec
2. add auto compaction as the first parameter
