### ISSUE TITLE
Need for a "none" pv provisioner type

### ISSUE THREAD

**Issue by uruddarraju** [coreos/etcd-operator#921]
Today, etcd operator supports only 2 pv provisioning types, `aws` and `gce-pd`. It should be possible for users without this functionality also to start up etcd operator to just bootstrap and etcd cluster real quick (great work btw, with the operator) without the need for a pv provisioning mode. 

This will let users be able to spin up etcd clusters without etcd needing to register a new storage class, where it is not supported. 

As some background, this is what I tried. At eBay, we use a pv provisioner with cinder. As cinder pv provisioner type is not yet supported, and I wanted to quickly try out etcd operator to bring up an etcd cluster, I could not do it because the operator startup fails saying it cannot register a storage class gce-pd. Why would I even want to register a provisioner called gce-pd when I am running on openstack cloud. Hence, we would need a none provisioner, which would just ignore the storage class registration. 

An other enhancement on top of this is to check the storage class existence, even before the operator tries to create one, this way, even if the operator was not given access to create a storageclass and if the storageclass exists, it can just continue without failing.

Relevant work: https://github.com/coreos/etcd-operator/pull/920

**Comment by uruddarraju** [comment]
cc @hongchaodeng

**Comment by hongchaodeng** [comment]
@uruddarraju
We will do a release later.
Currently I pushed latest image to` quay.io/coreos/etcd-operator:dev`.
Can you try it out?
