### ISSUE TITLE
how to let kubernetes to use etcd3 for it's own configuration

### ISSUE THREAD

**Issue by kfirufk** [coreos/etcd-operator#925]
Hi! :)

I have Container Linux by CoreOS 1353.1.0 installed on my cluster, it comes with etcd2 by default but I want to remove etcd2 and to have etcd3 support. now I know I can use your wonderful project to have etcd3 pods up and running. can I tell kubernetes to store it's own configuration in the etcd3 pods?
do I need to install kubernetes etcd-less and then to run these pods? then how do I tell kubernetes to store it's own configuration there?

I'm a bit lot on how to properly remove the usage of etcd2 and to use etcd3 on my nodes.

thank you!

**Comment by hongchaodeng** [comment]
Yes.
Please checkout bootkube: https://github.com/kubernetes-incubator/bootkube/
And this self hosted etcd demo: https://www.youtube.com/watch?v=RNM3CrbfLn8

**Comment by kfirufk** [comment]
thanks
