### ISSUE TITLE
majority of etcd cluster nodes can end up on same machine

### ISSUE THREAD

**Issue by xh3b4sd** [coreos/etcd-operator#926]
Imagine you have three machines, the Kubernetes workers, lets call them A, B and C. Running the etcd operator schedules all three etcd nodes of the new etcd cluster across all three Kubernetes workers, lets call them 1, 2 and 3. When machine A is rebooted, etcd node 1 lands on machine B, which hosts now etcd node 1 and 2. Machine A comes back after reboot and stays empty. When now machine B is rebooted the etcd cluster looses etcd node 1 and 2 at the same time and the etcd cluster is dead due to its lost quorum. How to handle this problem? Should the etcd operator make sure the pods are equally distributed? Should the etcd operator reschedule the etcd nodes? WDYT?

**Comment by xiang90** [comment]
You can set anti-affnity to avoid this from happening. See cluster spec for details.

**Comment by xh3b4sd** [comment]
Just for the record. The link to the information I was looking for is probably this one: https://github.com/coreos/etcd-operator/blob/master/doc/user/spec_examples.md#three-members-cluster-with-node-selector-and-anti-affinity. Thanks for the hint.

**Comment by xiang90** [comment]
@xh3b4sd You are right. Thanks for the hint.
