### ISSUE TITLE
S3 backup only runs once

### ISSUE THREAD

**Issue by ipfaffy** [coreos/etcd-operator#941]
Hi, I have etcd-operator running in Kubernetes- when I create the deployment, I give it the S3 credentials, and that works fine.  My issue is, after it starts, no matter what the `backupIntervalInSecond` is, it will only run the first time, and never again.

I haven't seen anything in the logs about the backup running when I run `kubectl logs -f $podname`, but looking at the mod time of the backup in S3 I can see it isn't being changed, and when I delete/recreate the cluster deployment (to restore the cluster from a backup), any data I pushed after the backup that was first run is gone.  

I've attached my 2 deploys, but they are pretty close to the examples.

[etcd-deployment.txt](https://github.com/coreos/etcd-operator/files/900406/etcd-deployment.txt)
[etcd-operator-deployment.txt](https://github.com/coreos/etcd-operator/files/900413/etcd-operator-deployment.txt)

**Comment by hasbro17** [comment]
Do you change the data in the etcd-cluster at all after the first backup?

You can inspect the logs of the `backup-sidecar` pod which should be named `etcd-testing-backup-sidecar-*****`.
In that you should see something along the lines of:
```
time="2017-04-05T20:18:44Z" level=info msg="getMaxRev: member etcd-testing-0000 revision (3)"
time="2017-04-05T20:18:44Z" level=info msg="getMaxRev: member etcd-testing-0001 revision (3)"
time="2017-04-05T20:18:44Z" level=info msg="getMaxRev: member etcd-testing-0002 revision (3)"
time="2017-04-05T20:18:44Z" level=info msg="skipped creating new backup: no change since last time"
```
After the first backup is created, the next one will be [skipped](https://github.com/coreos/etcd-operator/blob/master/pkg/backup/backup.go#L168-L171) unless you change the data, say by adding or deleting a key in the etcd-cluster.

**Comment by hasbro17** [comment]
Also I'm not sure why your cluster is not restoring from the previous backup. I just double checked on my setup and the restore works fine.
After you delete the `etcd-testing` cluster, can you check your S3 bucket to see if it still has the backup file(`3.1.2_0000000000000001_etcd.backup`) from the last backup?

Also can you show your etcd-operator pod logs around the time when you delete the previous cluster and then launch the new one with the restore configurations. You should see the operator trying to restore from the previous cluster's backup like so:

```
time="2017-04-05T20:13:35Z" level=info msg="Finish reconciling" cluster-name=etcd-cluster-with-s3 pkg=cluster
time="2017-04-05T20:13:39Z" level=info msg="cluster is deleted by the user" cluster-name=etcd-cluster-with-s3 pkg=cluster
time="2017-04-05T20:13:39Z" level=info msg="deleting the failed cluster" cluster-name=etcd-cluster-with-s3 pkg=cluster
time="2017-04-05T20:13:39Z" level=info msg="deleted pod (etcd-cluster-with-s3-0000)" pkg=gc
time="2017-04-05T20:13:39Z" level=info msg="deleted pod (etcd-cluster-with-s3-0001)" pkg=gc
time="2017-04-05T20:13:39Z" level=info msg="deleted pod (etcd-cluster-with-s3-0002)" pkg=gc
time="2017-04-05T20:13:40Z" level=info msg="deleted service (etcd-cluster-with-s3)" pkg=gc
time="2017-04-05T20:13:40Z" level=info msg="deleted service (etcd-cluster-with-s3-backup-sidecar)" pkg=gc
time="2017-04-05T20:13:40Z" level=info msg="deleted replica set (etcd-cluster-with-s3-backup-sidecar)" pkg=gc
time="2017-04-05T20:14:42Z" level=info msg="creating cluster with Spec (spec.ClusterSpec{Size:3, Version:\"3.1.2\", Paused:false, Pod:(*spec.PodPolicy)(nil), Backup:(*spec.BackupPolicy)(0xc4207722c0), Restore:(*spec.RestorePolicy)(0xc4207c3020), SelfHosted:(*spec.SelfHostedPolicy)(nil), TLS:(*spec.TLSPolicy)(nil)}), Status (spec.ClusterStatus{Phase:\"Creating\", Reason:\"\", ControlPaused:false, Conditions:[]spec.ClusterCondition(nil), Size:0, Members:spec.MembersStatus{Ready:[]string(nil), Unready:[]string(nil)}, CurrentVersion:\"\", TargetVersion:\"\", BackupServiceStatus:(*spec.BackupServiceStatus)(nil)})" cluster-name=etcd-cluster-with-s3 pkg=cluster
time="2017-04-05T20:14:42Z" level=info msg="restoring cluster from existing backup (etcd-cluster-with-s3)" cluster-name=etcd-cluster-with-s3 pkg=cluster
time="2017-04-05T20:14:42Z" level=info msg="backup replica set and service created" cluster-name=etcd-cluster-with-s3 pkg=cluster
time="2017-04-05T20:14:42Z" level=info msg="start running..." cluster-name=etcd-cluster-with-s3 pkg=cluster
time="2017-04-05T20:14:50Z" level=warning msg="all etcd pods are dead. Trying to recover from a previous backup" cluster-name=etcd-cluster-with-s3 pkg=cluster
time="2017-04-05T20:14:50Z" level=info msg="cluster created with seed member (etcd-cluster-with-s3-0000)" cluster-name=etcd-cluster-with-s3 pkg=cluster
time="2017-04-05T20:14:58Z" level=info msg="skip reconciliation: running ([]), pending ([etcd-cluster-with-s3-0000])" cluster-name=etcd-cluster-with-s3 pkg=cluster
time="2017-04-05T20:15:06Z" level=info msg="Start reconciling" cluster-name=etcd-cluster-with-s3 pkg=cluster
time="2017-04-05T20:15:06Z" level=info msg="running members: etcd-cluster-with-s3-0000" cluster-name=etcd-cluster-with-s3 pkg=cluster
time="2017-04-05T20:15:06Z" level=info msg="cluster membership: etcd-cluster-with-s3-0000" cluster-name=etcd-cluster-with-s3 pkg=cluster
```

**Comment by ipfaffy** [comment]
Hm- I am fairly certain that the data is changing:

`{mikep:~} $ date; curl -L -X PUT http://REDACTED/v2/keys/foo -d value="bar"
Wed Apr  5 14:41:49 PDT 2017
{"action":"set","node":{"key":"/foo","value":"bar","modifiedIndex":10,"createdIndex":10}}`

After putting new data into etcd using the above, I tail the logs in the backup sidecar pod and see this:

(time differences are due to PST/UTC but the minutes are accurate)

`time="2017-04-05T21:40:47Z" level=info msg="getMaxRev: member etcd1-0000 revision (1)"
time="2017-04-05T21:40:47Z" level=info msg="getMaxRev: member etcd1-0001 revision (1)"
time="2017-04-05T21:40:47Z" level=info msg="getMaxRev: member etcd1-0002 revision (1)"
time="2017-04-05T21:40:47Z" level=info msg="skipped creating new backup: no change since last time"
time="2017-04-05T21:41:47Z" level=info msg="getMaxRev: member etcd1-0000 revision (1)"
time="2017-04-05T21:41:47Z" level=info msg="getMaxRev: member etcd1-0001 revision (1)"
time="2017-04-05T21:41:47Z" level=info msg="getMaxRev: member etcd1-0002 revision (1)"
time="2017-04-05T21:41:47Z" level=info msg="skipped creating new backup: no change since last time"
time="2017-04-05T21:42:47Z" level=info msg="getMaxRev: member etcd1-0000 revision (1)"
time="2017-04-05T21:42:47Z" level=info msg="getMaxRev: member etcd1-0001 revision (1)"
time="2017-04-05T21:42:47Z" level=info msg="getMaxRev: member etcd1-0002 revision (1)"
time="2017-04-05T21:42:47Z" level=info msg="skipped creating new backup: no change since last time"
time="2017-04-05T21:43:47Z" level=info msg="getMaxRev: member etcd1-0000 revision (1)"
time="2017-04-05T21:43:47Z" level=info msg="getMaxRev: member etcd1-0001 revision (1)"
time="2017-04-05T21:43:47Z" level=info msg="getMaxRev: member etcd1-0002 revision (1)"
time="2017-04-05T21:43:47Z" level=info msg="skipped creating new backup: no change since last time"`

So, from what I can tell, even though I am adding new data, it isn't backing up for me.

**Comment by ipfaffy** [comment]
To answer your other questions, there is definitely an initial backup happening, I see it in S3.  I do see the new cluster use it to restore as well, it's just an old backup.

**Comment by xiang90** [comment]
@ipfaffy you put keys into v2 namespace. etcd operator do not backup v2 at all. see: https://github.com/coreos/etcd-operator#limitations
