### ISSUE TITLE
S3 backup storage path should respect namespace

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#946]
See https://github.com/coreos/etcd-operator/blob/master/doc/user/download_backup.md#get-backup-from-s3 .

Currently we stored s3 backup in following path:
```
${BUCKET_NAME}/v1/${CLUSTER_NAME}/
```
It doesn't respect namespace. That means, two cluster having the same name, using the same s3 bucket, but staying in different namespaces could end up in conflict.

**Comment by xiang90** [comment]
fixed by https://github.com/coreos/etcd-operator/pull/1015/commits/5d9384ef71a3224720ba646e761cefd9f82201cd
