### ISSUE TITLE
examples: add RBAC

### ISSUE THREAD

**Issue by philips** [coreos/etcd-operator#956]
With Kubernetes v1.6 RBAC is on by default. We need to ensure that the service account for the Operator has the right roles.

**Comment by hongchaodeng** [comment]
We already have docs: https://github.com/coreos/etcd-operator/blob/master/doc/user/rbac.md

Is this what you are looking for?

**Comment by hongchaodeng** [comment]
I'm closing this since it's already there.
Feel free to reopen it if you want something else

**Comment by philips** [comment]
Oops, sorry, missed it here: https://github.com/coreos/etcd-operator/blob/master/doc/user/op_guide.md

Thanks!
