### ISSUE TITLE
support specifying requests and limits

### ISSUE THREAD

**Issue by JosephSalisbury** [coreos/etcd-operator#959]
Hey!

I'd like to have CPU and memory requests and limits specified on pods created by the operator. 

No strong feelings on whether this is a value specified on the TPR, or computed by the operator itself, or some other option.

Any thoughts?

**Comment by xiang90** [comment]
You can specify it here in podpolicy: https://github.com/coreos/etcd-operator/blob/master/pkg/spec/cluster.go#L118

it is probably a little bit difficult to discovery. a doc improvement PR is welcomed!

**Comment by xiang90** [comment]
closing. the requested feature is already supported as mentioned above.
