### ISSUE TITLE
Upgrade to k8s 1.6

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#963]
Currently, we test etcd operator with k8s 1.5 . k8s 1.6 brings benefits: GC problematic logs reduced, kubectl working with TPR. We should upgrade our jenkins infra to 1.6 and fix problems for it.

**Comment by hongchaodeng** [comment]
We also need to change README: minimum version, replace curl hack with kubectl apply.

**Comment by xiang90** [comment]
we need to move this to 0.2.5

**Comment by hongchaodeng** [comment]
done
