### ISSUE TITLE
Option to update clientURL on etcd pods?

### ISSUE THREAD

**Issue by mcameron** [coreos/etcd-operator#964]
Probably more user education than a bug: I would like to update the clientURL format used to start etcd on each pod with a fqdn so that etcdctl doesn't require hostfile modification to get to the service. 

Please advise.  MY_POD_NAME value does not accept periods in the name.  

<details>
<code>
    client: etcd cluster is unavailable or misconfigured; error #0: dial tcp: lookup etcd-green-shared-non-prod-0001 on 192.168.1.9:53: no such host
    ; error #1: dial tcp: lookup etcd-green-shared-non-prod-0002 on 192.168.1.9:53: no such host
    ; error #2: dial tcp: lookup etcd-green-shared-non-prod-0000 on 192.168.1.9:53: no such host
</code>
</details>

**Comment by hongchaodeng** [comment]
I don't catch the question. Can you clarify? Probably give examples?

**Comment by mcameron** [comment]
When you spin up an example etcd cluster, it gets created with a member list as follows:
```
etcdctl member list
2d96de127aa0c046: name=example-etcd-cluster-0001 peerURLs=http://example-etcd-cluster-0001:2380 clientURLs=http://example-etcd-cluster-0001:2379 isLeader=false
816aca3ce56a296e: name=example-etcd-cluster-0000 peerURLs=http://example-etcd-cluster-0000:2380 clientURLs=http://example-etcd-cluster-0000:2379 isLeader=true
dfc6fa36a7fade9f: name=example-etcd-cluster-0002 peerURLs=http://example-etcd-cluster-0002:2380 clientURLs=http://example-etcd-cluster-0002:2379 isLeader=false
```
I would like to change the clientURLs for each node to use a FQDN so that the cluster can be reached from outside the kubernetes infrastructure it resides in.

**Comment by xiang90** [comment]
@mcameron we will change the member name to their FQDN instead of using the service name in the next release.

**Comment by hongchaodeng** [comment]
This is already solved in https://github.com/coreos/etcd-operator/issues/901 .

It will be in next release.
