### ISSUE TITLE
e2e: operator upgrade tests

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd-operator#989]
- ensure etcd operator can manage the etcd clusters created by the old version of etcd operator
- ensure etcd backup sidecar can pick up backups created by old version of backup sidecar

**Comment by hongchaodeng** [comment]
# Operator Upgrade Test

When we upgrade operator from v1 to v2, we need to make sure it is compatible. Here are some test scenarios we need to check.

## Test Scenarios

- make sure pods created by v1 operator could be managed by v2 operator
  - resize
  - healing 1 member
  - backup could be made by backup sidecar

- make sure backup made by v1 operator could be used by v2 operator
  - disaster recovery
  - restore

**Comment by hasbro17** [comment]
@hongchaodeng is there anything else in this issue that we need to do? Setting up the jenkins job for upgrade tests on a PR perhaps?

**Comment by hongchaodeng** [comment]
All done. Closing

> Setting up the jenkins job for upgrade tests on a PR perhaps?

Nightly job is fine for now.
