### ISSUE TITLE
e2e flake: migrate_boot_member_to_self_hosted_cluster

### ISSUE THREAD

**Issue by hasbro17** [coreos/etcd-operator#992]
failure: https://jenkins-etcd-public.prod.coreos.systems/job/etcd-operator/1719/consoleText

After the etcd-server is ready and is added as a  the cluster size goes up by one and then goes back to zero until the test times out:
`self_hosted_test.go:130: failed to create 3 members etcd cluster: still failing after 12 retries`

The first member is probably not being migrated correctly.

**Comment by hongchaodeng** [comment]
After digging into the operator logs, this is dup to #https://github.com/coreos/etcd-operator/issues/978.

Let's converge there.
