### ISSUE TITLE
etcdctl call etcd-cluster  nodeport error.

### ISSUE THREAD

**Issue by futureskywei** [coreos/etcd-operator#995]
etcd-v3.1.6-linux-amd64/etcdctl --endpoints=http://47.93.46.82:31988 ls
Error:  client: etcd cluster is unavailable or misconfigured; error #0: dial tcp: lookup etcd-cluster-0001.etcd-cluster.mytest1.svc.cluster.local on 100.100.2.138:53: no such host
; error #1: dial tcp: lookup etcd-cluster-0002.etcd-cluster.mytest1.svc.cluster.local on 100.100.2.138:53: no such host
; error #2: dial tcp: lookup etcd-cluster-0000.etcd-cluster.mytest1.svc.cluster.local on 100.100.2.138:53: no such host

**Comment by futureskywei** [comment]
here is my k8s service Object:
"spec": {
"ports": [
{
"name": "client",
"protocol": "TCP",
"port": 2379,
"targetPort": 2379,
"nodePort": 31988
}
],

**Comment by xiang90** [comment]
@futureskywei which version of etcd operator are you using? can you also provide the full service manifest? thanks.

**Comment by hongchaodeng** [comment]
Hi @futureskywei 

Can you provide:
- environment information: k8s version, etcd-operator version, etcdctl version, etc.
- steps to reproduce your issue.

**Comment by hasbro17** [comment]
@futureskywei it seems you are using etcdctl API version 2. For that you need to need to tell etcdctl to not sync with the cluster to update its clientURLs. So you need to pass in the `no-sync` flag.

`etcdctl --no-sync --endpoints http://<public-ip>:<node-port> get foo`

If you use API v3 then this is enabled by default and you should directly be able to access the client url.
`ETCDCTL_API=3 etcdctl --endpoints http://<public-ip>:<node-port> get foo`

**Comment by hongchaodeng** [comment]
@hasbro17 
I think no-sync issue is https://github.com/coreos/etcd-operator/issues/996

**Comment by xiang90** [comment]
@hongchaodeng this is the same issue with #996.

**Comment by futureskywei** [comment]
@xiang90   K8S version :v1.6.2. 
                   etcd-operator version:v0.2.5
                   etcd version:{"etcdserver": "3.1.4","etcdcluster": "3.1.0"}
                   etcdctl version:v3.1.6

ETCDCTL_API=3 etcdctl --endpoints http://<public-ip>:<node-port> get foo   is ok.

But  ETCDCTL_API=2 etcdctl  --endpoints=http://47.93.46.82:31988 get foo  will cause error.
Error:  client: etcd cluster is unavailable or misconfigured; error #0: dial tcp: lookup etcd-cluster-0002.etcd-cluster.mytest1.svc.cluster.local on 100.100.2.138:53: no such host
; error #1: dial tcp: lookup etcd-cluster-0001.etcd-cluster.mytest1.svc.cluster.local on 100.100.2.138:53: no such host
; error #2: dial tcp: lookup etcd-cluster-0000.etcd-cluster.mytest1.svc.cluster.local on 100.100.2.138:53: no such host

**Comment by xiang90** [comment]
ok. i can confirm the problem is what @hasbro17 suggested. you need to specify no-sync to make etcdctl work for v2 api. but please do note that etcd operator does not really support backing up etcd2 cluster. so technically speaking, you should not use etcd2 api at all for the moment.
